pentaho/pentaho-platform-plugin-common-ui

- package-res/resources/web/prompting/pentaho-prompting-components.js
Changes:
Added verifying v.label . This verifying was taken from function dojo.number.format(). Without this verifying, the block try was failed and  valueParsed variable was not correct.
> PRD-5306 - Parameter Date incorrect when publishing to PUC

- .gitignore
- build-res/subfloor-js.xml
- build-res/yuidoc-theme-mindtouch/layouts/main.handlebars
- build-res/yuidoc-theme-mindtouch/partials/attrs.handlebars
- build-res/yuidoc-theme-mindtouch/partials/classes.handlebars
- build-res/yuidoc-theme-mindtouch/partials/events.handlebars
- build-res/yuidoc-theme-mindtouch/partials/index.handlebars
- build-res/yuidoc-theme-mindtouch/partials/method.handlebars
- build-res/yuidoc-theme-mindtouch/partials/module.handlebars
- build-res/yuidoc-theme-mindtouch/partials/options.handlebars
- build-res/yuidoc-theme-mindtouch/partials/props.handlebars
- build-res/yuidoc-theme-mindtouch/partials/sidebar.handlebars
- build.properties
- config/yuidoc-vizapi.json
- package.json
* Adapted subfloor-js.xml (from the Analyzer project) to handle multiple YUIDoc configurations.
* Added the mindtouch YUIDoc template to the build-res directory
* Ant target "doc-js-mindtouch" uses the Mindtouch YUIDoc template
* Ant target "doc-js" uses the default template or whatever is specified in the config document.
* Updated package.json to use the latest YUIDoc version
@pminutillo please review.
> [ENGOPS-1024] Integrate YUIDoc into Subfloor-js

- config/require-config.js
- config/yuidoc-vizapi.json
- package-res/resources/web/dataapi/controller.js
- package-res/resources/web/test/karma/unit/vizapi/DataTableSpec.js
- package-res/resources/web/test/karma/unit/vizapi/DataViewSpec.js
- package-res/resources/web/test/query-sample.html
- package-res/resources/web/vizapi/DataTable.js
- package-res/resources/web/vizapi/VizController.js
- package-res/resources/web/vizapi/ccc/ccc_wrapper.js
- package-res/resources/web/vizapi/ccc/sample/sampleVisualization.js
* Refactoring and YUI Doc Documentation
* Removed DataView combinations feature and VizController.createCombination
* Removed DataTable.makePostable
* Renamed some DataTable and DataView properties to become private ("_")
* Removed DataTable.className and DataView.className (use instance instead)
* CCC_wrapper - removed unnecessary cell value translation from "-" to null. The "-" marker is used only in the PivotTable view.
* Sample visualization: refactored the code to not use private DataTable details.
* Added lint option to YUIDoc config.
Unit testing will come in a future PR.
Sorry for all the white-space changes. I've read somewhere that adding ?w=1 to the url will present diffs that ignore whitespace changed (untested).
@pminutillo please review.
> [BACKLOG-2545] - DataTable - Tidy-up, Document, Unit-Test

- .gitignore
- config/require-config.js
* Fixed karma require config baseUrl to not cause the "no timestamp" error message
* Added common temporary stuff to .gitignore
@pminutillo please review. This is to restore tests and coverage to the common-ui master branch.
> [CLEANUP] Karma baseUrl and .gitignore

- build-res/subfloor-js.xml
- config/context.js
- package-res/resources/web/common-ui-require-js-cfg.js
- package-res/resources/web/util/service.js
* Initial **basic** implementation adapted from Nick's prototype.
* Adding common Require-JS properties to the `requireCfg` object
* Also includes an `requireCfg.config.service` object, for easier configuration of the proposed AMD plugin, whose AMD module id is `service`.
* Here, just changing `subfloor-js.xml` and `config/context.js` (used for testing); but there's a corresponding commit in "pentaho-platform/extensions", to affect the generation of `webcontext.js`.
* I know changing "subfloor-js.xml" is always temporary - this commit would serve to propose the change to ENGOPS.
@pentaho-nbaker please review.
> [BACKLOG-2467] - Implement a standard method for registering Javascript plugin objects

- package-res/resources/web/vizapi/colorPaletteRegistry.js
- package-res/resources/web/vizapi/data/AbstractDataTable.js
- package-res/resources/web/vizapi/data/DataTable.js
- package-res/resources/web/vizapi/data/DataView.js
- package-res/resources/web/vizapi/vizTypeRegistry.js
Had forgotten to document the AMD module Ids of classes/singleton-classes accessible by AMD.
@pminutillo, @DFieldFL please review.
> [BACKLOG-2540] - AMD Conversion - Adding AMD Module ids to documentation

- package-res/resources/web/dojo/pentaho/common/propertiesPanel/Panel.js
- add <span> element to display escaped characters correctly
@rfellows, can you please review it?
I don't like that '<' and others are displayed as &-code, thus I added ```<span>``` to force browser to show them correctly
/cc @pentaho-nbaker, @mdamour1976
> [ANALYZER-3023] - JavaScript injection vulnerability

- package-res/resources/web/dojo/pentaho/common/propertiesPanel/Panel.js
- package-res/resources/web/vizapi/Events.js
- package-res/resources/web/vizapi/VizController.js
- package-res/resources/web/vizapi/ccc/ccc_wrapper.js
* Implemented a ccc wrapper dispose method that disposes the underlying CCC chart, if any, and clears DOM references
* Implemented a VizController dispose method that removes events from it and the viz, if any, and clears DOM references
* Replaced the VizAPI Events implementation by a non-leaky one that stores event listeners directly on the emitting objects
* Was leaking every controller, chart...
* Panel
* .subscriptions and .handles on the prototype... were leaking... a lot
* detaching from DOM events
* calling destroys that weren't being called
* cleared lots of dom references
* fixed this.handles.push[on(...)] ...
@pamval, @diogofscmariano, @bennychow please review.
> [ANALYZER-3058] - Memory leaks during multiple changing of chart type

- config/context.js
- config/karma.ci.conf.js
- config/require-config.js
- package-res/resources/web/prompting/components/StaticAutocompleteBoxComponent.js
- Updated the way cdf code is referenced within code stage.
- In cdf the ability to fully configure the location of the cdf source code was added. This configuration was added in context.js
- Fixed unit test for StaticAutocompleteBoxComponent due to missing jquery.ui dependency
> [BACKLOG-4055]

- package-res/resources/web/prompting/builders/DateInputBuilder.js
- package-res/resources/web/prompting/builders/ExternalInputBuilder.js
- package-res/resources/web/test/prompting/builders/CheckBuilderSpec.js
- package-res/resources/web/test/prompting/builders/DateInputBuilderSpec.js
- package-res/resources/web/test/prompting/builders/DropDownBuilderSpec.js
- package-res/resources/web/test/prompting/builders/ErrorLabelBuilderSpec.js
- package-res/resources/web/test/prompting/builders/ExternalInputBuilderSpec.js
- package-res/resources/web/test/prompting/builders/GarbageCollectorBuilderSpec.js
- package-res/resources/web/test/prompting/builders/LabelBuilderSpec.js
- package-res/resources/web/test/prompting/builders/ListBuilderSpec.js
- package-res/resources/web/test/prompting/builders/MultiButtonBuilderSpec.js
- package-res/resources/web/test/prompting/builders/ParameterGroupPanelBuilderSpec.js
- package-res/resources/web/test/prompting/builders/ParameterPanelBuilderSpec.js
- package-res/resources/web/test/prompting/builders/ParameterWidgetBuilderBaseSpec.js
- package-res/resources/web/test/prompting/builders/PlainPromptBuilderSpec.js
- package-res/resources/web/test/prompting/builders/PromptPanelBuilderSpec.js
- package-res/resources/web/test/prompting/builders/RadioBuilderSpec.js
- package-res/resources/web/test/prompting/builders/SubmitComponentBuilderSpec.js
- package-res/resources/web/test/prompting/builders/TextAreaBuilderSpec.js
- package-res/resources/web/test/prompting/builders/TextInputBuilderSpec.js
- package-res/resources/web/test/prompting/builders/ToggleButtonBaseBuilderSpec.js
- package-res/resources/web/test/prompting/builders/ValueBasedParameterWidgetBuilderSpec.js
- package-res/resources/web/test/prompting/builders/WidgetBuilderSpec.js
- Included unit tests for prompting builders;
- These tests will only test correct building of components, not their behaviour;
- Changed two of the builders to return correct widget (DateInputBuilder and ExternalInputBuilder);
> [BACKLOG-4132] - Develop unit tests for builders

- package-res/resources/web/common-ui-require-js-cfg.js
- package-res/resources/web/test/karma/unit/vizapi/editor/utilsSpec.js
- package-res/resources/web/test/karma/unit/vizapi/spec/helperSpec.js
- package-res/resources/web/vizapi/Wrapper.js
- package-res/resources/web/vizapi/_doc/IVisual.js
- package-res/resources/web/vizapi/_doc/IVisualDrawSpec.js
- package-res/resources/web/vizapi/ccc/visualApiConfig.js
- package-res/resources/web/vizapi/ccc/wrapper/charts/BarChart.js
- package-res/resources/web/vizapi/ccc/wrapper/charts/LineChart.js
- package-res/resources/web/vizapi/ccc/wrapper/charts/MetricDotChart.js
- package-res/resources/web/vizapi/config.js
- package-res/resources/web/vizapi/editor/_doc/IVisualEditorDocument.js
- package-res/resources/web/vizapi/editor/utils.js
- package-res/resources/web/vizapi/sample/visualTypeProvider.js
- package-res/resources/web/vizapi/spec/helper.js
- package-res/resources/web/vizapi/type/_doc/IVisualRoleRequirement.js
- package-res/resources/web/vizapi/type/_doc/IVisualType.js
- package-res/resources/web/vizapi/type/_doc/IVisualTypeConfiguration.js
- package-res/resources/web/vizapi/type/helper.js
This pull-request should only be accepted if https://github.com/pentaho/pentaho-analyzer/pull/656 is also accepted.
* Re-adding CCC/VisualAPI trends synchronization, lost in the last commit
* Fixes highlights not being set in drawSpec when `VisualWrapper#updateHighlights` is called.
* This is required by the GEO plugin.
* The whole highlights functionality is still to be refactored so no tests or great care is given for now.
* Renaming "visualTypeConfig.js" to the more appropriate name "visualApiConfig.js"
* Renaming `VisualEditorUtils#translateEditorProperties` and `IVisualTypeConfiguration#translateEditorProperties` to `#getEditorProperties`. Translation gave the impression of 1-1, and that every source of visualization properties were _editor properties_. Actually, visualization …
> [BACKLOG-2548] VizController - Refactoring - GEO and 12 Days plugins

- package-res/plugin.xml
- package-res/resources/web/common-ui-require-js-cfg.js
* Commenting VizAPI 3 Analyzer plugins in plugin.xml
* Changing the AMD mapping for the CSS plugin as it would use different module ids in build and in production, causing css to be loaded inline, by the build and dynamically as well...
@pamval please review.
> [BACKLOG-4144] - Restore VizAPI 2 visualization implementation

- package-res/plugin.xml
- changed plugin attributes to use the overriding class loader.
> [BACKLOG-4177] - PIR - Filter Specify from the list doesn't work

- package-res/resources/web/prompting/PromptPanel.js
- package-res/resources/web/prompting/components/CompositeComponent.js
- package-res/resources/web/prompting/parameters/ParameterDefinitionDiffer.js
- package-res/resources/web/test/prompting/PromptPanelSpec.js
- package-res/resources/web/test/prompting/parameters/ParameterDefinitionDifferSpec.js
What was done:
1. Refactored processing error's components without re-creating panel.
2. Fix clearing html elements when remove components.
3. Small refactoring
@plagoa @diogofscmariano @rfellows @krivera-pentaho @scottyaslan @pamval please review
> [BACKLOG-4070] Refactor errors processing without re-creating all panel

- package-res/resources/web/prompting/components/DojoDateTextBoxComponent.js
- package-res/resources/web/test/prompting/components/DojoDateTextBoxComponentSpec.js
- Added changes to date picker to allow Dashboards plugin usage
- Added conversion of jquery date format to dojo. Unit tests added to it
- Fixed issue when parameter from dashboards is an array (the use case from Dashboards includes it when the default value is defined in the gwt window of the prompt creation)
- Added formatter from dojo to properly format dates in Dashboards plugin
- Added ability to define start and end date of the date picker (needed for Dashboards plugin)
- Styles still need to be adjusted for Dashboards plugin
> [BACKLOG-4030]

- package-res/resources/web/prompting/PromptPanel.js
- package-res/resources/web/prompting/components/ParameterPanelComponent.js
- package-res/resources/web/prompting/components/PromptLayoutComponent.js
- package-res/resources/web/test/prompting/PromptPanelSpec.js
- package-res/resources/web/test/prompting/components/PromptLayoutComponentSpec.js
- Added logic to avoid need of updating the prompts if the parameter from CDF already has the value selected
- Removed update of all components if valuesArray of a single component have changed
- Fixed issue in report viewer that was not removing the error labels after the user gets the input defined
@pamval @krivera-pentaho @annapopova1 @rfellows @scottyaslan @plagoa please review
Dont merged it yet. Tomorrow i want to do more tests and check every unit test. But the implementation should be finished
> [BACKLOG-4038]

- package-res/resources/web/prompting/PromptPanel.js
- package-res/resources/web/prompting/api/EventAPI.js
- package-res/resources/web/prompting/api/promptApiSample.html
- package-res/resources/web/prompting/components/DojoDateTextBoxComponent.js
- package-res/resources/web/test/prompting/PromptPanelSpec.js
- package-res/resources/web/test/prompting/api/EventAPISpec.js
[BACKLOG-5008] -- Updated prompting event api for beforeRender, afterRender, and parameterChanged callbacks to work correctly. Updated unit tests as well
[BACKLOG-5011] -- fixed unused variable error
> Updated prompting event api and fixed unused variable error

- package-res/resources/web/visual/ccc/wrapper/charts/AbstractChart.js
* Fix regression to the CCC vizs when alternating between vizs with and without measure discrim. (more than one gem in the "measures" gembar).
@pamval please review (this is a regression found by the DET team, back in October)
> [BACKLOG-2544] DataTable - JSON and API changes

- package-res/resources/web/dataapi/models-mql.js
Cherry-pick of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/525
@pamval 
Please review.
> SP-2243 - Backport of PIR-1192 - Interactive Reports does not show fields with datasource name has Japanese characters (5.4 Suite)

- package-res/resources/web/dataapi/models-mql.js
Cherry-pick of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/525
@pamval 
Please review.
> SP-2242 - Backport of PIR-1192 - Interactive Reports does not show fields with datasource name has Japanese characters (6.0 Suite)

- package-res/resources/web/dojo/dijit/themes/pentaho/layout/LayoutPanel.css
- crop long names
(cherry picked from commit 309ed6e)
@krivera-pentaho, review it please. This is a backport of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/532
> [SP-2329] - Backport of ANALYZER-2893 - Long measure names are not rendered correctly on Analyzer Layout pane (6.0 Suite)

- package-res/resources/web/dojo/dijit/themes/pentaho/layout/LayoutPanel.css
- crop long names
(cherry picked from commit 309ed6e)
@krivera-pentaho, review it please. This is a backport of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/532
> [SP-2330] - Backport of ANALYZER-2893 - Long measure names are not rendered correctly on Analyzer Layout pane (5.4 Suite)

- package-res/resources/web/dataapi/cda.js
- package-res/resources/web/dataapi/models-mql.js
- package-res/resources/web/dataapi/models-svc.js
- package-res/resources/web/test/dataapi/cdaSpec.js
- package-res/resources/web/test/dataapi/models-mqlSpec.js
- package-res/resources/web/test/dataapi/models-svcSpec.js
- in cda.js, models-mql.js, models-svc.js
- replace eval() with JSON.parse()
- add tests for valid and invalid input cases
@rfellows, @krivera-pentaho, @diogofscmariano, review it please
> [PPP-3455] - Dynamic code injection vulnerabilities found

- package-res/resources/web/prompting/PromptPanel.js
- package-res/resources/web/prompting/api/OperationAPI.js
- package-res/resources/web/test/prompting/PromptPanelSpec.js
- package-res/resources/web/test/prompting/api/OperationAPISpec.js
- added the ability to getParameterName using a string as an input instead of an object
> [BACKLOG-5837] - Prompt API - Implement setParameterValue

- package-res/resources/web/vizapi/ccc/ccc_wrapper.js
* Extra latitude and longitude columns were not mapped to CCC (cccDimName == null) and later caused problems in the isNullMember test.
At this time, this issue hasn't yet been triaged yet, so please *do not* accept this pull-request yet.
> [ANALYZER-3138] - Sunburst - tooltip does not show when data contains a GEO "location" column

- package-res/resources/web/dataapi/cda.js
- package-res/resources/web/dataapi/models-mql.js
- package-res/resources/web/dataapi/models-svc.js
- package-res/resources/web/test/dataapi/cdaSpec.js
- package-res/resources/web/test/dataapi/models-mqlSpec.js
- package-res/resources/web/test/dataapi/models-svcSpec.js
- in cda.js, models-mql.js, models-svc.js
- replace eval() with JSON.parse()
- add tests for valid and invalid input cases
(cherry picked from commit 4c27f84)
@rfellows, @krivera-pentaho, @diogofscmariano, review it please. This is a backport of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/545
> [SP-2383] - Backport of PPP-3455 - Dynamic code injection vulnerabilities found (6.0 Suite)

- package-res/resources/web/prompting/parameters/ParameterXmlParser.js
- package-res/resources/web/test/prompting/parameters/ParameterXmlParserSpec.js
- cherry picked implementation João (https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/560)
- removed "error" flag from "_getBooleanFromXmlNode" because it's not used
- wrote unit tests
@jvelasques @diogofscmariano @pamval @krivera-pentaho @plagoa please review
> [BACKLOG-6102] Added checking paramDefn properties during parsing

- package-res/resources/web/dataapi/cda.js
- package-res/resources/web/dataapi/models-mql.js
- package-res/resources/web/dataapi/models-svc.js
- package-res/resources/web/test/dataapi/models-mqlSpec.js
- package-res/resources/web/test/dataapi/models-svcSpec.js
- in cda.js, models-mql.js, models-svc.js
- replace eval() with JSON.parse()
- add tests for valid and invalid input cases, except failing (they need changes from 96467f7b6557dfd6207c4f026de1cdc0350c5380)
(adopted from commits 4c27f84, 542c5ed)
@rfellows, @krivera-pentaho, @pamval, review it please. This is a backport of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/545 and https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/566
> [SP-2384] - Backport of PPP-3455 - Dynamic code injection vulnerabilities found (5.4 Suite)

- package-res/resources/web/prompting/PromptPanel.js
- package-res/resources/web/test/prompting/PromptPanelSpec.js
- add _areParamsDifferent() as an additional check for values equality
- change _changeComponentsByDiff() logic: do not call _areParamsDifferent() if it is clear, that update is needed
- add tests for new changes
(adopted from commit b996eb5)
@diogofscmariano, review it please. This is a backport of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/549
> [SP-2416] - Backport of BISERVER-12918 - the report parameter/prompt panel flashes when auto submit off (6.0 Suite)

- package-res/resources/web/pentaho/_doc/nully.jsdoc
- package-res/resources/web/pentaho/data/Cell.js
- package-res/resources/web/pentaho/data/Member.js
- package-res/resources/web/pentaho/type/Context.js
- package-res/resources/web/pentaho/type/Item.Meta.js
- package-res/resources/web/pentaho/type/Property.js
- package-res/resources/web/pentaho/type/list.js
- package-res/resources/web/pentaho/type/object.js
- package-res/resources/web/pentaho/type/simple.js
- package-res/resources/web/pentaho/type/value.js
* Renaming the documentation type `nully` to `Nully`,
to avoid a JSDocs generation bug
@graimundo please review.
> [BACKLOG-5981] - Common Client-Side Metadata Model

- config/jsdoc-vizapi.json
- package-res/resources/web/pentaho/data/_WithCellTupleBase.js
- package-res/resources/web/pentaho/data/_cross/Table.js
- package-res/resources/web/pentaho/data/_trends.js
- package-res/resources/web/pentaho/type/complex.js
- package-res/resources/web/pentaho/type/i18n/types.properties
- package-res/resources/web/pentaho/type/refinement.js
- package-res/resources/web/pentaho/util/error.js
- package-res/resources/web/pentaho/visual/type/helper.js
- test-js/unit/pentaho/type/complex.Spec.js
- test-js/unit/pentaho/type/refinement.Spec.js
- test-js/unit/pentaho/util/error.Spec.js
* Added lots of documentation
* Removed unused error.argEmpty
* Removed error.{argNotArray, argNotNumber, argNotFunction, argNotObject},
in favor of a generalization of the `argInvalidType` method
> [BACKLOG-6289] DEV: Create unit tests and documentation for /pentaho/util/error.js

- package-res/resources/web/pentaho/util/_doc/_namespace.jsdoc
- package-res/resources/web/pentaho/util/object.js
- package-res/resources/web/pentaho/visual/spec/helper.js
- test-js/unit/pentaho/util/object.Spec.js
- Added unit tests and documentation
- Removed functions eachOwnDefined, copyOwnDefined, copyOneDefined
> [BACKLOG-6291] pentaho/util/object.js:

- package-res/resources/web/pentaho/data/_trends.js
- package-res/resources/web/pentaho/lang/ArgumentError.js
- package-res/resources/web/pentaho/lang/ArgumentInvalidError.js
- package-res/resources/web/pentaho/lang/ArgumentInvalidTypeError.js
- package-res/resources/web/pentaho/lang/ArgumentRangeError.js
- package-res/resources/web/pentaho/lang/ArgumentRequiredError.js
- package-res/resources/web/pentaho/lang/Base.js
- package-res/resources/web/pentaho/lang/NotImplementedError.js
- package-res/resources/web/pentaho/lang/OperationInvalidError.js
- package-res/resources/web/pentaho/type/Context.js
- package-res/resources/web/pentaho/type/complex.js
- package-res/resources/web/pentaho/type/facets/DiscreteDomain.js
- package-res/resources/web/pentaho/type/list.js
- package-res/resources/web/pentaho/type/refinement.js
- package-res/resources/web/pentaho/type/value.js
- package-res/resources/web/pentaho/util/error.js
- package-res/resources/web/pentaho/util/text.js
- package-res/resources/web/pentaho/visual/base/View.js
- test-js/unit/pentaho/lang/Base.Spec.js
- test-js/unit/pentaho/type/Context.Spec.js
- test-js/unit/pentaho/type/PropertyMetaCollection.Spec.js
- test-js/unit/pentaho/type/complex.Spec.js
- test-js/unit/pentaho/type/list.Spec.js
- test-js/unit/pentaho/type/value.Spec.js
- test-js/unit/pentaho/type/value.refine.Spec.js
- test-js/unit/pentaho/util/error.Spec.js
- test-js/unit/pentaho/util/errorMatch.js
* Made the error classes public, as they were showing up in public documented
methods in any way.
* Left the private pentaho/util/error façade there, although now it is simply
a mostly empty convenience for not having to require many Error class modules...
* Adapted the testing errorMatch utility
* Moved pentaho/util/error's inner methods to pentaho/util/text
* Added a new Base root for errors: Base.Error, that derives from the native
Error class.
This PR depends on the previous PR https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/644, so don't merge before that one.
> [CLEANUP] Create pentaho.lang.XyzError classes

- package-res/resources/web/dojo/pentaho/common/FilterDialog.js
PIR - Human readable filters and Filters created by prompts are now displaying (None)
> [BACKLOG-6757] - Cherry pick to branch 6.1.0.0

- package-res/resources/web/prompting/PromptPanel.js
- test-js/unit/prompting/PromptPanelSpec.js
Changed nullValueParams condition to ignore single components (Text Area, Text Box, etc.).
Added unit test.
@pamval, @diogofscmariano, @krivera-pentaho, @annapopova1 could you please review?
> [BISERVER-12918] the report parameter/prompt panel flashes when autosubmit off

- package-res/resources/web/pentaho/util/has.js
- package-res/resources/web/pentaho/util/object.js
Creates `pentaho/util/has`. To be expanded as needed. For now, used by `pentaho/util/object`.
> [CLEANUP] Modularize engine dependent checks

- package-res/resources/web/pentaho/util/arg.js
> [CLEANUP] In JsDocs, the methods of `pentaho/util/arg` were appearing in the global scope

- package-res/resources/web/prompting/PromptPanel.js
- package-res/resources/web/prompting/builders/SubmitComponentBuilder.js
- package-res/resources/web/prompting/messages/messages.properties
- package-res/resources/web/prompting/messages/messages_de.properties
- package-res/resources/web/prompting/messages/messages_fr.properties
- package-res/resources/web/prompting/messages/messages_ja.properties
- test-js/unit/prompting/PromptPanelSpec.js
- test-js/unit/prompting/builders/SubmitComponentBuilderSpec.js
- Removed the getString function from the PromptPanel
- Required the localization service on the SubmitComponentBuilder
- Added message properties files with prompting specific messages
- Removed the unit tests from the prompt panel
> [BACKLOG-6898] - Re-implement PromptPanel#getString function

- package-res/resources/web/prompting/PromptPanel.js
- package-res/resources/web/prompting/WidgetBuilder.js
- package-res/resources/web/prompting/builders/DropDownBuilder.js
- package-res/resources/web/prompting/builders/StaticAutocompleteBoxBuilder.js
- test-js/unit/prompting/PromptPanelSpec.js
- test-js/unit/prompting/builders/DropDownBuilderSpec.js
- test-js/unit/prompting/builders/StaticAutocompleteBoxBuilderSpec.js
- Added auto complete component back
- Fixed BISERVER-12961 without having checks on the values array, creating unneeded updates
- Fixed param property, storing the param definition for the component. With the prompt flow, this property was not updated properly causing values to return to its original value
- Updated unit tests accordingly
> [BISERVER-13106]

- package-res/resources/web/prompting/PromptPanel.js
- package-res/resources/web/prompting/WidgetBuilder.js
- package-res/resources/web/prompting/builders/DropDownBuilder.js
- package-res/resources/web/prompting/builders/StaticAutocompleteBoxBuilder.js
- test-js/unit/prompting/PromptPanelSpec.js
- test-js/unit/prompting/builders/DropDownBuilderSpec.js
- test-js/unit/prompting/builders/StaticAutocompleteBoxBuilderSpec.js
- Added auto complete component back
- Fixed BISERVER-12961 without having checks on the values array, creating unneeded updates
- Fixed param property, storing the param definition for the component. With the prompt flow, this property was not updated properly causing values to return to its original value
- Updated unit tests accordingly
> [SP-2535] - Backport of BISERVER-13106

- package-res/resources/web/prompting/PromptPanel.js
- package-res/resources/web/prompting/WidgetBuilder.js
- package-res/resources/web/prompting/builders/DropDownBuilder.js
- package-res/resources/web/prompting/builders/StaticAutocompleteBoxBuilder.js
- package-res/resources/web/test/prompting/PromptPanelSpec.js
- package-res/resources/web/test/prompting/builders/DropDownBuilderSpec.js
- package-res/resources/web/test/prompting/builders/StaticAutocompleteBoxBuilderSpec.js
- Added auto complete component back
- Fixed BISERVER-12961 without having checks on the values array, creating unneeded updates
- Fixed param property, storing the param definition for the component. With the prompt flow, this property was not updated properly causing values to return to its original value
- Updated unit tests accordingly
> [SP-2534] - Backport of BISERVER-13106

- config/karma.conf.js
- config/nodojo.karma.conf.js
- package.json
This uses a mocha-like reporter for the DEV-time karma configs. It prints a nice outline of the test suites, marking them green, red or gray according to success, failure and ignored (https://www.npmjs.com/package/karma-mocha-reporter).
The only problem I see with the reporter is that console.logs get interleaved with the test titles. And code bases like prompting and angular directives abuse of console.log'ing... But this is a problem we already have...
What do you guys think?
@pentaho/millenniumfalcon, @pentaho/orlandocalisbon please review.
> [CLEANUP] Use the "mocha" karma reporter instead of the basic "progress" reporter.

- package-res/resources/web/dataapi/models-svc.js
- package-res/resources/web/dojo/pentaho/common/overrides/dojox/json/ref.js
- in ref.js, replace `eval()` with `JSON.parse()`
- in models-svc.js, replace old-fashioned `pentahoPost()` with `request.post()` from Dojo
(cherry picked from commit 089d23b)
@rfellows, @pamval, review it please. This is a backport of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/610
> [SP-2547] - Backport of PPP-3455 - Dynamic code injection vulnerabilities found (5.4 Suite)

- package-res/resources/web/common-ui-require-js-cfg.js
- Removed duplicate path configuration for the same underscore file
- Added a mapping to guarantee backwards compatibility
> [BACKLOG-6961] Fixed usage of underscore dependency

- package-res/resources/web/pentaho/type/Context.js
- package-res/resources/web/pentaho/type/SpecificationContext.js
- package-res/resources/web/pentaho/type/Type.js
- package-res/resources/web/pentaho/type/_doc/spec/IValueTypeProto.jsdoc
- package-res/resources/web/pentaho/type/_doc/spec/UTypeReference.jsdoc
- test-js/unit/pentaho/type/Context.Spec.js
- test-js/unit/pentaho/type/SpecificationContext.Spec.js
- test-js/unit/pentaho/type/Type.Spec.js
- test-js/unit/require-test.js
- test-js/unit/test-utils.js
* Tried to modularize the helper methods used to build test functions.
* Moved some resulting "primitives" to a new `test-utils.js` AMD module.
* Others, integrated into `require-test.js`
* Support for construction of types from generic type specifications with temporary ids.
> [BACKLOG-6052] More refactoring to Context.Spec + support type construction with temporary ids

- test-js/unit/pentaho/type/Context.Spec.js
- test-js/unit/require-test.js
* `require.using` receives `config` as second argument
* `config` can either be a function to be called with the cloned require or an object to pass to the `config` method
* the previous `using` method signature is still supported
@dcleao This resolves the issue we were seeing last friday. Please review.
> [BACKLOG-6733] Allow config of local require prior to its first use

- package-res/resources/web/dojo/djConfig.js
What was done:
- We can't depend on URL, when extracting locale, as in the moment when this script is executed url looks like this:  
http://localhost:8080/pentaho/api/repos/pentaho-interactive-reporting/prpti.new?ts=1458641503424, and contains no information about locale.
And there is actually no need to extract url parameter each time, as we have a SESSION_LOCALE for this, that is always up-to-date.
- We make pattern more strict: a valid value of a locale parameter is "xx" (language only, no dialect) or "xx_YY" (language with dialect).  If this pattern is not met, we set locale to be 'en' by default.
-  Before setting locale parameter to dojoConfig object we normalize it according to [dojo requirements] (https://github.com/pentaho/pentaho-platform-plugin-common-ui/blob/master/package-res …
> [BISERVER-13167] Specifying locale parameter with dialekt in URL works incorrect

- package-res/resources/web/common-ui-require-js-cfg.js
- package-res/resources/web/pentaho/GlobalContextVars.js
- package-res/resources/web/pentaho/type/Context.js
- test-js/unit/pentaho/GlobalContextVars.Spec.js
- test-js/unit/pentaho/type/Context.Spec.js
* Created a pentaho.GlobalContextVars class that does the dirty work of defaulting
context variables to the values of Pentaho System's global variables.
* Requires rebuild of the whole project dues to require-js-cfg.js changes.
> [BACKLOG-6733] Moving pentaho.type.Context variables to a `vars` property of type pentaho.IContextVars property.

- package-res/resources/web/pentaho/_doc/_namespace.jsdoc
- package-res/resources/web/pentaho/_doc/spec/IContextVars.jsdoc
- package-res/resources/web/pentaho/lang/Base.js
- package-res/resources/web/pentaho/type/ComplexChangeset.js
- package-res/resources/web/pentaho/type/_doc/IConfigurationService.jsdoc
- package-res/resources/web/pentaho/type/_doc/spec/ITypeConfiguration.jsdoc
- package-res/resources/web/pentaho/type/_doc/spec/ITypeConfigurationRule.jsdoc
- package-res/resources/web/pentaho/type/_doc/spec/ITypeConfigurationRuleSelection.jsdoc
- package-res/resources/web/pentaho/type/_doc/spec/UContextVarFilter.jsdoc
- package-res/resources/web/pentaho/type/_doc/spec/UTypeReference.jsdoc
* Also, moved the several variable getters in Context to a new `vars` property,
of type pentaho.IContextVars property.
* Created a pentaho.GlobalContextVars class that does the dirty work of defaulting
context variables to the values of Pentaho System's global variables.
* Requires rebuild of the whole project due to require-js-cfg.js changes.
@pentaho/millenniumfalcon please review. This requires JsDocs review by @swagner8412.
> [BACKLOG-6733] Documentation in JsDocs form

- package-res/resources/web/dojo/djConfig.js
- We can't depend on URL, when extracting locale, as in the moment when this script is executed url looks like this:  http://localhost:8080/pentaho/api/repos/pentaho-interactive-reporting/prpti.new?ts=1458641503424, and contains no information about locale.
And there is actually no need to extract url parameter each time, as we have a SESSION_LOCALE for this, that is always up-to-date.
- We make pattern more strict: a valid value of a locale parameter is "xx" (language only, no dialect) or "xx_YY" (language with dialect).  If this pattern is not met, we set locale to be 'en' by default.
-  Before setting locale parameter to dojoConfig object we normalize it according to dojo requirements.
@rfellows , could you please review it? It's a backport of …
> [SP-2651] Backport of BISERVER-13167 - Specifying locale parameter with dialekt in URL works incorrect (5.4 Suite)

- package-res/resources/web/pentaho/visual/ccc/abstract/View.js
- package-res/resources/web/pentaho/visual/ccc/abstract/ViewDemo.js
Removed TODO comment. It was left there by mistake because we confirmed that 'window.open' is working inside PDI.
> [BACKLOG-7611] Unable to cancel selection in a visualization

- package-res/resources/web/prompting/PromptPanel.js
- package-res/resources/web/prompting/WidgetBuilder.js
- test-js/unit/prompting/PromptPanelSpec.js
- test-js/unit/prompting/WidgetBuilderSpec.js
@pamval, @diogofscmariano, @jvelasques could you please review?
UPD: js tests passed successfully on my local machine: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/765#issuecomment-216277246
Used cherry-picks:
https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/549/commits/b996eb5eedaf58e1f65edd681d6247ecef5adc87
[SP-2652] Backport of BISERVER-12918 - the report parameter/prompt panel flashes when auto submit off (6.1 Suite)
- add _areParamsDifferent() as an additional check for values equality
- change _changeComponentsByDiff() logic: do not call _areParamsDifferent() if it is clear, that update is needed
- add tests for new changes
Conflicts:
package-res/resources/web/prompting/PromptPanel.js
test-js/unit/prompting/PromptPanelSpec.js …
> [SP-2652] Backport of BISERVER-12918 - the report parameter/prompt panel flashes when auto submit off (6.1 Suite)

- package-res/resources/web/pentaho/type/complex.js
- package-res/resources/web/pentaho/type/value.js
- package-res/resources/web/pentaho/visual/base/model.js
- test-js/unit/pentaho/visual/base/model.Spec.js
to be included in toJSON. Added `toSpec({omitProps})` map to complexes.
> [BACKLOG-7614] Prevent data and selectionFilter properties from visual/base

- package-res/resources/web/pentaho/type/changes/ListChangeset.js
- package-res/resources/web/pentaho/type/element.js
- package-res/resources/web/pentaho/type/simple.js
- test-js/unit/pentaho/type/changes/ListChangeset.Spec.js
This is to prevent simple values from being updated, when in reality their content (value, formatted) didn't change.
To escape the need to use 'instanceof' and because we still didn't tackle the Update issue, for now I implemented a default method in element.js that always returns `false`.
Also noticed that a complex value most likely will never be updated with our current implementation of the list algorithm, because when two complex values have the same `key`, even though their content might have changed the object is the same, making the test `existing !== elem` return `true` instead of `false`.
> [BACKLOG-7551] Check the content of a value before setting it for an update change

- package-res/resources/web/pentaho/type/property.js
- package-res/resources/web/pentaho/visual/ccc/pie/model.js
- test-js/unit/pentaho/type/property.Type.Spec.js
[Det-poc PR #69](https://github.com/pentaho/pentaho-det-ee/pull/69) is dependante of this being accepted first, as some of the configuration rules aren't possible without this fix.
> [BACKLOG-9105] Fix bug that was preventing root properties from being configured

- package-res/resources/web/pentaho/data/Attribute.js
- package-res/resources/web/pentaho/data/Cell.js
- package-res/resources/web/pentaho/data/Member.js
- package-res/resources/web/pentaho/data/_AbstractTable.js
- package-res/resources/web/pentaho/data/_Table.js
- package-res/resources/web/pentaho/data/_TableView.js
- package-res/resources/web/pentaho/data/_cross/Table.js
- package-res/resources/web/pentaho/data/_doc/ITableReadOnly.jsdoc
- package-res/resources/web/pentaho/data/_plain/Table.js
- package-res/resources/web/pentaho/type/date.js
- package-res/resources/web/pentaho/util/date.js
- test-js/unit/pentaho/data/AttributeSpec.js
- test-js/unit/pentaho/data/TableSpec.js
- test-js/unit/pentaho/util/date.Spec.js
Supporting Google "datetime" type as an alias to type "date"
Implemented an "as close as possible/needed" ECMA-262 v7 Date.parse in pentaho/util/date.
Changed pentaho/type/date to use the new cross-browser safe date parse function.
Related with https://github.com/pentaho/pentaho-det/pull/266.
> [BACKLOG-10019] Casting date and number values in google data tables.

- package-res/resources/web/dojo/pentaho/common/RowLimitControl.js
- test-js/unit/dojo/pentaho/common/RowLimitControlSpec.js
Treat report row limit as maximum with an exception that we don't show "system limit reached" message in this case.
Per Kurtis we should leave inputs blank if there is no value. It makes things easier because we don't need to wait fro total report rows no more - it allows us to fix several issues at a time in reportviewer ( https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/443 ).
Also it is a good place to hide negative values and Infinity from user and fix BACKLOG-11285.
@tmorgner please review
> [BACKLOG-11284]-Treat report row limit as Maximum

- package-res/resources/web/common-ui-require-js-cfg.js
* The way the AMD re-mapping of the debugInfo module was causing problems in r.js, in Analyzer,
even though, apparently, there’s nothing wrong with using “map” in this situation.
> [CLEANUP][FIX] Debuggability of Client Metadata Model and VizAPI object

- package-res/resources/web/pentaho/visual/ccc/abstract/View.js
* [FIX] Column/Bar/Line/Area/Pie/Donut charts only accept one measure field. This also happens in DET.
> [BACKLOG-8522] Sync Analyzer layout panel with VizAPI 3.0 model

- package-res/resources/web/dataapi/models-mql.js
- replace escape() to encodeURIComponent for encoding request parameters
> [SP-3167][PIR-1296]-Interactive Report Filter never loads when the search characters are Chinese or Japanese.

- package-res/resources/web/prompting/components/SubmitPromptComponent.js
When a user types a value into a mandatory textfield and clicks the 'View report' button, 
the blur event prevents the click event on the button from being fired, so the user is forced to click it again.
A mousedown event is not prevented though, so we can set a timeout for the click logic execution.
If no click event happens the timeout will fire a submit, if it still happens ( for examle the user just clicked the button and no mandatory prompts were involved ) then the timeout is cleared and we are safe from multiple executions.
> [BISERVER-13280]-Support blur and click at the same time

- package-res/resources/web/prompting/PromptPanel.js
Hey @tmorgner 
Your idea with a transient parameter didn't worked well, datepickers chnges caused an infinite loop, lists were not updated unless we requested it by a special flag, also we needed to hide the transient value...
Nevertheless the place for the fix was defined correctly.
What we are doing here - detect if the dashboard and parameter definition are not in sync, update the latest, request a parameter component update, thats it.
Checked for various controls and datatypes, see the params.prpt in the Jira ticket.
> [BACKLOG-13170]-Sync parameter definition with latest user selection

- package-res/resources/web/prompting/components/SubmitPromptComponent.js
Still needed a second click when the 'click' event was fired and the timeout was removed - for some reason the behaviour defined in a parent control was not applied. So, we are unbinding all the handlers and apply our simple logic:
on 'mousedown' 
- call expressionStart
- set timeout for the expresiion call
on 'click' 
- if there is no timeout set, call expression
on timeout 
- call expression and delete a timeout from 'this'
Tested in Chrome, FF and IE
> [BACKLOG-13280]-Ensure only one click is needed to submit a report

- impl/client/src/main/javascript/web/pentaho/visual/ccc/abstract/i18n/model.properties
> [BACKLOG-14317] Missing space in Heat Grid label

- impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js
"Depends" on https://github.com/pentaho/pentaho-analyzer/pull/1417.
> [BACKLOG-14324] Restoring Analyzer tooltip footer in CCC vizs.

- impl/client/src/main/javascript/web/vizapi/ccc/ccc_wrapper.js
> [BACKLOG-14622] Ignore vizApiVersion chart option

- impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.views.conf.js
Add variable decimal digit placeholders to numeric axis tick formatting mask when precision is unspecified.
> [BACKLOG-15078] Decimal placeholders in axis tick formatting

- impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js
- impl/client/src/main/javascript/web/pentaho/visual/models/line.js
- impl/client/src/main/javascript/web/pentaho/visual/models/sunburst.js
Sunburst model properties “labelsOption” and “sliceOrder” are only applicable when “size” is bound.
> [BACKLOG-15223] Hidden sunburst labels don’t show on hover.

- impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js
- Added default color config for MetricDotAbstract Chart
@dcleao please review
> [BACKLOG-14077]

- assemblies/platform-plugin/src/main/resources/plugin.xml
- impl/client/src/main/javascript/web/util/SessionExpiryCheckStartingPoint.js
A global entry point for the session expired dialog logic.
A platform PR https://github.com/pentaho/pentaho-platform/pull/3498
> [BISERVER-12677]-Global JS for the session expired dialog

- impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/line.js
- impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js
* Fixing size of line dots (main, plot2 and trend) and corresponding legend markers to match the UX spec for a lineWidth of 2px
* Legend alignment: when placed at top/bottom, align left; when placed at left/right, align top
* Fixing diamond shape, in legend markers, requiring a bit extra space to not overflow
* Removed legend_overflow extension point, as now the generated legend markers do not normally overflow anymore
* Fixed some configs like disabling marks being hoverable that were not being applied to all instances
(only main plot / only 1st legend group / only 1st axes)
* Removed legend item rule that showed in the line series of Column/Line Combo
@pentaho/millenniumfalcon, @diogofscmariano please review.
> [BACKLOG-15788][BACKLOG-15789] Several styling fixes.

- impl/client/src/main/javascript/web/vizapi/ccc/ccc_wrapper.js
- additinal fixing (for filter 'keep only')
> [ANALYZER-3108]-Selecting a second chart item selects additional items

- package-res/resources/web/vizapi/ccc/ccc_wrapper.js
- additional fixing (keep only filter)
> [SP-3429][Backport of ANALYZER-3108 - Selecting a second chart item selects additional items (6.1 Suite)]

- impl/client/src/main/javascript/web/pentaho/data/_AbstractTable.js
- impl/client/src/test/javascript/pentaho/data/Table.spec.js
* Added AbstractDataTable#filterMatchesRow method.
> [BACKLOG-16390] It is not possible to filter a single row in the data table

- docs/_config.yml
- docs/_includes/default-page-header.html
- docs/_includes/default-site-header.html
- docs/_layouts/intro.html
- docs/_sass/_api-list.scss
- docs/index.md
- docs/platform/bundling.md
- docs/platform/configuration.md
- docs/platform/visual/analyzer-viz-api.md
- docs/platform/visual/configuration.md
- docs/platform/visual/index.md
- docs/platform/visual/samples/bar-d3-sandbox/step2-model-creation.md
- docs/platform/web-package.md
* Removed the parent-title from 1st-level pages, where the site header would just be duplicated
* Removed the word “Pentaho” from a lot of places where it is implied, making the text look clearer
* Removed the word “API” where it could be implied and elsewhere clarified
* Simplified the summaries of the blocks in the top Platform page (and made the dd font lighter and smaller)
* Removed the New star and moved the beta modifier to the site title
* Moved bundling.md from visual to platform.
* In Visualization API promoted the “side-by-side versions” statement to a “warning callout”
> [BACKLOG-16452] Several changes

- impl/client/src/main/javascript/web/pentaho/visual/color/paletteRegistry.js
- impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js
The scatter non-selected points are 100% opaque (shouldn't be) but this is already a known issue by PDUX
> [BACKLOG-16201]  Unable to visually see selections

- package-res/resources/web/dojo/pentaho/common/datasourceselect.js
- src/org/pentaho/common/ui/metadata/model/impl/Category.java
- src/org/pentaho/common/ui/metadata/service/MetadataService.java
- test-src/org/pentaho/common/ui/metadata/model/impl/CategoryTest.java
- test-src/org/pentaho/common/ui/metadata/service/MetadataServiceTest.java
- fixing exception for case when add any field to report
- fixing executing malicious code when datasource deleting
> [SP-3570][PIR-1351]-XSS vulnerability in DataSource name when creating new PIR

- impl/client/src/main/javascript/web/prompting/components/DojoDateTextBoxComponent.js
- date format is used according to the dojo/date/locale
> [PIR-1339] Datepicker in PIR prompt incorrectly applies date format with minutes

- impl/client/src/main/doc-js/pentaho/type/spec/IValueProto.jsdoc
- impl/client/src/main/doc-js/pentaho/type/spec/IValueTypeProto.jsdoc
- impl/client/src/main/javascript/web/pentaho/type/_type.js
- impl/client/src/main/javascript/web/pentaho/type/complex.js
- impl/client/src/main/javascript/web/pentaho/type/facets/discreteDomain.js
- impl/client/src/main/javascript/web/pentaho/type/list.js
- impl/client/src/main/javascript/web/pentaho/type/property.js
- impl/client/src/main/javascript/web/pentaho/type/value.js
- impl/client/src/main/javascript/web/pentaho/visual/role/mapping.js
- impl/client/src/test/javascript/pentaho/type/complex.validation.spec.js
- impl/client/src/test/javascript/pentaho/type/list.validation.spec.js
- impl/client/src/test/javascript/pentaho/type/value.Type.serialization.spec.js
- impl/client/src/test/javascript/pentaho/type/value.validation.spec.js
* Moved validation functions to the Type prototype.
* Removed serialization of methods like `validate` (now `_validate`).
These should be seen as `mixin` type matter, not to be serialized.
Merge with: https://github.com/pentaho/pentaho-det/pull/874
> [BACKLOG-16602] Fixed validation of nested accident types.

- impl/client/src/main/javascript/web/dojo/pentaho/common/datasourceselect.js
- impl/server/src/main/java/org/pentaho/common/ui/metadata/model/impl/Category.java
- impl/server/src/main/java/org/pentaho/common/ui/metadata/service/MetadataService.java
- impl/server/src/test/java/org/pentaho/common/ui/metadata/model/impl/CategoryTest.java
- impl/server/src/test/java/org/pentaho/common/ui/metadata/service/MetadataServiceTest.java
- fixing exception for case when add any field to report
- fixing executing  malicious code when datasource deleting
> [SP-3569][PIR-1351]-XSS vulnerability in DataSource name when creating new PIR

- impl/server/src/main/java/org/pentaho/common/ui/metadata/service/MetadataService.java
- fix for regression: foreign names in datasources list
(should be at the bottom of the list)
> [PIR-1351]-XSS vulnerability in DataSource name when creating new PIR

- impl/client/pom.xml
- impl/client/src/doc/javascript/config/customPlugins/defineTags.js
- impl/client/src/doc/javascript/template/vizApi/tmpl/amd.tmpl
- impl/client/src/doc/javascript/template/vizApi/tmpl/container.tmpl
- impl/client/src/main/doc-js/pentaho/IAmdLoaderPlugin.jsdoc
- impl/client/src/main/doc-js/pentaho/i18n/IService.jsdoc
- impl/client/src/main/doc-js/pentaho/i18n/_namespace.jsdoc
- impl/client/src/main/doc-js/pentaho/service/ILocator.jsdoc
- impl/client/src/main/doc-js/pentaho/service/_namespace.jsdoc
- impl/client/src/main/javascript/web/pentaho/i18n.js
- impl/client/src/main/javascript/web/pentaho/service.js
- impl/client/src/main/javascript/web/pentaho/type/_type.js
- impl/client/src/main/javascript/web/pentaho/type/changes/ListChangeset.js
- impl/client/src/main/javascript/web/pentaho/type/simple.js
- impl/client/src/main/javascript/web/pentaho/visual/color/paletteRegistry.js
- impl/client/src/main/javascript/web/pentaho/visual/role/mapping.js
Only added the commits related with the service/i18n documentation and small tweaks not related to 8.0
Excluded from the cherry-pick things like:
- Point Event
- Mixins
- Refinements
- The last cleanups from @dcleao that are also related with 8.0 code changes
> [BACKLOG-17015] Update Javascript APIs' reference documentation

- impl/client/src/main/javascript/web/pentaho/environment/impl/Environment.js
- impl/client/src/main/javascript/web/pentaho/i18n.js
- Fix for the embedded scenario (in a Pentaho Server and on an external one)
- Added the toString method to the fake URL object, this way we won't run into problems again
by doing `server.root + "some/path"` instead of `server.root.href + "some/path"` in older browsers.
> [BACKLOG-16943] Fixing 'pentaho/i18n' for embedded scenarios

- impl/client/src/main/javascript/web/pentaho/type/changes/Changeset.js
- impl/client/src/main/javascript/web/pentaho/type/changes/ComplexChangeset.js
- impl/client/src/main/javascript/web/pentaho/type/changes/ListChangeset.js
- impl/client/src/main/javascript/web/pentaho/type/changes/Transaction.js
- impl/client/src/test/javascript/pentaho/type/complex.spec.js
`Complex#isDefaultedOf(propName)` would not return `false` when a remote nested
changeset existed in that property's path and when under a transaction.
This affected `Complex#toSpec`, which would not return correct results when
evaluated during a transaction.
All accessible changesets are now created and connected immediately once a primitive change is performed.
> [BACKLOG-18929] DET - First "Drag and Drop" into a drop-zone doesn't work

- impl/client/src/main/javascript/web/pentaho/ccc/visual/all.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/area.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/areaAbstract.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/areaStacked.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/bar.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/barAbstract.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/barHorizontal.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/barLine.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/barNormalized.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/barNormalizedHorizontal.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/barStacked.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/barStackedHorizontal.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/boxplot.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/bubble.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/cartesianAbstract.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/categoricalContinuousAbstract.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/donut.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/heatGrid.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/line.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/metricPointAbstract.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/pie.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/pointAbstract.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/scatter.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/sunburst.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/treemap.js
- impl/client/src/main/javascript/web/pentaho/ccc/visual/waterfall.js
- impl/client/src/main/javascript/web/pentaho/visual/base/view.js
* Fixed CCC views to use relative names to reference base types.
> [BACKLOG-19060] Created the pentaho/ccc/visual/all module to help r.js.

- impl/client/src/main/javascript/web/util/formatting.js
This is the cherry-pick of the fix for [PRD-5939]: Unable to open a prpt that uses several timezones
Fixed typo in parameter name.
> [SP-3810]: Backport of PRD-5939 - Unable to open a prpt that uses several timezones (7.1 Suite)

- impl/client/src/main/javascript/web/pentaho/i18n.js
This was happening because javascript URL omits the port value when it is the scheme default port
> [BACKLOG-20128] Fixed amd i18n loader when using pentaho server on the default http(s) port

- impl/client/src/main/javascript/web/prompting/builders/DropDownBuilder.js
- impl/client/src/test/javascript/prompting/builders/DropDownBuilder.spec.js
- renamed the component property that controls first value selection, from `defaultIfEmpty` to `useFirstValue`, to be consistent with dashboards and common-ui plugins across the platform
> [PDB-1987] Check box filters with no default value set, display the first checkbox as selected

- impl/client/src/main/javascript/web/prompting/builders/DropDownBuilder.js
- impl/client/src/test/javascript/prompting/builders/DropDownBuilder.spec.js
- renamed the component property that controls first value selection, from `defaultIfEmpty` to `useFirstValue`, to be consistent with dashboards and common-ui plugins across the platform
> [SP-3990][PDB-1987] Check box filters with no default value set, display the first checkbox as selected

- impl/client/src/main/javascript/web/prompting/builders/DropDownBuilder.js
- impl/client/src/test/javascript/prompting/builders/DropDownBuilder.spec.js
- renamed the component property that controls first value selection, from `defaultIfEmpty` to `useFirstValue`, to be consistent with dashboards and common-ui plugins across the platform
> [SP-3989][PDB-1987] Check box filters with no default value set, display the first checkbox as selected

- impl/client/src/main/javascript/web/dojo/pentaho/common/RowLimitControl.html
- impl/client/src/main/javascript/web/dojo/pentaho/common/RowLimitControl.js
The fix from https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1221/commits/c67ab3d677f85e821e5e57c8777e6dafcdf61365 doesn't not work for all cases so it should be replaced with a custom event handling.
@tmorgner , @kcruzada, @Aliaksandr-Kastenka, @annapopova1 please review.
> [PRD-5827] - Browser freezes when marking elements on the report toolbar and trying to put data in from keyboard - prevent default handler

- impl/client/src/main/javascript/web/prompting/PromptPanel.js
- add widget parameter to allow it's builder to react to parameter value changes
- stops executing updates when the CDF component has 'isManaged' set to 'false'
> [BACKLOG-22104] DEV: avoid select filter full redraw when feeding data

- impl/server/pom.xml
**Warning**: To be merged together with all other projects that need this change, please do not merge until then
**This PR relates to:**
https://github.com/pentaho/pentaho-commons-database/pull/152
https://github.com/pentaho/apache-vfs-browser/pull/42
https://github.com/pentaho/data-access/pull/992
https://github.com/pentaho/mondrian/pull/1033
https://github.com/pentaho/pdi-jms-plugin/pull/53
https://github.com/pentaho/pdi-platform-utils-plugin/pull/92
https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/76
https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/39
https://github.com/pentaho/big-data-plugin/pull/1340
https://github.com/pentaho/pentaho-cassandra-plugin/pull/106
https://github.com/pentaho/pentaho-data-mining/pull/15 …
> [BACKLOG-19695] Update commons-vfs2 artifact version from 2.1 to 2.2

- impl/client/src/main/javascript/web/pentaho/data/_AbstractTable.js
- impl/client/src/main/javascript/web/pentaho/data/filter/_core/isEqual.js
- impl/client/src/main/javascript/web/pentaho/data/filter/abstract.js
- impl/client/src/main/javascript/web/pentaho/data/util.js
- impl/client/src/main/javascript/web/pentaho/visual/action/SelectionModes.js
- impl/client/src/main/javascript/web/pentaho/visual/base/abstractModel.js
- impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js
- impl/client/src/main/javascript/web/pentaho/visual/role/abstractMapping.js
- impl/client/src/test/javascript/pentaho/data/util.spec.js
- impl/client/src/test/javascript/pentaho/visual/base/abstractModel.spec.js
Merge along with https://github.com/pentaho/pentaho-analyzer/pull/1781.
> [BACKLOG-22097] Filter rows with all null measures on SelectionModes.

- impl/client/src/test/javascript/pentaho/visual/role/externalProperty.spec.js
Added tests for:
- externalProperty#category
- externalProperty#ordinal
- externalProperty#label
- externalProperty#description
- externalProperty#helpUrl
- externalProperty#isBrowsable
- externalProperty#isApplicableOn
> [BACKLOG-21825] Unit tests for 'externalProperty'

- impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/EntityWithNumberKeyStrategy.js
- impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/Strategy.js
* Caused the "color" visual role of the scatter chart not to propagate DET's internal model `countMax: 1` constraint.
Still for 8.2.
> [BACKLOG-26058] Fix `EntityWithNumberKeyStrategy` not being marked as an "identity" strategy.

- impl/client/src/main/javascript/web/pentaho/type/InstanceType.js
- impl/client/src/main/javascript/web/pentaho/type/loader.js
- impl/client/src/main/javascript/web/pentaho/util/url.js
These are documentation only changes, but they should enter the branch because the generated documentation will point to the 8.2.0.0-R tag and it contains links to the source code.
@kcruzada, @pamval, @pentaho-jlien, @pentaho-svigneri please merge.
> [BACKLOG-26361] Fixes to VizAPI's JsDocs documentation.

- impl/client/src/test/javascript/pentaho/type/Instance.spec.js
> [BACKLOG-27908] Fix forgotten `fdescribe`.

- impl/client/src/main/javascript/web/prompting/parameters/ParameterDefinitionDiffer.js
- impl/client/src/test/javascript/prompting/parameters/ParameterDefinitionDiffer.spec.js
Bug fix: Activating auto-refresh after adding a prompt in an Interactive Report causes report to become non-responsive
> [PIR-1442] Activating auto-refresh after adding a prompt in an Interactive Report causes report to become non-responsive

- impl/client/src/main/javascript/web/pentaho/visual/impl/View.js
@kcruzada please merge.
We need to update the 8.3 branch to be able to generate the fixed JavaScript reference documentation from it.
Related master PR: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1452.
/cc @pentaho/millenniumfalcon
> [BACKLOG-29550] Fix JS documentation for class `pentaho.visual.impl.View`

- impl/client/src/main/javascript/web/prompting/parameters/ParameterDefinition.js
- impl/client/src/test/javascript/prompting/parameters/ParameterDefinition.spec.js
@pentaho/tatooine @ssamora @pentaho-lmartins @tmorgner
* [BISERVER-14306] Fix tied to this ticket. Needed to add a option for timezoneHints to be persisted with the parameter values (if it exists). This is because when a prompt parameter is created, it sets it to whatever the server sets it to be (checking the node value), so most of the time, it will be undefined (unless it's a date object).  So it's important to persist this, especially when you're dealing with changing from a timezone without DST and a timezone with one (i.e. March 10, 2019 -> EST, March 11, 2019 -> EDT).
Pull Request is from a set of two PRs:
* https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/738
* https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1475
> [BISERVER-14306] Multi Value List parameter values are reset after changing output type in a prpt report

- impl/client/src/main/javascript/web/pentaho/shim/css.escape.js
Adding shim to provide `CSS.escape` and enable escaping CSS class names.
Merge this one followed by, in order:
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/744
- https://github.com/pentaho/pentaho-platform/pull/4582
- https://github.com/pentaho/pentaho-platform-ee/pull/1366
> [BACKLOG-31795] Layout Editor CRUDL

- impl/client/src/main/doc-js/pentaho/csrf/_namespace.jsdoc
We don't want to reveal the documentation for the CSRF API just yet, as this will not be available for all customers in 9.0.
Also, the documented version has the identifier `pentaho/csrf/service` and, under the pending CSRF refactoring, this module has moved to a Web Package module published under the identifier `@pentaho/csrf`...
Another module, `common-ui/util/pentaho-csrf`, was defined some commits ago to be used by AMD modules which are not in WebPackages. We have not replaced all internal uses of `pentaho/csrf/service` for `common-ui/util/pentaho-csrf`, but this is acceptable, as it is an internal implementation detail.
> [BACKLOG-31898] Hide the CSRF client API documentation.

- impl/client/src/main/javascript/web/prompting/components/StaticAutocompleteBoxComponent.js
@pentaho/tatooine @pentaho-lmartins @ssamora 
* [PRD-6038] Adding in check for IE11 and Edge to handle cursor placement without losing focus.
> [PRD-6038] Auto-complete feature of Text Box is not working as expected when using a query to limit the results returned.

- impl/server/pom.xml
@pentaho/tatooine @pentaho-lmartins @ssamora 
* [PDI-17775] Cleaning up version references to old commons-vfs2, unifying under maven parent pom. Removing unused, declared dependency reference.
This PR is a part of a series of PR to upgrade commons-vfs2 and fix VFS issues with HTTP:
- https://github.com/pentaho/apache-vfs-browser/pull/60
- https://github.com/pentaho/big-data-plugin/pull/1929
- https://github.com/webdetails/cpk/pull/85
- https://github.com/pentaho/data-access/pull/1083
- https://github.com/pentaho/maven-parent-poms/pull/185
- https://github.com/pentaho/mondrian/pull/1177
- https://github.com/pentaho/pdi-jms-plugin/pull/73
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/102
- https://github.com/pentaho/pdi-plugins-ee/pull/139
- …
> [PDI-17775] Process Files step no longer supports HTTP scheme

- impl/server/pom.xml
This reverts commit 6521236a5ed27096ddbbe5e2ef9b7be96fe7a565, reversing
changes made to 2885d462559f8937f7619597798eb91451f9f51d.
This Revert PR is part of a series:
- https://github.com/pentaho/maven-parent-poms/pull/229
- https://github.com/pentaho/apache-vfs-browser/pull/62
- https://github.com/pentaho/big-data-plugin/pull/2040
- https://github.com/webdetails/cpk/pull/87
- https://github.com/pentaho/data-access/pull/1091
- https://github.com/pentaho/mondrian/pull/1202
- https://github.com/pentaho/pdi-jms-plugin/pull/76
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/104
- https://github.com/pentaho/pdi-plugins-ee/pull/174
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/84
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/53
- …
> Revert "Merge pull request #1503 from gryphendowre/SP-5370"

- impl/client/src/main/javascript/web/prompting/components/StaticAutocompleteBoxComponent.js
@pentaho-lmartins 
@ssamora 
@smmribeiro 
It was always setting a null value when it doesn't receive a initial value from parameter. 
A similar check was already in create method.
> [BISERVER-14512] - Text box values are only displayed for about a second in prpt reports published to PUC

- impl/client-config/client-config/src/main/resources-filtered/config.js
- especially, regarding Viz. API 2 style equivalence
The links to the Pentaho Help documentation are for the future 9.2 version. I tested these with the 9.1 version and then changed them to 9.2, because the 9.2 Viz. API reference documentation is still being updated (specifically, in the context of [BACKLOG-32090](https://jira.pentaho.com/browse/BACKLOG-32090)).
The comments containing `// region` and `// #region` define collapsible code regions for IntelliJ and Visual Studio Code, respectively. Curiously, the comment `// #endregion` works for both.
[EDIT] Regarding the Viz. API 2 styles, one interesting note. Replacing all of the occurrences of the text:
```
// [Viz. API 2 Style] Uncomment:
// 
```
with an empty string, will activate all Viz. API 2 graphical styles.
@bennychow please …
> [ANALYZER-4000] Provide more examples of VizAPI configuration

- impl/client/src/main/doc-js/pentaho/environment/spec/IEnvironment.jsdoc
- impl/client/src/main/javascript/web/pentaho/data/_WithCellTupleBase.js
- impl/client/src/main/javascript/web/pentaho/environment/impl/Environment.js
- impl/client/src/main/javascript/web/pentaho/i18n/serverService.js
- impl/client/src/main/javascript/web/pentaho/visual/config.js
- impl/client/src/test/javascript/pentaho/environment/impl/Environment.spec.js
- impl/client/src/test/javascript/pentaho/environment/main.spec.js
- Fix for being able to run in the new Rhino 1.7.13 used by CGG
- The Environment class now normalizes and validates the specified locale
- New formatting function for Cartesian Axes' ticks via the `timeSeriesAxisTickFormatter` extension point
This PR is part of a PR set: https://github.com/webdetails/cgg/pull/148.
@davidmsantos90, @afrjorge, @bennychow please review.
/cc @jcarneirohv
> [ANALYZER-3942] Localized date tick formatting for CCC based stock visualizations

- impl/client/src/main/javascript/web/pentaho/visual/config.js
Now using the formatting information of the _first_ dimension of the visual role.
@bennychow please review.
> [ANALYZER-2977] Fix incorrect use of singleDimensionType in multi-dimension visual role

- impl/client/src/main/javascript/web/pentaho/visual/config.js
@bennychow please review and merge.
This follows from the decision to spin-off the PDI/DET support, from https://jira.pentaho.com/browse/ANALYZER-3942,  to another story https://jira.pentaho.com/browse/PDI-19372.
The proposed changes make the date formatting code tolerant to the inexistance of the `Intl` browser API, as is currently the case on PDI/DET on Linux. It will continue behaving as it did before.
> [ANALYZER-3942] Make date formatting robust against Intl API missing (PDI/DET)

- impl/client/src/main/doc-js/pentaho/config/impl/_namespace.jsdoc
- impl/client/src/main/javascript/web/pentaho/_core/config/Service.js
- impl/client/src/main/javascript/web/pentaho/config/impl/Service.js
- impl/client/src/main/javascript/web/pentaho/platformCore.js
- impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js
- impl/client/src/test/javascript/pentaho/config/impl/Service.spec.js
Must be merged together with: https://github.com/webdetails/cgg/pull/158.
@himanshu6201, @varuntangirala, @NJtwentyone please review.
> [BACKLOG-36156] Create a new JS module (pentaho/config/Service) that exposes the existing Configuration Service class/constructor

- impl/client-config/client-config/src/main/resources-filtered/config.js
- Changed from `help.pentaho.com` to the current `help.hitachivantara.com` to avoid the redirect
- Fixed the base URL paths, which were missing the `/Pentaho/` section...
@himanshu6201, @varuntangirala, @NJtwentyone, @rmansoor please review.
> [BACKLOG-36318] Fix config.js Pentaho help URLs

- impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js
PR set: https://github.com/pentaho/pentaho-analyzer/pull/2287
(Follows https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1581 which was inadvertently closed due to deleting of the target branch)
> [BACKLOG-36160] Declare the stock CCC/View class hierarchy to the JS Modules API

- assemblies/platform-plugin/src/main/resources/plugin.xml
- impl/client/src/main/javascript/web/util/_dialog.js
@pentaho/wcag, please review.
Stories:
- [BACKLOG-36879](https://hv-eng.atlassian.net/browse/BACKLOG-36879)
- [BACKLOG-37033](https://hv-eng.atlassian.net/browse/BACKLOG-37033)
- [BACKLOG-37034](https://hv-eng.atlassian.net/browse/BACKLOG-37034)
Merge together with:
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/847
- https://github.com/pentaho/pentaho-commons-xul/pull/212
- https://github.com/pentaho/pentaho-platform/pull/5226
Handles defaulting, trapping and restoring back focus for "JS dialogs" (especially, modal dialogs).
Can be used by "any" library.
In associated PRs it is included the use by GWT / XUL dialogs.
Clicking in some empty places of GWT dialogs can still make the focus to be "lost" (into the body...).
Focusing into iframes is not yet supported as is (cf. …
> [BACKLOG-36879][BACKLOG-37033][BACKLOG-37034] GWT/XUL Dialogs Default, Trap and Restore Focus

- impl/client/src/main/javascript/web/util/_dialog.js
@pentaho/wcag, please review.
- Removed async focusing which was causing issues in the detection of element to restore focus to, as well as in restoring it
Merge with:
- https://github.com/pentaho/pentaho-platform/pull/5236
> [BACKLOG-37034] Fix restore focus for BootstrapJS dialogs

- assemblies/platform-plugin/src/main/resources/plugin.xml
- impl/client/src/main/javascript/web/util/_dialog.js
- impl/client/src/main/javascript/web/util/_focus.js
@pentaho/wcag, please review.
- Refactored `_dialog.js`; moved the jQuery `:pen-tabbable` and `:pen-focusable` selectors to a new file, `_focus.js`
- Tabbable functions look into the content of iframes, if from same domain
- Added two new utility functions: `nextTabbable` and `previousTabbable` which are needed to meet the needs of other stories (`CustomDropDown` tab behavior, used for PUC's "Perspectitves" and "User" dropdowns). There are two new matching functions in the GWT project. 
Merge with:
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/851
- https://github.com/pentaho/pentaho-platform/pull/5238
> [BACKLOG-36879][BACKLOG-37033][BACKLOG-37034] Improve tabbing functions to look into iframes' content

- impl/client/src/main/javascript/web/dojo/pentaho/common/Dialog.js
Please review @pentaho/wcag 
Merge with https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/906
> [BACKLOG-37971] - Set proper focus order for 'datatabpanel' after clicking cross button

- impl/client/src/main/javascript/web/dojo/pentaho/common/datasourceselect.js
@pentaho/wcag Please review for https://hv-eng.atlassian.net/browse/BACKLOG-38174 .
the msgBox in  `deleteDatasource2` closes after confirming the deletion operation. The edit button is disabled after selected model is deleted.  Setting the add button to be the dialogOpener for msgBox (in this case), so that focus doesn't go to disabled edit button.
> [BACKLOG-38174] Restoring focus after deleting selected data source

- impl/client/src/main/javascript/web/dojo/pentaho/common/angularjs/themes/styles.css
Story/Task: [BACKLOG-38656](https://hv-eng.atlassian.net/browse/BACKLOG-38656)
/cc @pentaho/hoth
- Hidden by default via CSS
- Still preserves ability to close via ESC key
[BACKLOG-38656]: https://hv-eng.atlassian.net/browse/BACKLOG-38656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-37873] Hide HostDialog's close button by default

- impl/client/src/main/javascript/web/dojo/pentaho/common/angularjs/HostDialog.js
Story/Task: [BACKLOG-38649](https://hv-eng.atlassian.net/browse/BACKLOG-38649)
/cc @pentaho/hoth
- Makes sure to override `dijit/DialogUnderlay` to use the Pentaho `glasspane` class
[BACKLOG-38649]: https://hv-eng.atlassian.net/browse/BACKLOG-38649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-37873] Styled AngularJS HostDialog's modal backdrop/glasspane

- assemblies/platform-plugin/src/main/resources/themes.xml
- Also, added the new shared `base.css` stylesheet, including rules for basic responsive primitives, to supported themes
Part of PR set: https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/41
/cc @pentaho/hoth
> [BACKLOG-37873][BACKLOG-38655] Changed `themes.xml` to declare responsive themes

- impl/client/src/main/javascript/web/pentaho/ccc/visual/Waterfall.js
- impl/client/src/main/javascript/web/pentaho/visual/models/Waterfall.js
Water-Direction property for waterfall shown twice.
> [BACKLOG-38919] Fixed Properties for Waterfall Chart

- impl/client/src/main/javascript/web/dojo/pentaho/common/Dialog.js
Move buttons to correct div location to be navigable via tab
> [BACKLOG-39166] Ensure Page Setup Dialog Buttons are Keyboard Navigable

- impl/client/src/main/javascript/web/prompting/pentaho-prompting.css
cut off when rendered in an iframe.
> [BACKLOG-39139] Fix css overflow handling to prevent content from being

- impl/client/src/main/javascript/web/prompting/pentaho-prompting.css
> [BACKLOG-39139] Leave original default overflow in place for

- impl/client/src/test/javascript/prompting/PromptPanel.spec.js
- impl/client/src/test/javascript/prompting/api/EventAPI.spec.js
PromptPanel.spec.js and EventAPI.spec.js had unit tests failing because of the focus logic introduced in PromptPanel's refresh method
cc: @pentaho/wcag
> test(frontend): fix failing unit tests [BACKLOG-37967]

- impl/client/src/main/config/javascript/build.js
In the new version of uglify-js some default values for the 'compress' options changed and cause loss of functionality in our code.
- [uglify-js v2 compress options](https://www.npmjs.com/package/uglify-js2#compressor-options)
- [uglify-js v3 compress options](https://www.npmjs.com/package/uglify-js#compress-options)
@pentaho/millenniumfalcon @dcleao please review
> fix: event listener of 'change:init' failed [BACKLOG-40956]

- impl/client/pom.xml
- impl/client/src/main/assembly/dependencies-js-assembly.xml
- impl/client/src/main/javascript/web/dojo/pentaho/common/MessageBox.js
- impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js
- pom.xml
instead of blindly encoding all html to prevent xss attacks, that caused the regression by encoding valid html used for formatting, will use [DOMPurify](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page#html_sanitization) to only remove harmful html.
cc: @peterrinehart
> fix: MessageBox usage with html in title and message [BACKLOG-40907]

- impl/client/pom.xml
- impl/client/src/main/assembly/dependencies-js-assembly.xml
- impl/client/src/main/javascript/web/dojo/pentaho/common/MessageBox.js
- impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js
- pom.xml
Original PRs:
- [PPP-5061](https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1769)
- [BACKLOG-40907](https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1776)
Didn't include the **lint** done in the `PPP-5061` PR because PhantomJS doesn't support the modern javascript syntax.
- that is also why for this backport the version of `dompurify` was downgraded from `3.1.5` to `2.5.6`
Need to include the `BACKLOG-40907` PR as the fix in `PPP-5061` broke some plugins behavior
[PPP-5061]: https://hv-eng.atlassian.net/browse/PPP-5061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BACKLOG-40907]: https://hv-eng.atlassian.net/browse/BACKLOG-40907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
> [SP-6583] Backport of PPP-5061 - Sanitize messages and title in message box (9.3 Suite)

- impl/client/src/main/javascript/web/dojo/pentaho/common/overrides/dojo/store/Memory.js
- impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js
from `1.9.2` to `1.17.3` the major change in `dojo/store/Memory.js`
was in the `put` method, that was also the method we were changing in the override.
In the new version they added logic for the `before` option, but
left out the logic for the `parent` option, which we rely on so that PIR filters work as expected.
- 1.9.x `dojo/store/Memory.js` original [put method](https://github.com/dojo/dojo/blob/1.9/store/Memory.js#L58-L83)
- 1.9.x `dojo/store/Memory.js` override [put method](https://github.com/pentaho/pentaho-platform-plugin-common-ui/blob/10.0/impl/client/src/main/javascript/web/dojo/pentaho/common/overrides/dojo/store/Memory.js#L65-L130)
Fix regression caused by: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1788
> fix: indent Issue on PIR report creation [BACKLOG-42478]

- impl/client/src/main/javascript/web/dojo/pentaho/common/overrides/dojo/store/Memory.js
- impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js
fix filter indent issue on PIR report creation.
from "1.9.2" to "1.17.3" the major change in "dojo/store/Memory.js" was in the "put" method, that was also the method we were changing. In the new version they added logic for the "before" option, but left out the "parent" option, which we rely on so that PIR filters work as expected.
- Original [commit](https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1795/commits/ed8099d4f5bb13e3adfbb6a770325230c0913176)
> [SP-6590] Backport of PPP-4824 - Vulnerable Component: dojo 1.9.3 (10.2 Suite)

- impl/client/src/main/javascript/web/util/_a11y.js
The issue relates to this dialog: https://github.com/pentaho/pentaho-analyzer/blob/d350af40eb9a193670940509aedf194c25a92ff8/client/src/main/javascript/scripts/report/cv_rptFilterDlg.js
If there are any concerns about this change affecting other components elsewhere in Pentaho, I did search for that problem, and found out that this accessible listbox (the element affected by this change) is only used in the dialog mentioned above.
@pentaho/tatooine_dev
> [ANALYZER-4145] - Multiselect feature for Analyzer Report Filter no longer requires holding CTLR key

- impl/client/src/main/javascript/web/prompting/components/StaticAutocompleteBoxComponent.js
In my humble opinion, looking at the code is doesn't make much sense to set the input value on its updated method.
Having that said, and since I'm not aware of all the possible use cases I added an extra condition that checks if the input is focused, and if it is, it won't be updated.
> fix: typing too fast in the input sometimes would refresh it [PRD-6156]
