pentaho/pentaho-platform-plugin-common-ui

package-res/resources/web/prompting/pentaho-prompting.js

[BACKLOG-1961] Add flag for parameter changes

---

.gitignore
build-res/subfloor-js.xml
build-res/yuidoc-theme-mindtouch/layouts/main.handlebars
build-res/yuidoc-theme-mindtouch/partials/attrs.handlebars
build-res/yuidoc-theme-mindtouch/partials/classes.handlebars
build-res/yuidoc-theme-mindtouch/partials/events.handlebars
build-res/yuidoc-theme-mindtouch/partials/index.handlebars
build-res/yuidoc-theme-mindtouch/partials/method.handlebars
build-res/yuidoc-theme-mindtouch/partials/module.handlebars
build-res/yuidoc-theme-mindtouch/partials/options.handlebars
build-res/yuidoc-theme-mindtouch/partials/props.handlebars
build-res/yuidoc-theme-mindtouch/partials/sidebar.handlebars
build.properties
config/yuidoc-vizapi.json
package-res/resources/web/vizapi/ISelection.doc.js
package-res/resources/web/vizapi/IViz.doc.js
package-res/resources/web/vizapi/IVizCallbacks.doc.js
package-res/resources/web/vizapi/IVizCreateOptions.doc.js
package-res/resources/web/vizapi/IVizDrawOptions.doc.js
package-res/resources/web/vizapi/SelectionMode.doc.js
package-res/resources/web/vizapi/meta/IGeneralRequirement.doc.js
package-res/resources/web/vizapi/meta/IGeneralRequirementUI.doc.js
package-res/resources/web/vizapi/meta/IRequirement.doc.js
package-res/resources/web/vizapi/meta/IRequirementSet.doc.js
package-res/resources/web/vizapi/meta/IVisualRoleRequirement.doc.js
package-res/resources/web/vizapi/meta/IVizType.doc.js
package-res/resources/web/vizapi/meta/UIType.doc.js
package-res/resources/web/vizapi/meta/module.doc.js
package-res/resources/web/vizapi/module.doc.js
package.json

Sorry this includes the commit in the previous (ENGOPS-1024) pull-request.
This PR is specifically for [BACKLOG-2546] and [BACKLOG-2547] — IViz and IVizType documentation.
@pminutillo please review.

Backlog 2547

---

package-res/resources/web/vizapi/ccc/ccc_wrapper.js

@e-cuellar, @mdamour1976  could you merge it?

[ANALYZER-2933] Fixes tooltip not showing "measure interpolated" suffix for interpolated measures.

---

config/karma.ci.conf.js

* Activating JS code coverage for VizAPI

[BACKLOG-2545] - DataTable - Tidy-up, Document, Unit-Test

---

package-res/resources/web/prompting/pentaho-prompting.js

@dcleao @rfellows 
Please review.

Backport of PRD-5398 - Prompt screen flashes and take user back to the top again

---

package-res/resources/web/prompting/pentaho-prompting.js

@dcleao @rfellows 
Please review.

[SP-1771] Backport of PRD-5398 - Prompt screen flashes and take user back to the top again

---

package-res/resources/web/dojo/pentaho/common/propertiesPanel/Panel.js
package-res/resources/web/test/dojo/pentaho/common/propertiesPanel/panelSpec.js

@pentaho-nbaker, @rfellows, @mdamour1976, review it please

[ANALYZER-3023] - JavaScript injection vulnerability

---

package-res/resources/web/vizapi/ccc/ccc_wrapper.js

@dcleao, @mdamour1976, @rfellows Could you review and merge it?
It is issue for 5.4  fix according https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/343#issuecomment-98758981

[ANALYZER-2933] Tooltip of Line chart on part regarding empty cell shows a value

---

config/require-config.js
package-res/resources/web/test/karma/unit/util/serviceSpec.js
package-res/resources/web/util/service.js

* Unit tests.
* Some fixes.
* Improved documentation.
@pentaho-nbaker please review.

[BACKLOG-2467] - Implement a standard method for registering Javascript plugin objects

---

package-res/resources/web/dojo/pentaho/common/propertiesPanel/Panel.js
package-res/resources/web/vizapi/Events.js
package-res/resources/web/vizapi/VizController.js
package-res/resources/web/vizapi/ccc/ccc_wrapper.js

@dcleao, review it please.
These are two backports of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/383 and https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/384. The first one was done manually, as cherry-pick failed.
/cc @diogofscmariano

Analyzer 3058 5.3.0.4

---

package-res/resources/web/dojo/pentaho/common/propertiesPanel/Panel.js
package-res/resources/web/vizapi/Events.js
package-res/resources/web/vizapi/VizController.js
package-res/resources/web/vizapi/ccc/ccc_wrapper.js

@dcleao, review it please.
These are two backports of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/383 and https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/384. The first one was done manually, as cherry-pick failed.
/cc @diogofscmariano

Analyzer 3058 5.3

---

package-res/resources/web/test/dojo/dom-geometry-Spec.js

A small merge issue I detected.
@mdamour1976 please review.

[CLEANUP] - Fix small merge issue - Future develop is already using jasmine 2.0.

---

package-res/resources/web/dojo/pentaho/common/propertiesPanel/Panel.js
package-res/resources/web/vizapi/Events.js
package-res/resources/web/vizapi/VizController.js
package-res/resources/web/vizapi/ccc/ccc_wrapper.js

Reverts pentaho/pentaho-platform-plugin-common-ui#387

Revert "Analyzer 3058 5.3.0.4"

---

package-res/resources/web/dojo/pentaho/common/propertiesPanel/Panel.js
package-res/resources/web/vizapi/Events.js
package-res/resources/web/vizapi/VizController.js
package-res/resources/web/vizapi/ccc/ccc_wrapper.js

Reverts pentaho/pentaho-platform-plugin-common-ui#388

Revert "Analyzer 3058 5.3"

---

package-res/resources/web/test/karma/unit/angular-directives/accordionWizardSpec.js
package-res/resources/web/test/karma/unit/angular-directives/dateTimePickerSpec.js
package-res/resources/web/test/karma/unit/angular-directives/folderBrowseSpec.js
package-res/resources/web/test/karma/unit/angular-directives/scheduleSpec.js
package-res/resources/web/test/karma/unit/angular-directives/weeklyRecurrenceSpec.js

@pminutillo please review.
/cc @rfellows @pamval

[CLEANUP][ENGOPS-1132] - Commenting randomly failing unit tests.

---

package-res/resources/web/dojo/pentaho/common/propertiesPanel/Panel.js
package-res/resources/web/vizapi/Events.js
package-res/resources/web/vizapi/VizController.js
package-res/resources/web/vizapi/ccc/ccc_wrapper.js

Reverts pentaho/pentaho-platform-plugin-common-ui#391
@akhayrutdinov @mtseu @pentaho-nbaker  could one of you pull this revert

Revert "Sp 1946"

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/prompting/parameters/ParameterXmlParser.js
package-res/resources/web/util/base64.js

[BACKLOG-4157]
- Update Common-Ui base 64 utils to AMD
[BACKLOG-4057]
- Added the Dojo Number dependency to the PromptPanel

[BACKLOG-4157] & [BACKLOG-4057] Updated AMD dependencies

---

package-res/resources/web/prompting/components/DojoDateTextBoxComponent.js
package-res/resources/web/prompting/components/FlowPromptLayoutComponent.js
package-res/resources/web/test/prompting/components/DojoDateTextBoxComponentSpec.js
package-res/resources/web/test/prompting/components/FlowPromptLayoutComponentSpec.js
package-res/resources/web/test/prompting/components/GarbageCollectorComponentSpec.js
package-res/resources/web/test/prompting/components/HorizontalTableBasedPromptLayoutComponentSpec.js
package-res/resources/web/test/prompting/components/PanelComponentSpec.js
package-res/resources/web/test/prompting/components/ParameterPanelComponentSpec.js
package-res/resources/web/test/prompting/components/PostInitComponentSpec.js

@diogofscmariano @pamval @plagoa @krivera-pentaho @scottyaslan @rfellows please review

[BACKLOG-4062] Unit tests for some prompt components

---

package-res/resources/web/prompting/components/ScopedPentahoButtonComponent.js
package-res/resources/web/test/prompting/components/PromptLayoutComponentSpec.js
package-res/resources/web/test/prompting/components/ScopedPentahoButtonComponentSpec.js
package-res/resources/web/test/prompting/components/ScrollingPromptPanelLayoutComponentSpec.js
package-res/resources/web/test/prompting/components/SubmitPromptComponentSpec.js
package-res/resources/web/test/prompting/components/TableBasedPromptLayoutComponentSpec.js
package-res/resources/web/test/prompting/components/TextAreaComponentSpec.js
package-res/resources/web/test/prompting/components/VerticalTableBasedPromptLayoutComponentSpec.js

@diogofscmariano @pamval @plagoa @krivera-pentaho @scottyaslan @rfellows please review

[BACKLOG-4062] Last part of tests for prompt components

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/prompting/builders/GarbageCollectorBuilder.js
package-res/resources/web/prompting/components/CompositeComponent.js

@diogofscmariano @annapopova1 @scottyaslan @rfellows @plagoa please review. I have more changes that I want to commit tomorrow, but here are some to start.

[BACKLOG-4137] -- addressed TODOs throughout code

---

package-res/resources/web/prompting/PromptPanel.js

[BACKLOG-4138] - Reviewed PromptPanel module making not used methods private. Small refactor to WidgetBuilder usage and components construction cycle

[BACKLOG-4063] - Included documentation for PromptPanel methods

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/prompting/components/CompositeComponent.js

- Reviewed the CompositeComponent usage for component iteration.
- Moved these functions to the PromptPanel as private functions and removed unneeded params and return values
- Updated names of variables in the PromptPanel component iterations

[BACKLOG-4137]

---

package-res/resources/web/prompting/PromptPanel.js

@scottyaslan @annapopova1 @diogofscmariano @plagoa @rfellows please review

[BACKLOG-4137] -- Removed block of code which is not in use

---

package-res/resources/web/prompting/parameters/Parameter.js
package-res/resources/web/prompting/parameters/ParameterDefinition.js
package-res/resources/web/prompting/parameters/ParameterGroup.js
package-res/resources/web/prompting/parameters/ParameterValue.js
package-res/resources/web/prompting/parameters/ParameterXmlParser.js

- Added documentation for Parameter package
- Added license headers
[BACKLOG-4138]
- Removed unneeded method from Parameter
- Removed unneeded dependency Base from files

[BACKLOG-4139]

---

package-res/resources/web/prompting/PromptPanel.js

@diogofscmariano @pamval @plagoa @krivera-pentaho @scottyaslan @rfellows please review

[BACKLOG-4271] Fix error label position

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/prompting/WidgetBuilder.js
package-res/resources/web/prompting/builders/ParameterGroupPanelBuilder.js
package-res/resources/web/prompting/builders/ParameterWidgetBuilderBase.js
package-res/resources/web/prompting/builders/ValueBasedParameterWidgetBuilder.js
package-res/resources/web/prompting/components/CompositeComponent.js
package-res/resources/web/prompting/parameters/Parameter.js
package-res/resources/web/prompting/parameters/ParameterDefinition.js
package-res/resources/web/prompting/parameters/ParameterGroup.js
package-res/resources/web/prompting/parameters/ParameterValue.js
package-res/resources/web/prompting/parameters/ParameterXmlParser.js

- Added documentation in jsdocs for all the main modules.
- Components: only the CompositeComponent is documented. Others need to be included
- Builders: Only the WidgetBuilder and the Base Builder are included
[BACKLOG-4139]
- Added documentation for methods in the documented modules

[BACKLOG-4063]

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/prompting/parameters/ParameterDefinition.js

@diogofscmariano please review

[CLEANUP] Fix comments

---

package-res/resources/web/prompting/components/ScopedPentahoButtonComponent.js
package-res/resources/web/test/prompting/components/ScopedPentahoButtonComponentSpec.js

@diogofscmariano @pamval @plagoa @krivera-pentaho @scottyaslan @rfellows please review

[BACKLOG-4280] Fix style for View Report button

---

config/karma.ci.conf.js
config/karma.conf.js

* Excluded some more unused files from the karma configs
@plagoa please review

[CLEANUP] Karma launcher. Too many test files starts giving file not found errors

---

package-res/resources/themes/css/angular-animations.css
package-res/resources/web/plugin-handler/animatedAngularPlugin.js
package-res/resources/web/plugin-handler/animatedAngularPluginHandler.js

Please review @pminutillo @kurtwalker @bytekast @krivera-pentaho and merge thx!

[BACKLOG-4270] notification slide down transition

---

package-res/resources/web/plugin-handler/animatedAngularPluginHandler.js

@krivera-pentaho please review and merge

[BACKLOG-4270] added allow animation on the root scope

---

package-res/resources/web/prompting/PromptPanel.js

- Fixed typo introduced in PromptPanel refactor
- Fixed report add to dashboard. It was broken due to implicit global variable in PromptPanel initialization

[BACKLOG-4074&BACKLOG-4491]

---

package-res/resources/web/plugin-handler/animatedAngularPluginHandler.js
package-res/resources/web/test/karma/unit/animatedAngularPluginHandlerSpec.js
package-res/resources/web/test/karma/unit/animatedAngularPluginSpec.js

@pminutillo @bytekast @kurtwalker please review and merge thx.

[BACKLOG-3836] added tests for new angular animations

---

package-res/resources/web/prompting/builders/TextInputBuilder.js

- Included Dev documentation in the TextInputBuilder

[BACKLOG-4045] - Review Component - Text Field

---

package-res/resources/web/prompting/builders/CheckBuilder.js
package-res/resources/web/prompting/builders/RadioBuilder.js

@plagoa @diogofscmariano @rfellows @krivera-pentaho @scottyaslan @pamval please review

[BACKLOG-4042] JS doc for RadioBuilder and CheckBuilder

---

package-res/resources/web/prompting/builders/MultiButtonBuilder.js

- Included Dev documentation in the MultiButtonBuilder

[BACKLOG-4046] - Review Component - MultiButton

---

package-res/resources/web/prompting/builders/ListBuilder.js
package-res/resources/web/prompting/builders/ParameterWidgetBuilderBase.js
package-res/resources/web/prompting/builders/ValueBasedParameterWidgetBuilder.js

- Included Dev documentation in the ListBuilder

[BACKLOG-4040] - Review Component - List

---

build.properties
ivy.xml

- also moved all spring revisions to build.properties

spring.framework upgraded to 3.2.14.RELEASE

---

package-res/resources/web/prompting/builders/DropDownBuilder.js

[BACKLOG-4041] - Dev doc for Dropdown Builder

[BACKLOG-4041] - Dev doc for Dropdown Builder

---

package-res/resources/web/prompting/builders/SubmitComponentBuilder.js
package-res/resources/web/prompting/builders/SubmitPanelBuilder.js
package-res/resources/web/prompting/components/FlowPromptLayoutComponent.js
package-res/resources/web/prompting/components/ScopedPentahoButtonComponent.js
package-res/resources/web/prompting/components/SubmitPromptComponent.js

@plagoa @diogofscmariano @rfellows @krivera-pentaho @scottyaslan @pamval please review

[BACKLOG-4031] JS doc for submit components

---

package-res/resources/web/prompting/builders/TextAreaBuilder.js

- Changed the TextAreaBuilder to use the CDF TextAreaInputComponent instead of the Common-Ui TextAreaComponent
- Included Dev documentation in the TextAreaBuilder

[BACKLOG-4032] - Review Component - TextArea

---

package-res/resources/web/prompting/builders/TextAreaBuilder.js
package-res/resources/web/test/prompting/builders/TextAreaBuilderSpec.js

- Added keypress and focusout events code to the TextAreaBuilder;
- Corrected unit tests to the new builder code;
- Minor code corrections;

[[BACKLOG-4032] - Review Component - TextArea

---

package-res/resources/web/test/prompting/builders/TextInputBuilderSpec.js

- Reviewed the unit tests for the new functionality in the TextInputBuilder and increased the code coverage

[BACKLOG-4045, TEST] - Review Component - Text Field

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/util/util.js

[BACKLOG-4035] - Removing underscore dependency to resolve the build

---

package-res/resources/web/prompting/components/DojoDateTextBoxComponent.js
package-res/resources/web/test/prompting/components/DojoDateTextBoxComponentSpec.js

- Allow default null or empty specified value;
- Allow change of date formats in the date component;
- Some code refactoring;

[BACKLOG-4030] - Review Component - Date Picker

---

build.properties
ivy.xml

with those maintained by the build team.
@lucboudreau

[CLEANUP] making version properties consistent

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/prompting/builders/StaticAutocompleteBoxBuilder.js
package-res/resources/web/prompting/builders/SubmitComponentBuilder.js
package-res/resources/web/prompting/builders/SubmitPanelBuilder.js
package-res/resources/web/prompting/builders/TextAreaBuilder.js
package-res/resources/web/prompting/builders/TextInputBuilder.js
package-res/resources/web/prompting/builders/ValueBasedParameterWidgetBuilder.js
package-res/resources/web/prompting/components/DojoDateTextBoxComponent.js
package-res/resources/web/prompting/components/ExternalInputComponent.js
package-res/resources/web/prompting/components/FlowPromptLayoutComponent.js
package-res/resources/web/prompting/components/ScopedPentahoButtonComponent.js
package-res/resources/web/prompting/components/SubmitPromptComponent.js
package-res/resources/web/prompting/parameters/ParameterDefinition.js

@plagoa @diogofscmariano @rfellows @krivera-pentaho @scottyaslan @pamval please review

[BACKLOG-4661] Fix literal errors from js doc

---

package-res/resources/web/test/prompting/PromptPanelSpec.js

@diogofscmariano please review

[BACKLOG-4916] Unit tests for check initialize hidden parameters

---

package-res/resources/web/prompting/components/DojoDateTextBoxComponent.js
package-res/resources/web/test/prompting/components/DojoDateTextBoxComponentSpec.js

- Fixed date start and date end configuration for date picker component
- Unit tests updated
@plagoa @pamval @annapopova1 @krivera-pentaho @scottyaslan @rfellows please review

[BACKLOG-5011]

---

package-res/resources/web/prompting/components/DojoDateTextBoxComponent.js
package-res/resources/web/test/prompting/components/DojoDateTextBoxComponentSpec.js

- Fixed issue with editing date picker due to missing property about the digit id
- Reviewed date format handing due to double conversions and non-conversions of some legacy formats
- Handled special case for y and yy in dojo due to automatic conversions to yyyy
- Updated unit tests accordingly
@annapopova1 @plagoa @pamval @krivera-pentaho @scottyaslan please review

[BACKLOG-5059]

---

package-res/plugin.xml
package-res/resources/web/vizapi/ccc/sample/sampleVisualization.js
package-res/resources/web/vizapi/ccc/sample/sampleVisualization_analyzer_plugin.js

* Fixing the sample_calc paths in plugin.xml.
* Giving a little love to the sample itself.
@pamval please review.

[BACKLOG-4144] - Full VizAPI/Analyzer Support for 3rd-party, Legacy Visualizations

---

package-res/resources/web/test/prompting/PromptPanelSpec.js

@diogofscmariano please review

[TEST] - Fixed unit tests

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/test/prompting/PromptPanelSpec.js

Cherry pick to 6.0
@diogofscmariano @pamval @dkincade please review

[BACKLOG-5307] - PIR: Error message "This prompt is mandatory" appears for prompt with selected value

---

package-res/resources/web/dojo/pentaho/common/propertiesPanel/Configuration.js
package-res/resources/web/dojo/pentaho/common/propertiesPanel/Panel.js

@krivera-pentaho please review.
/cc @pamval

[ANALYZER-3058][ANALYZER-3164] Restore removed code used by Analyzer API

---

src/org/pentaho/common/ui/metadata/model/impl/ModelInfoComparator.java
src/org/pentaho/common/ui/metadata/service/MetadataService.java
src/org/pentaho/common/ui/metadata/service/MetadataService2.java
src/org/pentaho/common/ui/metadata/service/MetadataServiceUtil.java
src/org/pentaho/common/ui/metadata/service/MetadataServiceUtil2.java
src/org/pentaho/common/ui/models/TreeBrowserModelUtils.java
src/org/pentaho/common/ui/services/ChartSeriesColorContentGenerator.java
src/org/pentaho/common/ui/services/SolutionRepoService.java
src/org/pentaho/common/ui/services/SolutionUrlContentGenerator.java
test-res/pentaho-solutions/system/common-ui/resources/help/messages.properties
test-src/org/pentaho/common/ui/metadata/model/impl/ConditionTest.java
test-src/org/pentaho/common/ui/metadata/service/MetadataService2Test.java
test-src/org/pentaho/common/ui/metadata/service/MetadataServiceIT.java
test-src/org/pentaho/common/ui/metadata/service/MetadataServiceTest.java
test-src/org/pentaho/common/ui/metadata/service/MetadataServiceUtil2Test.java
test-src/org/pentaho/common/ui/metadata/service/MetadataServiceUtilTest.java
test-src/org/pentaho/common/ui/metadata/service/SolutionRepoServiceTest.java
test-src/org/pentaho/common/ui/metadata/service/TestModelProvider.java
test-src/org/pentaho/common/ui/models/TreeBrowserMapperTest.java
test-src/org/pentaho/common/ui/models/TreeBrowserModelUtilsTest.java
test-src/org/pentaho/common/ui/services/ChartSeriesColorContentGeneratorIT.java
test-src/org/pentaho/common/ui/services/ChartSeriesColorContentGeneratorTest.java
test-src/org/pentaho/common/ui/services/JsonUtilTest.java
test-src/org/pentaho/common/ui/services/LocalizationServiceIT.java
test-src/org/pentaho/common/ui/services/SolutionUrlContentGeneratorIT.java
test-src/org/pentaho/common/ui/services/SolutionUrlContentGeneratorTest.java
test-src/org/pentaho/common/ui/services/UserSettingServiceIT.java

1. Fixed checkstyle issues.
2. Increased coverage, as a result now:
Unit tests coverage = 72.1%
Integration tests coverage = 74.4%
Overall coverage = 92.7%
@rfellows @krivera-pentaho @diogofscmariano @pamval please review or find someone who can review this.

[TEST] Increase unit test coverage

---

package-res/resources/web/dojo/dijit/themes/pentaho/layout/LayoutPanel.css

- crop long names
@rfellows, @bennychow, @krivera-pentaho, review it please

[ANALYZER-2893] - Long measure names are not rendered correctly on Analyzer Layout pane

---

package-res/resources/web/prompting/builders/FormattedParameterWidgetBuilderBase.js

[BACKLOG-5873] DEV: Clean jsDoc in common-ui/prompting/builders/FormattedParameterWidgetBuilderBase

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/test/prompting/api/EventAPISpec.js

- removed the two empty functions from the PromptPanel module;
- fixed Prompting tests that were failing occasionally;

[BACKLOG-5872, TEST] - DEV: Clean code in common-ui/prompting/PromptPanel

---

config/karma.ci.conf.js
package-res/resources/web/prompting/builders/TextInputBuilder.js
package-res/resources/web/prompting/sample.html
package-res/resources/web/test/util/TextFormatterSpec.js
package-res/resources/web/util/TextFormatter.js
package-res/resources/web/util/formatting.js

@diogofscmariano @krivera-pentaho @plagoa please review

[BACKLOG-5868] - [BACKLOG-5871] Created the module with formatters based on dojo + unit tests + replcaed global formatter + fixed sample.html

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/prompting/api/OperationAPI.js
package-res/resources/web/prompting/api/UiAPI.js
package-res/resources/web/test/prompting/PromptPanelSpec.js
package-res/resources/web/test/prompting/api/OperationAPISpec.js
package-res/resources/web/test/prompting/api/UiAPISpec.js

Sample framework: https://github.com/pentaho/pentaho-platform-ee/pull/860
@diogofscmariano @plagoa @krivera-pentaho @pamval  @afrjorge  please review

[BACKLOG-5838] Prompt API - Implemented showProgressIndicator

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/test/prompting/PromptPanelSpec.js

@pamval, @diogofscmariano, @krivera-pentaho, review it please. This is a replacement of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/546
@MikhailHubanau is absent until the middle of Jan, that is why I picked his changes and added tests as well as some small changes.

[BISERVER-12918] - the report parameter/prompt panel flashes when auto submit off

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/test/prompting/PromptPanelSpec.js

Backport of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/533
@pamval 
Please review.

SP-2348 - Backport of BISERVER-12961 - Setting drop-down parameter causes text box to revert to default values (6.0 Suite)

---

package-res/resources/web/prompting/PromptPanel.js

Before this fix sample framework case has duplicated documentation for this function.
@krivera-pentaho @pamval @diogofscmariano @plagoa @afrjorge @jvelasques please review

[CLEANUP] fixed documentation for PromptPanel#setBlockUiOptions

---

package-res/resources/web/prompting/api/OperationAPI.js
package-res/resources/web/prompting/api/UtilAPI.js

@diogofscmariano @pamval @krivera-pentaho @plagoa @jvelasques please review.

[BACKLOG-6130] Updated description based on DOC review

---

package-res/resources/web/prompting/api/OperationAPI.js

@diogofscmariano @pamval please review

[BACKLOG-6063] Fixed documentation after doc review for refreshPrompt

---

package-res/resources/web/test/dataapi/models-mqlSpec.js
package-res/resources/web/test/dataapi/models-svcSpec.js

- remove failing tests (they need changes from 96467f7b6557dfd6207c4f026de1cdc0350c5380)
@pamval, review it please

[SP-2383] - Backport of PPP-3455 - Dynamic code injection vulnerabilities found (6.0 Suite)

---

package-res/resources/web/pentaho/type/Item.Meta.js
package-res/resources/web/pentaho/type/Item.js
package-res/resources/web/pentaho/type/Property.js
package-res/resources/web/pentaho/type/complex.js
package-res/resources/web/pentaho/type/i18n/types.properties
package-res/resources/web/pentaho/type/list.js
package-res/resources/web/pentaho/type/value.js
package-res/resources/web/test/karma/unit/pentaho/type/Item.validation.Spec.js
package-res/resources/web/test/karma/unit/pentaho/type/Property.validation.Spec.js
package-res/resources/web/test/karma/unit/pentaho/type/complex.validation.Spec.js
package-res/resources/web/test/karma/unit/pentaho/type/list.validation.Spec.js
package-res/resources/web/test/karma/unit/pentaho/type/value.Spec.js

On behalf of @nantunes (MIA, sick) and with only slight touches from myself, I ask @graimundo and @scottyaslan  to review this. Thanks.

[BACKLOG-6051] - Have validate behavior for foundation classes

---

package-res/resources/web/pentaho/type/boolean.js
package-res/resources/web/pentaho/type/function.js
package-res/resources/web/pentaho/type/object.js
package-res/resources/web/pentaho/type/string.js
package-res/resources/web/test/karma/unit/pentaho/type/boolean.Spec.js
package-res/resources/web/test/karma/unit/pentaho/type/function.Spec.js
package-res/resources/web/test/karma/unit/pentaho/type/object.Spec.js
package-res/resources/web/test/karma/unit/pentaho/type/string.Spec.js

[BACKLOG-6049] boolean, function, object, and string specs

---

config/require-config.js
package-res/resources/web/test/karma/unit/angular-directives/accordionWizardSpec.js
package-res/resources/web/test/karma/unit/angular-directives/dateTimePickerSpec.js
package-res/resources/web/test/karma/unit/angular-directives/folderBrowseSpec.js
package-res/resources/web/test/karma/unit/angular-directives/scheduleSpec.js
package-res/resources/web/test/karma/unit/angular-directives/weeklyRecurrenceSpec.js
package-res/resources/web/test/require-config.js

@dcleao @lucboudreau @pentaho-nbaker

[BACKLOG-6407] remove angular-mocks test dependencies

---

package-res/resources/web/pentaho/type/value.js
package-res/resources/web/pentaho/type/valueHelper.js
package-res/resources/web/test/karma/unit/pentaho/type/value.Spec.js
package-res/resources/web/test/karma/unit/pentaho/type/valueHelper.Spec.js

- Complemented Value unit tests

[BACKLOG-6049] - Added tests for valueHelper

---

package-res/resources/web/pentaho/type/Property.js
package-res/resources/web/test/karma/unit/pentaho/type/refinement.Spec.js

@dcleao please review. Needed for sandbox's calc demo.

[BACKLOG-6051] Allow overriding a property with a refinement

---

package-res/resources/web/vizapi/ccc/ccc_wrapper.js

[ANALYZER-2209] skipped exponent limit

---

package-res/resources/web/pentaho/type/i18n/types.properties
package-res/resources/web/pentaho/type/simple.js
package-res/resources/web/test/karma/unit/pentaho/type/simple.Spec.js

@dcleao @graimundo please review

[BACKLOG-6049] Create missing unit tests and update documentation for simple.js

---

package-res/resources/web/pentaho/type/simple.js
package-res/resources/web/test/karma/unit/pentaho/type/simple.Spec.js

@dcleao @graimundo please review

[BACKLOG-6049] Implemented reviews done in previous PR

---

package-res/resources/web/pentaho/type/i18n/types.properties

@graimundo As talked with Katelyn.

[BACKLOG-6051] Correct countOutOfRange error message

---

package-res/resources/web/pentaho/type/list.js
package-res/resources/web/test/karma/unit/pentaho/type/list.Spec.js

[BACKLOG-6051] First element of list was never removed when using list.set()

---

package-res/resources/web/pentaho/type/PropertyMetaCollection.js
package-res/resources/web/test/karma/unit/pentaho/type/PropertyMetaCollection.Spec.js

@dcleao @scottyaslan please review

[BACKLOG-6049] Added unit tests to PropertyMetaCollection.

---

package-res/resources/web/test/karma/unit/pentaho/type/PropertyMetaCollection.Spec.js

Trying to archive the 100% coverage I noticed that there were no tests in use cases where some properties are inherited.
@dcleao @scottyaslan @carlosrusso @graimundo please review.

[BACKLOG-6049] Additional tests to PropertyMetaCollection

---

package-res/resources/web/dataapi/models-svc.js
package-res/resources/web/dojo/pentaho/common/overrides/dojox/json/ref.js

- replace `eval()` with `JSON.parse()` in models-svc.js, ref.js
@rfellows, @krivera-pentaho, @diogofscmariano, review it please

[PPP-3455] - Dynamic code injection vulnerabilities found

---

test-js/unit/pentaho/util/MessageBundle.Spec.js

Didn't do a proper validation in this function, and was making the unit tests fail.
@graimundo please review

[BACKLOG-6287] fixed auxiliary function used in the unit tests

---

test-js/unit/pentaho/util/MessageBundle.Spec.js

[BACKLOG-6249] Format now throws and error when no text is given

---

package-res/resources/web/pentaho/type/Context.js
package-res/resources/web/pentaho/type/Item.Meta.js
package-res/resources/web/pentaho/util/promise.js
package-res/resources/web/pentaho/visual/Wrapper.js
package-res/resources/web/pentaho/visual/type/helper.js
test-js/unit/pentaho/type/Context.Spec.js
test-js/unit/pentaho/util/promise.Spec.js

[BACKLOG-6293] DEV: Create unit tests and documentation for pentaho/util/promise.js

---

package-res/resources/web/pentaho/lang/Base.js
test-js/unit/pentaho/lang/Base.Spec.js

For review. @pentaho/millenniumfalcon

[BACKLOG-6284] Base.js - Unit testing and dev API reference documentation

---

package-res/resources/web/pentaho/lang/Base.js
test-js/unit/pentaho/lang/Base.Spec.js

[BACKLOG-6284] Base.js - Bug fixes

---

package-res/resources/web/pentaho/util/arg.js
test-js/unit/pentaho/util/arg.Spec.js

[BACKLOG-6288] arg spec and doc

---

package-res/resources/web/pentaho/type/Item.Meta.js
package-res/resources/web/pentaho/type/list.js
package-res/resources/web/pentaho/util/fun.js
test-js/unit/pentaho/util/MessageBundle.Spec.js
test-js/unit/pentaho/util/fun.Spec.js

[BACKLOG-6290] Create unit tests and documentation for /pentaho/util/fun.js

---

test-js/unit/pentaho/util/object.Spec.js

* Removed test due to inconsistent JS engine behavior.
@graimundo please review.

[BACKLOG-6291] pentaho/util/object.js

---

test-js/unit/pentaho/lang/Event.Spec.js

* Fixing Event.Spec.js unit tests

[BACKLOG-5984] Define the event model in a visualization

---

test-js/unit/pentaho/lang/Event.Spec.js
test-js/unit/pentaho/lang/EventSource.Spec.js
test-js/unit/pentaho/type/Context.Spec.js
test-js/unit/pentaho/type/Property.Meta.Spec.js
test-js/unit/pentaho/type/complex.Spec.js
test-js/unit/pentaho/type/facets/DiscreteDomain.Spec.js
test-js/unit/pentaho/type/facets/Refinement.Spec.js
test-js/unit/pentaho/type/list.Spec.js
test-js/unit/pentaho/type/refinement.Spec.js
test-js/unit/pentaho/type/value.refine.Spec.js
test-js/unit/pentaho/util/MessageBundle.Spec.js
test-js/unit/pentaho/util/arg.Spec.js
test-js/unit/pentaho/util/promise.Spec.js
test-js/unit/pentaho/visual/base/View.Spec.js
test-js/unit/pentaho/visual/data/_plain/TableSpec.js

[CLEANUP] Change pentaho/ unit tests to use errorMatch utility

---

package-res/resources/web/pentaho/type/Context.js
test-js/unit/pentaho/type/Context.Spec.js

This PR is based on the commit of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/638, so please only merge after the latter.

[CLEANUP] Change Context#getAsync to not throw errors synchronously, but to instead return a rejected promise.

---

package-res/resources/web/pentaho/type/Context.js
package-res/resources/web/pentaho/type/complex.js
package-res/resources/web/pentaho/type/facets/DiscreteDomain.js
package-res/resources/web/pentaho/type/list.js
package-res/resources/web/pentaho/type/refinement.js
package-res/resources/web/pentaho/type/value.js
package-res/resources/web/pentaho/visual/base/View.js
test-js/unit/pentaho/type/Context.Spec.js
test-js/unit/pentaho/type/complex.Spec.js
test-js/unit/pentaho/type/list.Spec.js
test-js/unit/pentaho/type/value.refine.Spec.js

This PR is based on the commit of #641, so please only merge after the latter.

[CLEANUP] Document thrown errors using the JsDocs @throws tag

---

test-js/unit/pentaho/i18nMock.js

[FIX][BACKLOG-6625] Normalize resourceIDs in i18nMock plugin

---

config/karma.ci.conf.js
config/karma.conf.js
config/nodojo.karma.conf.js
package-res/resources/web/common-ui-require-js-cfg.js
package-res/resources/web/pentaho/visual/2.5/Wrapper.js
package-res/resources/web/pentaho/visual/2.5/editor/utils.js
package-res/resources/web/pentaho/visual/2.5/spec/helper.js
package-res/resources/web/pentaho/visual/2.5/type/helper.js
package-res/resources/web/pentaho/visual/2.5/type/registry.js
test-js/unit/require-config.js

[BACKLOG-5807] Fix Analyzer breaking, due to missing VizAPI 2.5

---

package-res/resources/web/pentaho/visual/color/paletteRegistry.js
package-res/resources/web/pentaho/visual/color/utils.js

[BACKLOG-5807] Revert color palettes' codes as Analyzer still depends on this.

---

package-res/resources/web/pentaho/i18n.js

Following #655, applies the same fix on the i18n plugin.
@dcleao please review.

[FIX] Normalize resourceIDs in i18n plugin

---

package-res/resources/web/common-ui-require-js-cfg.js
package-res/resources/web/pentaho/visual/ccc/bar/model.js
package-res/resources/web/pentaho/visual/ccc/bar/themes/det/images/icon-sprite.svg
package-res/resources/web/pentaho/visual/ccc/bar/themes/det/model.css
package-res/resources/web/pentaho/visual/ccc/bar/themes/det/model.js
package-res/resources/web/pentaho/visual/ccc/barHorizontal/model.js
package-res/resources/web/pentaho/visual/ccc/barHorizontal/themes/det/images/icon-sprite.svg
package-res/resources/web/pentaho/visual/ccc/barHorizontal/themes/det/model.css
package-res/resources/web/pentaho/visual/ccc/barHorizontal/themes/det/model.js
package-res/resources/web/pentaho/visual/ccc/barNormalized/model.js
package-res/resources/web/pentaho/visual/ccc/barNormalized/themes/det/images/icon-sprite.svg
package-res/resources/web/pentaho/visual/ccc/barNormalized/themes/det/model.css
package-res/resources/web/pentaho/visual/ccc/barNormalized/themes/det/model.js
package-res/resources/web/pentaho/visual/ccc/barNormalizedHorizontal/model.js
package-res/resources/web/pentaho/visual/ccc/barNormalizedHorizontal/themes/det/images/icon-sprite.svg
package-res/resources/web/pentaho/visual/ccc/barNormalizedHorizontal/themes/det/model.css
package-res/resources/web/pentaho/visual/ccc/barNormalizedHorizontal/themes/det/model.js
package-res/resources/web/pentaho/visual/ccc/barStacked/model.js
package-res/resources/web/pentaho/visual/ccc/barStacked/themes/det/images/icon-sprite.svg
package-res/resources/web/pentaho/visual/ccc/barStacked/themes/det/model.css
package-res/resources/web/pentaho/visual/ccc/barStacked/themes/det/model.js
package-res/resources/web/pentaho/visual/ccc/barStackedHorizontal/model.js
package-res/resources/web/pentaho/visual/ccc/barStackedHorizontal/themes/det/images/icon-sprite.svg
package-res/resources/web/pentaho/visual/ccc/barStackedHorizontal/themes/det/model.css
package-res/resources/web/pentaho/visual/ccc/barStackedHorizontal/themes/det/model.js

Merge after PR #653. See diff of commit 65afee5.

[BACKLOG-6615] Barchart family icons (det theme)

---

package-res/resources/web/pentaho/visual/ccc/abstract/View.js

[BACKLOG-6625] Fix ccc/abstract/View options changing base options

---

config/nodojo.karma.conf.js
test-js/unit/pentaho/lang/EventSource.Spec.js
test-js/unit/pentaho/lang/EventSource.dojo.Spec.js

[CLEANUP] Testing that EventSource is really compatible with dojo/on.

---

.gitignore
config/karma.ci.conf.js
package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/prompting/api/EventAPI.js
test-js/unit/prompting/PromptPanelSpec.js

The submit callback has not 'promptPanel' argument.
@pentaho/orlandocalisbon please review

[BACKLOG-6882] Fixed prompt EventAPI#submit

---

config/karma.ci.conf.js

@pentaho/orlandocalisbon please review

[BACKLOG-6882] Reverted js test report path

---

package-res/resources/web/pentaho/type/Instance.js
package-res/resources/web/pentaho/type/SpecificationScope.js
package-res/resources/web/pentaho/type/Type.js
package-res/resources/web/pentaho/type/_doc/spec/IComplex.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/IDate.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/IFunction.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/IInstance.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/IList.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/IPropertyType.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/ISimple.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/IType.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/UComplex.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/UInstance.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/UList.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/UPropertyType.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/USimple.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/UTypeReference.jsdoc
package-res/resources/web/pentaho/type/complex.js
package-res/resources/web/pentaho/type/date.js
package-res/resources/web/pentaho/type/function.js
package-res/resources/web/pentaho/type/list.js
package-res/resources/web/pentaho/type/simple.js
package-res/resources/web/pentaho/type/value.js
test-js/unit/pentaho/type/Instance.serialization.Spec.js
test-js/unit/pentaho/type/complex.serialization.Spec.js
test-js/unit/pentaho/type/list.serialization.Spec.js
test-js/unit/pentaho/type/simple.serialization.Spec.js

This PR is a joint effort of @scottyaslan, @dcleao and @nantunes. During preparation of the PR and commit history, I had to squash changes made by @scottyaslan, changing their authorship.

[BACKLOG-6535] Instance#toSpec

---

package-res/resources/web/pentaho/lang/Base.js
package-res/resources/web/pentaho/type/Context.js
package-res/resources/web/pentaho/type/Instance.js
package-res/resources/web/pentaho/type/Property.js
package-res/resources/web/pentaho/type/Type.js
package-res/resources/web/pentaho/type/refinement.js
package-res/resources/web/pentaho/type/simple.js
package-res/resources/web/pentaho/type/value.js
test-js/unit/pentaho/lang/Base.Spec.js
test-js/unit/pentaho/type/Context.Spec.js
test-js/unit/pentaho/type/Property.Type.Spec.js
test-js/unit/pentaho/type/PropertyTypeCollection.Spec.js
test-js/unit/pentaho/type/Type.Spec.js
test-js/unit/pentaho/type/simple.Spec.js

[CLEANUP] Multiple cleanup issues done in the context of BACKLOG 6052 (II)

---

package-res/resources/web/pentaho/visual/ccc/abstract/ViewDemo.js

[BACKLOG-6052] Changed event listeners to better handle key press and a flag to ignore the confirmation window

---

package-res/resources/web/pentaho/service.js
test-js/unit/pentaho/serviceSpec.js

[BACKLOG-6733] Extends pentaho/service plugin to provide the moduleId

---

test-js/unit/prompting/WidgetBuilderSpec.js

[CLEANUP] - removed wrong fdescribe disabling all tests

---

package-res/resources/web/pentaho/util/logger.js

[BACKLOG-6739][CLEANUP] Fix JsDocs failure.

---

package-res/resources/web/pentaho/service.js
test-js/unit/pentaho/serviceSpec.js

[BACKLOG-6733] Extends pentaho/service plugin to ask for single result

---

package-res/resources/web/common-ui-require-js-cfg.js
package-res/resources/web/pentaho/type/Context.js
package-res/resources/web/pentaho/type/config/AmdLoadedConfigurationService.js
package-res/resources/web/pentaho/type/config/ConfigurationService.js
package-res/resources/web/pentaho/type/configurationService.js
test-js/unit/pentaho/type/config/AmdLoadedConfigurationService.Spec.js
test-js/unit/pentaho/type/config/ConfigurationService.Spec.js
test-js/unit/pentaho/type/configurationService.Spec.js

[BACKLOG-6733] Initial implementation of the configuration service

---

package-res/resources/web/pentaho/lang/SortedList.js
test-js/unit/pentaho/lang/SortedList.Spec.js

[BACKLOG-6733] pentaho/lang/SortedList

---

package-res/resources/web/dojo/pentaho/common/FormatCombo.js
test-js/unit/dojo/pentaho/common/FormatComboSpec.js

Sync with master

---

package-res/resources/web/prompting/builders/FormattedParameterWidgetBuilderBase.js
package-res/resources/web/prompting/builders/StaticAutocompleteBoxBuilder.js
package-res/resources/web/prompting/components/DojoDateTextBoxComponent.js
package-res/resources/web/prompting/components/StaticAutocompleteBoxComponent.js
package-res/resources/web/util/formatting.js

@pentaho/orlandocalisbon please review

[BACKLOG-6875] PIR: Review paramDefn usage

---

package-res/resources/web/pentaho/type/Context.js
package-res/resources/web/pentaho/type/_doc/IConfigurationService.jsdoc
package-res/resources/web/pentaho/type/_doc/_namespace.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/ITypeConfiguration.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/ITypeConfigurationRuleSelection.jsdoc
package-res/resources/web/pentaho/type/config/AmdLoadedConfigurationService.js
package-res/resources/web/pentaho/type/config/ConfigurationService.js
package-res/resources/web/pentaho/type/config/_doc/_namespace.jsdoc
package-res/resources/web/pentaho/type/configurationService.js
package-res/resources/web/pentaho/type/value.js
test-js/unit/pentaho/type/config/AmdLoadedConfigurationService.Spec.js
test-js/unit/pentaho/type/config/ConfigurationService.Spec.js

Depends on #734.
@pentaho/millenniumfalcon please take a look.

[BACKLOG-6733] ConfigurationService: add and select config

---

test-js/unit/pentaho/type/Context.Spec.js

@pentaho/millenniumfalcon increasing test coverage.

[BACKLOG-6733][CLEANUP] Unit testing Context#vars

---

package-res/resources/web/pentaho/_doc/UJsonValue.jsdoc
package-res/resources/web/pentaho/type/Instance.js
package-res/resources/web/pentaho/type/Type.js
package-res/resources/web/pentaho/type/date.js
package-res/resources/web/pentaho/type/function.js
package-res/resources/web/pentaho/type/simple.js
package-res/resources/web/pentaho/type/value.js
test-js/unit/pentaho/type/Instance.serialization.Spec.js
test-js/unit/pentaho/type/Property.Type.serialization.Spec.js
test-js/unit/pentaho/type/Type.serialization.Spec.js
test-js/unit/pentaho/type/date.Spec.js
test-js/unit/pentaho/type/function.Spec.js
test-js/unit/pentaho/type/serializationUtil.js
test-js/unit/pentaho/type/simple.Type.serialization.Spec.js
test-js/unit/pentaho/type/simple.serialization.Spec.js
test-js/unit/pentaho/type/value.Type.serialization.Spec.js

NOTE: Documentation will be reviewed along with all the remaining metadata docs.

[BACKLOG-7614] Serialize a visualization to JSON

---

package-res/resources/web/pentaho/type/complex.js
package-res/resources/web/pentaho/type/function.js
package-res/resources/web/pentaho/type/i18n/types.properties
package-res/resources/web/pentaho/type/simple.js
test-js/unit/pentaho/type/complex.serialization.Spec.js
test-js/unit/pentaho/type/function.Spec.js
test-js/unit/pentaho/type/simple.serialization.Spec.js

[BACKLOG-7614] Prevent function properties with native functions from being serialized.

---

package-res/resources/web/pentaho/type/_doc/spec/IFunction.jsdoc

[BACKLOG-7614] Added docs on native functions not being serialized.

---

package-res/resources/web/common-ui-require-js-cfg.js
package-res/resources/web/pentaho/i18n.js
package-res/resources/web/pentaho/service.js
package-res/resources/web/pentaho/type/Context.js
package-res/resources/web/pentaho/type/refinement.js
package-res/resources/web/pentaho/visual/2.5/samples/calc/analyzer_plugin_loader.js
package-res/resources/web/pentaho/visual/ccc/2.5/analyzer_plugin_loader.js
package-res/resources/web/pentaho/visual/ccc/2.5/visualTypeProvider.js
package-res/resources/web/pentaho/visual/ccc/areaStacked/model.js
package-res/resources/web/pentaho/visual/ccc/bar/model.js
package-res/resources/web/pentaho/visual/ccc/barHorizontal/model.js
package-res/resources/web/pentaho/visual/ccc/barLine/model.js
package-res/resources/web/pentaho/visual/ccc/barNormalized/model.js
package-res/resources/web/pentaho/visual/ccc/barNormalizedHorizontal/model.js
package-res/resources/web/pentaho/visual/ccc/barStacked/model.js
package-res/resources/web/pentaho/visual/ccc/barStackedHorizontal/model.js
package-res/resources/web/pentaho/visual/ccc/heatGrid/model.js
package-res/resources/web/pentaho/visual/ccc/line/model.js
package-res/resources/web/pentaho/visual/ccc/metricDot/model.js
package-res/resources/web/pentaho/visual/ccc/pie/model.js
package-res/resources/web/pentaho/visual/ccc/sunburst/model.js
test-js/unit/pentaho/service.Spec.js
test-js/unit/pentaho/type/Context.Spec.js

[BACKLOG-8366] Fixed references to modules specific to VizAPI 2.5

---

package-res/resources/web/pentaho/type/changes/Transaction.js

[BACKLOG-7899] - Fix jsdocs comment

---

package-res/resources/web/pentaho/type/ContainerMixin.js
package-res/resources/web/pentaho/type/Context.js
package-res/resources/web/pentaho/type/ReferenceList.js
package-res/resources/web/pentaho/type/SpecificationContext.js
package-res/resources/web/pentaho/type/_doc/Factory.jsdoc
package-res/resources/web/pentaho/type/_doc/IConfigurationService.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/IPropertyTypeProto.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/IRefinementTypeProto.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/ISimple.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/ISimpleTypeProto.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/ITypeConfigurationRuleSelection.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/ITypeProto.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/IValueTypeProto.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/UContextVarFilter.jsdoc
package-res/resources/web/pentaho/type/_doc/spec/UTypeReference.jsdoc
package-res/resources/web/pentaho/type/_type.js
package-res/resources/web/pentaho/type/complex.js
package-res/resources/web/pentaho/type/instance.js
package-res/resources/web/pentaho/type/list.js
package-res/resources/web/pentaho/type/property.js
package-res/resources/web/pentaho/type/refinement.js
package-res/resources/web/pentaho/type/simple.js
package-res/resources/web/pentaho/type/value.js
package-res/resources/web/pentaho/type/valueHelper.js

Integrated and reviewed Joe's language check

[BACKLOG-8687] Final language check to Client Metadata Model core classes

---

.gitignore
package-res/resources/web/pentaho/type/changes/AbstractTransactionScope.js
package-res/resources/web/pentaho/type/changes/ChangeRef.js
package-res/resources/web/pentaho/type/changes/Changeset.js
package-res/resources/web/pentaho/type/changes/CommittedScope.js
package-res/resources/web/pentaho/type/changes/ComplexChangeset.js
package-res/resources/web/pentaho/type/changes/ListChangeset.js
package-res/resources/web/pentaho/type/changes/Transaction.js
package-res/resources/web/pentaho/type/changes/TransactionRejectedError.js
package-res/resources/web/pentaho/type/changes/TransactionScope.js
package-res/resources/web/pentaho/type/config/AmdLoadedConfigurationService.js
package-res/resources/web/pentaho/type/config/ConfigurationService.js
package-res/resources/web/pentaho/type/facets/Refinement.js
package-res/resources/web/pentaho/type/mixins/mixinError.js

Integrated and reviewed Joe's language check. Also added the file `package-pom.xml` to the list of ignored files by github as it is generated by the build process

[CLEANUP][BACKLOG-8409] Final language check to Client Metadata Model non-core classes

---

package-res/resources/web/common-ui-require-js-cfg.js
package-res/resources/web/pentaho/visual/ccc/abstract/View.js
package-res/resources/web/pentaho/visual/ccc/abstract/i18n/model.properties
package-res/resources/web/pentaho/visual/ccc/bubble/View.js
package-res/resources/web/pentaho/visual/ccc/bubble/model.js
package-res/resources/web/pentaho/visual/ccc/donut/View.js
package-res/resources/web/pentaho/visual/ccc/donut/model.js
package-res/resources/web/pentaho/visual/ccc/metricDotAbstract/View.js
package-res/resources/web/pentaho/visual/ccc/metricDotAbstract/model.js
package-res/resources/web/pentaho/visual/ccc/pie/model.js
package-res/resources/web/pentaho/visual/ccc/scatter/View.js
package-res/resources/web/pentaho/visual/ccc/scatter/model.js

[BACKLOG-9052] Configure the Axis defaults for DET charts

---

package-res/resources/web/pentaho/type/complex.js
package-res/resources/web/pentaho/visual/base/View.js
package-res/resources/web/pentaho/visual/base/events/DidCreate.js
package-res/resources/web/pentaho/visual/base/events/DidUpdate.js
package-res/resources/web/pentaho/visual/base/events/RejectedUpdate.js
package-res/resources/web/pentaho/visual/base/events/WillUpdate.js
package-res/resources/web/pentaho/visual/ccc/abstract/View.js
package-res/resources/web/pentaho/visual/samples/calc/View.js
package-res/resources/web/pentaho/visual/samples/sandbox/container.js
test-js/unit/pentaho/visual/base/View.Spec.js
test-js/unit/pentaho/visual/base/events/DidCreate.Spec.js
test-js/unit/pentaho/visual/base/events/DidUpdate.Spec.js
test-js/unit/pentaho/visual/base/events/RejectedUpdate.Spec.js
test-js/unit/pentaho/visual/base/events/WillUpdate.Spec.js
test-js/unit/pentaho/visual/ccc/bar/View.Spec.js

@pentaho/millenniumfalcon ready for final review.

[BACKLOG-8282][BACKLOG-8274] update events and element view managment

---

package-res/resources/web/pentaho/util/object.js
package-res/resources/web/pentaho/visual/base/View.js

[BACKLOG-8276] Docs review.

---

package-res/resources/web/pentaho/visual/ccc/abstract/View.js

* Fixed an issue where CCC-wrapper would process click events for clearing selection
even when selection is explicitly deactivated;
this prevented the tab scroller from receiving click events.
@pentaho/orlandocalisbon please review.

[BACKLOG-9016] Implement the Tabs Scroller Component

---

package-res/resources/web/prompting/PromptPanel.js
package-res/resources/web/prompting/parameters/ParameterDefinitionDiffer.js
test-js/unit/prompting/parameters/ParameterDefinitionDifferSpec.js

- Parameters errors refreshment is fixed.

[BISERVER-13277] PostProcessing Error Validation Message keeps showing on ReportViewer after validation is complete

---

package-res/resources/web/prompting/parameters/ParameterDefinition.js
package-res/resources/web/prompting/parameters/ParameterXmlParser.js

[BACKLOG-8607]-Support for minimized parameter definition

---

test-js/unit/prompting/parameters/ParameterXmlParserSpec.js

Fixes failing test on CI.
@graimundo @annapopova1 @tmorgner @rfellows please review

[BACKLOG-8607]-Test 'minimized' attribute parsed

---

package-res/resources/web/pentaho/visual/ccc/pointAbstract/model.js

[BACKLOG-10514] Fix new CCC Viz base class, PointAbstract not being marked as abstract.

---

package-res/resources/web/dojo/pentaho/common/RowLimitControl.css
package-res/resources/web/dojo/pentaho/common/RowLimitControl.html
package-res/resources/web/dojo/pentaho/common/RowLimitControl.js
package-res/resources/web/dojo/pentaho/common/RowLimitExceededDialog.html
package-res/resources/web/dojo/pentaho/common/RowLimitExceededDialog.js
package-res/resources/web/dojo/pentaho/common/RowLimitMessage.html
package-res/resources/web/dojo/pentaho/common/RowLimitMessage.js
package-res/resources/web/dojo/pentaho/common/nls/messages.properties
test-js/unit/dojo/pentaho/common/RowLimitControlSpec.js
test-js/unit/dojo/pentaho/common/RowLimitExceededDialogSpec.js
test-js/unit/dojo/pentaho/common/RowLimitMessageSpec.js

[BACKLOG-6859]-Row limit UI components

---

package-res/resources/web/pentaho/data/Attribute.js
package-res/resources/web/pentaho/data/Member.js
package-res/resources/web/pentaho/type/util.js
package-res/resources/web/pentaho/visual/ccc/abstract/View.js
package-res/resources/web/pentaho/visual/ccc/metricDotAbstract/model.js
package-res/resources/web/pentaho/visual/ccc/pointAbstract/model.js
package-res/resources/web/pentaho/visual/role/level.js
package-res/resources/web/pentaho/visual/role/mapping.js
package-res/resources/web/pentaho/visual/role/mappingAttribute.js
test-js/unit/pentaho/visual/role/level.Spec.js
test-js/unit/pentaho/visual/role/mapping.Spec.js
test-js/unit/pentaho/visual/role/mappingAttribute.Spec.js

[BACKLOG-11074] DET: Problem in Scatter/Bubble charts when using Date type fields in Dots' Color drop zone

---

package-res/resources/web/dojo/pentaho/common/RowLimitControl.js
package-res/resources/web/dojo/pentaho/common/RowLimitExceededDialog.js
package-res/resources/web/dojo/pentaho/common/RowLimitMessage.js

[BACKLOG-6859]-Apply localization carefully

---

build.properties

- Changed the build.properies to use the springframework
4.3.2.RELEASE

[BACKLOG-10623] Upgraded Springframework

---

package-res/resources/web/pentaho/type/complex.js
package-res/resources/web/pentaho/type/object.js
package-res/resources/web/pentaho/visual/role/level.js
test-js/unit/pentaho/type/complex.Type.Spec.js
test-js/unit/pentaho/type/object.Spec.js

To be merged along with https://github.com/pentaho/pentaho-det/pull/383

[BACKLOG-10707] Reusing visual roles when switching between visualizations

---

package-res/resources/web/util/BootstrappedTabLoader.js

@pentaho/rogueone please review

[BACKLOG-9815] use correct selector syntax

---

package-res/resources/web/pentaho/visual/ccc/abstract/View.js

[BACKLOG-9648] DET: Render chart changes after PlotMinSize is achieved

---

package-res/resources/web/pentaho/visual/base/View.js
test-js/unit/pentaho/visual/base/View.Spec.js

[BACKLOG-9599] - Added View.getAsync for use by DET.

---

package-res/resources/web/pentaho/visual/ccc/abstract/View.js

[BACKLOG-11169] Disable default CCC comparer

---

package-res/themes.xml
src/themes.xml

@mdamour1976 @bmorrise.  Required changes to two different themes.xml

[BACKLOG-11315] - Added fix for default theme of sapphire to common-ui.

---

package-res/resources/web/dojo/pentaho/common/RowLimitControl.js

two more palces to check after te Infinity was removed 
@tmorgner please review

[BACKLOG-11674]-Ignore not positive system limit

---

package-res/resources/web/dojo/pentaho/common/RowLimitControl.js

[BACKLOG-11636]-Row limit not working in Safari

---

package-res/resources/web/prompting/messages/messages_ja.properties

[BACKLOG-11760] - Localization - Fixes from Acclaro.
@tmorgner please review.

[BACKLOG-11760] - Localization - Fixes from Acclaro.

---

package-res/resources/web/pentaho/type/facets/DiscreteDomain.js
package-res/resources/web/pentaho/visual/ccc/abstract/i18n/model.properties
package-res/resources/web/pentaho/visual/ccc/abstract/mixins/scaleColorContinuousType.js
test-js/unit/pentaho/type/facets/DiscreteDomain.Spec.js

This PR provides support for https://github.com/pentaho/pentaho-analyzer/pull/1275

[BACKLOG-8759] Modified some properties of VizAPI 3.0 visualizations to comply with Analyzer 

---

package-res/resources/web/pentaho/visual/ccc/abstract/View.js

[BACKLOG-8367] Removing scroll width hack for visualizations in multi-charts "mode"

---

package-res/resources/web/prompting/parameters/ParameterXmlParser.js

[PPP-3592]-Report parameter vulnerable to XSS

---

package-res/resources/web/dojo/pentaho/common/RowLimitControl.css
package-res/resources/web/dojo/pentaho/common/RowLimitControl.html
package-res/resources/web/dojo/pentaho/common/RowLimitControl.js
package-res/resources/web/dojo/pentaho/common/nls/messages.properties
package-res/resources/web/dojo/pentaho/common/nls/messages_de.properties
package-res/resources/web/dojo/pentaho/common/nls/messages_fr.properties
package-res/resources/web/dojo/pentaho/common/nls/messages_ja.properties

Reverts pentaho/pentaho-platform-plugin-common-ui#902

Revert "Backport of [BACKLOG-11517] - PIR: An unexpected error when putting huge numbers …"

---

package-res/resources/web/dataapi/models-mql.js

characters are Chinese or Japanese.
- replace escape() to encodeURIComponent for encoding request parameters

[PIR-1296]-Interactive Report Filter never loads when the search

---

package-res/resources/web/prompting/parameters/ParameterXmlParser.js

[SP-3084][PPP-3592]-Report parameter vulnerable to XSS

---

package-res/resources/web/prompting/parameters/ParameterXmlParser.js

[SP-3085][PPP-3592]-Report parameter vulnerable to XSS

---

package-res/resources/web/dataapi/models-mql.js

- replace escape() to encodeURIComponent for encoding request parameters

[SP-3168][PIR-1296]-Interactive Report Filter never loads when the search characters are Chinese or Japanese.

---

package-res/resources/web/prompting/PromptPanel.js

Reverts pentaho/pentaho-platform-plugin-common-ui#913

Revert "[PRD-5793] - PRPT reports with auto-submit=false do not display on a …"

---

doc-jsdoc/pentaho/spec/IContextVars.jsdoc
package-res/resources/web/pentaho/CustomContextVars.js
package-res/resources/web/pentaho/_globalContextVars.js
package-res/resources/web/pentaho/i18n.js

See related PRs at: https://github.com/pentaho/pentaho-analyzer/pull/1340.

[BACKLOG-7977] Changes to pentaho/i18n

---

package-res/resources/web/prompting/components/SubmitPromptComponent.js

Prevent lost "onclick" when it is also an "onblur"

[SP-3213][BISERVER-13280]-Support blur and click at the same time

---

package-res/resources/web/prompting/components/SubmitPromptComponent.js

Prevent lost "onclick" when it is also an "onblur"

[SP-3212][BISERVER-13280]-Support blur and click at the same time

---

ivy.xml

- platform-core-test
- platform-repository-test
only merge after https://github.com/pedrofvteixeira/pentaho-platform/tree/BACKLOG-12101 merge

[BACKLOG-12101] Updating test dependencies

---

package-res/resources/web/prompting/PromptPanel.js

The previous aproach didn't worked in 7+ with async mode = false

[PRD-5793]-Don't fail if there is no prompt UI on the page

---

impl/client/src/main/javascript/web/pentaho/visual/samples/sandbox/container.js
impl/client/src/main/javascript/web/pentaho/visual/samples/sandbox/index.html

[BACKLOG-14145] Adapt VizAPI sample sandbox to enable testing embedded scenarios.

---

impl/client/src/main/javascript/web/pentaho/visual/ccc/abstract/i18n/model.properties

Related with this PR https://github.com/pentaho/pentaho-analyzer/pull/1383

[BACKLOG-14317] Changed the v3 visualizations labels with the new ones from analyzer

---

package-res/resources/web/prompting/PromptPanel.js

[SP-3287][PRD-5793]-Don't fail if there is no prompt UI on the page

---

package-res/resources/web/prompting/PromptPanel.js

[SP-3288][PRD-5793]-Don't fail if there is no prompt UI on the page

---

impl/client/src/main/javascript/web/pentaho/context/impl/Context.js
impl/client/src/main/javascript/web/pentaho/util/has.js
impl/client/src/test/javascript/pentaho/context.spec.js
impl/client/src/test/javascript/pentaho/context/impl/Context.spec.js

[BACKLOG-14800] URL feature detection and fallback

---

impl/client/src/main/javascript/web/pentaho/context/impl/Context.js

[BACKLOG-14800] Fix bug occurring in PhantomJS.

---

impl/client/src/main/javascript/web/pentaho/type/function.js

@marcoslarsen, @pentaho/millenniumfalcon please review.

[BACKLOG-12257] Fixed simple function values using toString as a key.

---

impl/server/pom.xml

TO BE MERGED BY BUILDTEAM ONLY!   Pending upstream mavenization of reporting.

[BACKLOG-12334] GAV changes for reporting

---

impl/client/src/test/javascript/pentaho/visual/color/paletteRegistry.spec.js

/cc @diogofscmariano, @afrjorge

[BACKLOG-14077] Fix broken paletteRegistry test due to uphill CDF changes.

---

assemblies/platform-plugin/src/main/resources/resources/web/common-ui-require-js-cfg.js
impl/client/src/main/javascript/web/pentaho/visual/color/paletteRegistry.js
impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.views.conf.js
impl/client/src/test/javascript/pentaho/visual/color/paletteRegistry.spec.js

@pentaho/millenniumfalcon @diogofscmariano please review.
We already found some issues related to multi charts and scrolling.

[BACKLOG-15218] Created default configuration for viz api views

---

impl/client/src/main/javascript/web/dataapi/models-mql.js

- changed the creation of mql-string for a parameterized filter with an array type

[PIR-1317]-array element type mismatch when passing multiple values to one parameter via URL

---

impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.views.conf.js
impl/client/src/test/javascript/pentaho/visual/color/paletteRegistry.spec.js

@pentaho/millenniumfalcon @diogofscmariano please review

[BACKLOG-15218] Fix to palette unit test and removing redundant configurations

---

assemblies/platform-plugin/src/main/resources/resources/web/common-ui-require-js-cfg.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/heatGrid.js
impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js

Merge with https://github.com/pentaho/pentaho-det/pull/718.

[BACKLOG-15219][BACKLOG-15221][BACKLOG-15220] Configuration fixes

---

impl/client/src/main/javascript/web/pentaho/lang/Event.js
impl/client/src/main/javascript/web/pentaho/type/changes/Transaction.js
impl/client/src/main/javascript/web/pentaho/visual/models/abstract.js
impl/client/src/main/javascript/web/pentaho/visual/models/barAbstract.js
impl/client/src/main/javascript/web/pentaho/visual/models/heatGrid.js
impl/client/src/main/javascript/web/pentaho/visual/models/metricDotAbstract.js
impl/client/src/main/javascript/web/pentaho/visual/models/pie.js
impl/client/src/main/javascript/web/pentaho/visual/models/pointAbstract.js
impl/client/src/main/javascript/web/pentaho/visual/models/sunburst.js
impl/client/src/main/javascript/web/pentaho/visual/role/i18n/messages.properties
impl/client/src/main/javascript/web/pentaho/visual/role/level.js
impl/client/src/main/javascript/web/pentaho/visual/role/mapping.js
impl/client/src/test/javascript/pentaho/visual/role/mapping.spec.js

Merge before but along with: https://github.com/pentaho/pentaho-analyzer/pull/1445

[BACKLOG-13730]

---

impl/client/src/main/javascript/web/pentaho/type/simple.js
impl/client/src/test/javascript/pentaho/type/filter/isEqual.spec.js
impl/client/src/test/javascript/pentaho/type/simple.serialization.spec.js

/cc @pentaho/bobafett, @annapopova1

[BACKLOG-12256] Fix serialization of simple values.

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js

Also fixed datums having all-null measures being included in selections.

[BACKLOG-15020] Display selection count in the tooltip.

---

impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js

- Added title font
- Changed xAxis and yAxis band size min to more context specific scenarios
- Moved line visibility property to a new config group to hide lines for pointAbstract charts
@dcleao please review

[BACKLOG-14077]

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/_util.js
impl/client/src/main/javascript/web/pentaho/i18n.js

* A new form of URL arose coming from CGG…
See main PR: https://github.com/pentaho/pentaho-analyzer/pull/1458

[BACKLOG-15553] PAZ: Charts - Export to PDF is not working

---

impl/client/src/main/javascript/web/pentaho/visual/color/paletteRegistry.js

[BACKLOG-14869] Modified blue color scale.

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/_util.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js
impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js

Replaces https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/986.

[BACKLOG-15218] Fix legend position and style

---

impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js

[BACKLOG-15219] Make bullets always visible

---

impl/client/src/main/javascript/web/pentaho/visual/color/paletteRegistry.js

[BACKLOG-14869] Inverted blue color scale.

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js
impl/client/src/main/javascript/web/pentaho/data/_ElementMock.js

[BACKLOG-15612] Get TableView column index by attribute

---

impl/client/src/main/javascript/web/pentaho/visual/color/paletteRegistry.js

[BACKLOG-14869] Updated documentation concerning the blue color scale.

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/i18n/view_de.properties
impl/client/src/main/javascript/web/pentaho/ccc/visual/i18n/view_fr.properties
impl/client/src/main/javascript/web/pentaho/ccc/visual/i18n/view_ja.properties
impl/client/src/main/javascript/web/pentaho/visual/models/i18n/model.properties
impl/client/src/main/javascript/web/pentaho/visual/models/i18n/model_de.properties
impl/client/src/main/javascript/web/pentaho/visual/models/i18n/model_fr.properties
impl/client/src/main/javascript/web/pentaho/visual/models/i18n/model_ja.properties

Related with https://github.com/pentaho/pentaho-platform-plugin-geo/pull/163

[Backlog 15602] Added French, German and Japanese locales for vizApi 3.0

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/_util.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/barLine.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/categoricalContinuousAbstract.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/donut.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/metricDotAbstract.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/pie.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/pointAbstract.js
impl/client/src/main/javascript/web/pentaho/visual/color/paletteRegistry.js
impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js

[BACKLOG-15553] Styling fixes and cleanup

---

impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js

[BACKLOG-15222] Fixed scatter continuous color scale.

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/axes/MeasureAxis.js

[BACKLOG-15223] Fix NPE on tooltip for interpolated measure.

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js

[BACKLOG-15654] Removed interactivity of trend lines (and their dots).

---

impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js

Refactored the `fillStyle1` function. 
* Added two new fillStyle functions, one for Scatter/Bubble and another one for StackedArea.
* Changed the default Scatter/Bubble color scale to `ryg`

[BACKLOG-15223] Refactored the `fillStyle1` function.

---

assemblies/client-config/pom.xml

[CLEANUP] Use project.version instead of hardcoded 7.1-SNAPSHOT

---

impl/client-config/folder-enabler/src/main/java/org/pentaho/config/impl/ConfigEnabler.java

[BACKLOG-14852] Avoid duplicate fileinstall configurations

---

impl/client-config/folder-enabler/src/main/java/org/pentaho/config/impl/ConfigEnabler.java

[BACKLOG-14852] Limit bundles to be refreshed by config deploy folder

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js

[BACKLOG-15788] Change CCC views legend marker size to be constant

---

impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js

@pentaho/millenniumfalcon, @diogofscmariano please review.

[BACKLOG-15790] Show null values in Heatgrid and Bubble charts

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js

[BACKLOG-15788] Setting visualizations legend dot size to 8px

---

package-res/resources/web/dataapi/models-mql.js

- changed the creation of mql-string for a parameterized filter with an array type

[SP-3409][PIR-1317]-array element type mismatch when passing multiple values to one parameter via URL

---

package-res/resources/web/dataapi/models-mql.js

- changed the creation of mql-string for a parameterized filter with an array type

[SP-3408][PIR-1317]-array element type mismatch when passing multiple values to one parameter via URL

---

impl/client/src/main/javascript/web/dojo/pentaho/common/ExpressionTree.js

- The operator value wasn't set into the operatorSelect, that caused the setting of the first value from the list.

[PIR-1189] Filter Type inconsistency

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js
impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js

and setting the dot size in respect to UX recommendation.

[BACKLOG-15788] Revert legend dot size to 8px by removing its line width

---

impl/client/src/main/javascript/web/pentaho/visual/samples/sandbox/container.js

[CLEANUP] Fixed typo in sample container.

---

impl/client/src/main/javascript/web/util/timeutil.js

[PRD-5879] Datepicker doesn't display a user selection if a date has a 30/45 minute time zone

---

impl/client/src/main/javascript/web/vizapi/ccc/ccc_wrapper.js

- additinal fixing (keep only filter)

[ANALYZER-3108]-Selecting a second chart item selects additional items

---

package-res/resources/web/vizapi/ccc/ccc_wrapper.js

- additinal fixing (keep only filter)

[SP-3428][Backport of ANALYZER-3108 - Selecting a second chart item selects additional items (7.0 Suite)]

---

impl/client/src/main/doc-js/pentaho/config/spec/_namespace.jsdoc

[BACKLOG-15858] Adding forgotten JsDocs namespace file.

---

impl/server/src/main/java/org/pentaho/common/ui/metadata/service/MetadataService.java
impl/server/src/test/java/org/pentaho/common/ui/metadata/service/MetadataServiceTest.java

[PIR-1351]-XSS vulnerability in DataSource name when creating new PIR

---

impl/client/pom.xml
impl/client/src/doc/javascript/config/customPlugins/defineTags.js
impl/client/src/doc/javascript/config/customPlugins/eventHandlers.js
impl/client/src/doc/javascript/config/jsdoc-vizapi.json
impl/client/src/doc/javascript/template/vizApi/publish.js
impl/client/src/doc/javascript/template/vizApi/static/styles/mindtouch-local.css
impl/client/src/doc/javascript/template/vizApi/tmpl/container.tmpl
impl/client/src/doc/javascript/template/vizApi/tmpl/details.tmpl
impl/client/src/doc/javascript/template/vizApi/tmpl/layout.tmpl
impl/client/src/doc/javascript/template/vizApi/tmpl/methods-summary.tmpl
impl/client/src/doc/javascript/template/vizApi/tmpl/summary.tmpl

[BACKLOG-16263] Fix to template errors

---

docs/platform/visual/analyzer-viz-api.md
docs/platform/visual/index.md

[BACKLOG-16452] Changing the naming of VizAPI to “previous”/“new”.

---

docs/platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md
docs/platform/visual/samples/bar-d3-sandbox/step3-view-creation.md

[BACKLOG-16452] Fixing url to viz-api beta release package

---

impl/client/src/main/javascript/web/dojo/pentaho/common/Dialog.js
impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.html

Fix z-index issues with date picker month lists from PIR-1334 and PIR-1327.

Fix z-index issues with date picker month lists from

---

impl/client/src/main/javascript/web/dojo/pentaho/common/datasourceselect.js
impl/server/src/main/java/org/pentaho/common/ui/metadata/model/impl/Category.java
impl/server/src/main/java/org/pentaho/common/ui/metadata/service/MetadataService.java
impl/server/src/test/java/org/pentaho/common/ui/metadata/model/impl/CategoryTest.java
impl/server/src/test/java/org/pentaho/common/ui/metadata/service/MetadataServiceTest.java

- fixing exception for case when add any field to report
- fixing executing  malicious code when datasource deleting

[SP-3569][PIR-1351]-XSS vulnerability in DataSource name when creating new PIR

---

docs/platform/visual/analyzer-viz-api.md
docs/platform/visual/index.md

* Also, completed the generic path to the Karaf folder: `system/karaf/deploy`.

[BACKLOG-16452] Added callout advising to create a backup to the VizAPI/Analyzer article.

---

impl/client/src/main/javascript/web/pentaho/visual/color/paletteRegistry.js

[BACKLOG-16201] Replaced the default blue color to #005DA6.

---

docs/platform/web-project.md

@pentaho/millenniumfalcon please review. 
Preview here: http://graimundo.github.io/pentaho-platform-plugin-common-ui/platform/web-project
Please squash merge with proper commit message when merged.

Web-project documentation

---

impl/client/src/main/javascript/web/pentaho/visual/color/paletteRegistry.js
impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js

Backported Backlog-16201 to 7.1.
@pamval @dkincade @duarteteixeira please review

[SP-3610][BACKLOG-16201] - Fix to enable selection visualization

---

docs/platform/configuration.md
docs/platform/visual/analyzer-viz-api.md
docs/platform/visual/samples/bar-d3-sandbox/step5-view-interactivity.md

[BACKLOG-16452] Applying changes that result from QA's review

---

impl/client/src/main/javascript/web/pentaho/lang/Base.js
impl/client/src/main/javascript/web/pentaho/shim/es5.js
impl/client/src/main/javascript/web/pentaho/type/Context.js
impl/client/src/main/javascript/web/pentaho/type/_type.js
impl/client/src/main/javascript/web/pentaho/type/instance.js
impl/client/src/main/javascript/web/pentaho/type/refinement.js
impl/client/src/test/javascript/pentaho/lang/Base.spec.js
impl/client/src/test/javascript/pentaho/type/_type.serialization.spec.js
impl/client/src/test/javascript/pentaho/type/_type.spec.js
impl/client/src/test/javascript/pentaho/type/instance.serialization.spec.js
impl/client/src/test/javascript/pentaho/type/refinement.spec.js
impl/client/src/test/javascript/pentaho/type/value.spec.js

[BACKLOG-16765] Enrich types with mixin ability

---

docs/platform/configuration.md
docs/platform/visual/analyzer-viz-api.md
docs/platform/visual/samples/bar-d3-sandbox/step2-model-creation.md

[BACKLOG-16452] Fix to broken links in the documentation pages

---

impl/client/src/main/javascript/web/prompting/components/DojoDateTextBoxComponent.js

Reverts pentaho/pentaho-platform-plugin-common-ui#1083
This PR caused unit test failures.
To merge along with https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/604.
@mbatchelor @pamval @tmorgner @mchen-len-son @duarteteixeira please revert.

Revert "[PIR-1339] Datepicker in PIR prompt incorrectly applies date format with minutes"

---

impl/client/src/doc/javascript/config/customPlugins/defineTags.js
impl/client/src/doc/javascript/template/vizApi/tmpl/amd.tmpl
impl/client/src/doc/javascript/template/vizApi/tmpl/container.tmpl

This should be included in 7.1-Doc branch so that we have proper amd module's documentation and Interfaces in the Namespace pages

[BACKLOG-17015] Fix to template interface summary and amd tag

---

package-res/resources/web/dojo/pentaho/common/datasourceselect.js
src/org/pentaho/common/ui/metadata/model/impl/Category.java
src/org/pentaho/common/ui/metadata/service/MetadataService.java
test-src/org/pentaho/common/ui/metadata/model/impl/CategoryTest.java
test-src/org/pentaho/common/ui/metadata/service/MetadataServiceTest.java

- fixing exception for case when add any field to report
- fixing executing malicious code when datasource deleting

[SP-3570][[PIR-1351]-XSS vulnerability in DataSource name when creating new PIR

---

assemblies/platform-plugin/src/main/resources/resources/web/common-ui-require-js-cfg.js

[BACKLOG-17293] Removing config that was moved to webcontext.js

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FieldList.js

[PIR-1355]-Fields highlighting works incorrectly for multiple selection

---

impl/client/src/main/javascript/web/pentaho/type/changes/ComplexChangeset.js
impl/client/src/test/javascript/pentaho/type/changes/ComplexChangeset.spec.js

[BACKLOG-16423] Fix regression caused by __ normalization.

---

impl/client/src/main/javascript/web/pentaho/type/Context.js
impl/client/src/main/javascript/web/pentaho/type/changes/Add.js
impl/client/src/main/javascript/web/pentaho/type/changes/Changeset.js
impl/client/src/main/javascript/web/pentaho/type/changes/Clear.js
impl/client/src/main/javascript/web/pentaho/type/changes/ComplexChangeset.js
impl/client/src/main/javascript/web/pentaho/type/changes/ListChangeset.js
impl/client/src/main/javascript/web/pentaho/type/changes/PrimitiveChange.js
impl/client/src/main/javascript/web/pentaho/type/changes/Remove.js
impl/client/src/main/javascript/web/pentaho/type/changes/Replace.js
impl/client/src/main/javascript/web/pentaho/type/changes/Transaction.js
impl/client/src/main/javascript/web/pentaho/type/changes/TransactionScope.js
impl/client/src/main/javascript/web/pentaho/type/complex.js
impl/client/src/main/javascript/web/pentaho/type/list.js
impl/client/src/main/javascript/web/pentaho/type/mixins/Container.js
impl/client/src/test/javascript/pentaho/type/changes/ComplexChangeset.spec.js
impl/client/src/test/javascript/pentaho/type/changes/ListChangeset.spec.js
impl/client/src/test/javascript/pentaho/type/changes/Transaction.spec.js
impl/client/src/test/javascript/pentaho/type/changes/TransactionScope.spec.js

[BACKLOG-16423] Missed renames.

---

impl/client/src/main/javascript/web/prompting/PromptPanel.js
impl/client/src/test/javascript/prompting/PromptPanel.spec.js

[PRD-5909]-Using the a period (.) in parameter name makes this parameter

---

impl/client/src/test/javascript/prompting/PromptPanel.spec.js

@dcleao, could you please have a look?

Fixed it test

---

assemblies/platform-plugin/src/main/resources/resources/web/common-ui-require-js-cfg.js
impl/client/src/main/javascript/web/jquery/jquery.conflict.js
impl/client/src/test/config/javascript/require.config.js

@pentaho/millenniumfalcon, @afrjorge please review.

[BACKLOG-17504] DET: Geo Map doesn't render

---

impl/client/src/main/javascript/web/jquery/jquery.conflict.js

[BACKLOG-17504] Fixing copyright header.

---

assemblies/platform-plugin/src/main/resources/resources/web/common-ui-require-js-cfg.js
impl/client/src/main/doc-js/pentaho/context/spec/IServer.jsdoc
impl/client/src/main/javascript/web/pentaho/context/impl/Context.js
impl/client/src/main/javascript/web/pentaho/i18n.js
impl/client/src/test/config/javascript/context-begin.js
impl/client/src/test/javascript/pentaho/context.spec.js
impl/client/src/test/javascript/pentaho/context/impl/Context.spec.js

To be merged before:
- https://github.com/pentaho/pentaho-det/pull/911
- https://github.com/pentaho/pentaho-det-ee/pull/464
- https://github.com/pentaho/pentaho-platform/pull/3700
- https://github.com/pentaho/pentaho-osgi-bundles/pull/219
- https://github.com/pentaho/pentaho-platform-plugin-geo/pull/198

[BACKLOG-17196] Adding the cxf endpoint to pentaho/context module

---

impl/client/src/test/javascript/prompting/builders/DropDownBuilder.spec.js

[BACKLOG-17688,TEST] DEV: Change the prompt API to accept a parameter to enable the "Select2" library

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FieldList.js

[SP-3679][PIR-1355]-Fields highlighting works incorrectly for multiple selection

---

impl/client/src/main/doc-js/pentaho/environment/IServer.jsdoc
impl/client/src/main/doc-js/pentaho/environment/spec/IServer.jsdoc
impl/client/src/main/javascript/web/pentaho/environment/impl/Environment.js
impl/client/src/test/javascript/pentaho/environment.spec.js
impl/client/src/test/javascript/pentaho/environment/impl/Environment.spec.js

Merge before:
- https://github.com/pentaho/pentaho-platform/pull/3716
- https://github.com/pentaho/pentaho-osgi-bundles/pull/221

[BACKLOG-17190] Adding osgiRoot property to access osgi resources

---

impl/client/src/main/javascript/web/dojo/pentaho/common/overrides/dojo/_base/config.js
impl/client/src/test/javascript/prompting/builders/TextInputBuilder.spec.js

- fix number parse first run error, allow setting the pentaho platform session locale in the dojo config

[BACKLOG-17488] Added LT, LTE, GT and GTE to prompt builder

---

impl/client/src/main/javascript/web/prompting/PromptPanel.js
impl/client/src/main/javascript/web/prompting/api/OperationAPI.js
impl/client/src/main/javascript/web/prompting/api/PromptingAPI.js
impl/client/src/test/javascript/prompting/PromptPanel.spec.js

https://github.com/pentaho/pentaho-det/pull/944

[BACKLOG-17609] Allow passing options for the prompt renderer constructor

---

assemblies/platform-plugin/src/main/resources/resources/web/common-ui-require-js-cfg.js

Please review @pentaho/bobafett

[BACKLOG-18124] Added missing require config entry

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FieldList.js

- reworked fields selection reset on mouse right click

[PIR-1355] Fields highlighting works incorrectly for multiple selection

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js

@pentaho/kashyyyk @nantunes Please review

[BACKLOG-17820] - Enable multi selection on a chart in model view.

---

docs/platform/visual/analyzer-viz-api.md
docs/platform/visual/configuration.md
docs/platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md
docs/platform/visual/samples/bar-d3-sandbox/step2-model-creation.md
docs/platform/visual/samples/bar-d3-sandbox/step3-view-creation.md
docs/platform/visual/samples/bar-d3-sandbox/step5-view-interactivity.md
docs/platform/visual/samples/bar-d3-sandbox/step6-default-configuration.md

To be merged only when http://jira.pentaho.com/browse/ENGOPS-3345 is handled.
To be merged together with on https://github.com/pentaho/pentaho-engineering-samples/pull/30.

Backlog guidance doc updates

---

impl/client/src/main/javascript/web/pentaho/data/filter/_core/isLike.js

Please review @pentaho/bobafett @pentaho/millenniumfalcon

[BACKLOG-18124] Replaced unsupported function endsWith

---

impl/client/src/main/doc-js/pentaho/data/ITable.jsdoc
impl/client/src/main/javascript/web/pentaho/data/_AbstractTable.js
impl/client/src/main/javascript/web/pentaho/data/filter/abstract.js
impl/client/src/main/javascript/web/pentaho/visual/action/SelectionModes.js
impl/client/src/test/javascript/pentaho/data/filter/abstract.spec.js
impl/client/src/test/javascript/pentaho/visual/action/SelectionModes.spec.js

[BACKLOG-18489] -  Added method to create extensional representation of a filter.

---

docs/platform/visual/configuration.md
impl/client-config/client-config/src/main/resources-filtered/config.js

[BACKLOG-18432] Fix colors with a bad format.

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/axes/DiscreteAxis.js

Needs https://github.com/webdetails/ccc/pull/302.

[BACKLOG-18740] Include non-virtual null attributes when creating filter from complex

---

impl/client/src/main/javascript/web/pentaho/visual/color/level.js
impl/client/src/main/javascript/web/pentaho/visual/role/level.js

[CLEANUP] Typos.

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/axes/DiscreteAxis.js

Depends on https://github.com/webdetails/ccc/pull/312.

[BACKLOG-18740] Allow null values on where specification

---

platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md
platform/visual/samples/bar-d3-sandbox/step3-view-creation.md

@pentaho/millenniumfalcon please review. Something services team complained.

Fix RequireJS path in case-sensitive OS

---

impl/client/src/main/javascript/web/dojo/pentaho/common/propertiesPanel/Panel.js

[ANALYZER-3045]-The layout panel is dissapeared after adding field with back-slash ( \ ) on canvas

---

impl/client/src/main/javascript/web/pentaho/context/impl/Context.js
impl/client/src/main/javascript/web/pentaho/i18n.js

[SP-3767] Backport of CDE-912 - Uncaught Error: Load timeout for modules when embedding dashboard within Pentaho Server (7.1 Suite)

---

impl/client/src/main/javascript/web/pentaho/context/impl/Context.js
impl/client/src/main/javascript/web/pentaho/i18n.js

Reverts pentaho/pentaho-platform-plugin-common-ui#1170

Revert "[SP-3767] Backport of CDE-912 - Uncaught Error: Load timeout for modules when embedding dashboard within Pentaho Server (7.1 Suite)"

---

impl/client/src/main/javascript/web/util/formatting.js

[PRD-5939: Unable to open a prpt that uses several timezones]

---

docs/_config.yml
docs/platform/visual/analyzer-viz-api.md

Related PR:
- https://github.com/pentaho/pentaho-platform-ee/pull/1215

[BACKLOG-19262] Updated direct references to mindtouch links

---

impl/client/src/main/javascript/web/dataapi/controller.js
impl/client/src/main/javascript/web/dataapi/models-mql.js
impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.html
impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.js

- hyperlinks "Excludes" and "Includes" were fixed and now working
- CONDITION_TYPES.IN was added
- filter title and filter dialog now correspond with the last saved filter state
- unsafe console usages were wrapped

[PIR-1365] Report filter not working correctly

---

impl/client/pom.xml
impl/client/src/doc/javascript/config/customPlugins/eventHandlers.js
impl/client/src/doc/javascript/config/jsdoc-vizapi.json
impl/client/src/doc/javascript/template/vizApi/tmpl/container.tmpl
impl/client/src/doc/javascript/template/vizApi/tmpl/details.tmpl
pom.xml

[DOC-3679] Small tweak to the template to make it applicable to VizApi and CDF

---

docs/platform/configuration.md
impl/client/src/main/javascript/web/pentaho/VizApiReadme.md

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.js

Reverts pentaho/pentaho-platform-plugin-common-ui#1189

Revert "[PIR-1311]-The japanese symbols displays like &#22823;"

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/heatGrid.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/pie.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/sunburst.js

[ANALYZER-3616] Fixes to Member Palette colors and HeatGrid.

---

_layouts/7.1_default.html
_layouts/7.1_intro.html
_layouts/7.1_sub-intro.html

@pentaho/millenniumfalcon please review and merge, before QAs catch it. ;-)

[BACKLOG-19906] Fix 7.1 callout to 8.0 link

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.js

[PIR-1311] The japanese symbols displays like &#22823;

---

_layouts/default.html
_layouts/intro.html
_layouts/sub-intro.html
_sass/_api-list.scss
assets/css/style.scss
platform/configuration.md
platform/visual/index.md

[BACKLOG-19906] QA and UX validation fixes

---

docs/_config.yml
docs/platform/whats-new-beta-2.md

[BACKLOG-19906] Fixed docs' link to UTypeModule

---

7.1/platform/visual/configuration.md
_config.yml
platform/visual/configuration.md
platform/whats-new-beta-2.md

[BACKLOG-19906] Fixed several broken links.

---

7.1/platform/visual/index.md
platform/visual/configuration.md

Fixing links to the CCC "minisite".

---

impl/server/pom.xml

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-1757] version name consolidation

---

assemblies/platform-plugin/pom.xml
assemblies/platform-plugin/src/main/assembly/prepareAssembly.xml

Depends on https://github.com/pentaho/pentaho-commons-gwt-modules/pull/649

[BACKLOG-20163] Update downstreams

---

docs/platform/visual/samples/bar-d3-sandbox/step6-view-interactivity.md
impl/client/src/main/doc-js/pentaho/visual/action/SelectionMode.jsdoc
impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js
impl/client/src/main/javascript/web/pentaho/type/action/Execution.js
impl/client/src/main/javascript/web/pentaho/type/action/States.js
impl/client/src/main/javascript/web/pentaho/type/action/base.js
impl/client/src/main/javascript/web/pentaho/type/action/impl/target.js
impl/client/src/main/javascript/web/pentaho/type/i18n/types.properties
impl/client/src/main/javascript/web/pentaho/visual/action/select.js
impl/client/src/test/javascript/pentaho/type/action/Execution.spec.js
impl/client/src/test/javascript/pentaho/type/action/base.spec.js
impl/client/src/test/javascript/pentaho/type/action/impl/target.spec.js
impl/client/src/test/javascript/pentaho/visual/action/base.spec.js
impl/client/src/test/javascript/pentaho/visual/action/execute.spec.js
impl/client/src/test/javascript/pentaho/visual/action/select.spec.js
impl/client/src/test/javascript/pentaho/visual/action/update.spec.js

Merge along with:
* https://github.com/webdetails/cgg/pull/113
* https://github.com/pentaho/pentaho-analyzer/pull/1696

[BACKLOG-19949][BACKLOG-19950] Implementing unit tests and some fixes

---

impl/client/src/main/javascript/web/dojo/pentaho/common/RowLimitControl.html
impl/client/src/main/javascript/web/dojo/pentaho/common/RowLimitControl.js

@tmorgner , @kcruzada please review.
(the changes from this PR https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/867 were updated to master branch)

[PRD-5827] - Browser freezes when marking elements on the report toolbar and trying to put data in from keyboard

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.html
impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.js

- parameter name now hides if (is null | not is null) condition was selected

[PIR-1391] Filter Parameter Name can not be saved if condition in (is null; is not null)

---

impl/client/src/main/javascript/web/pentaho/i18n.js
impl/client/src/main/javascript/web/pentaho/util/url.js
impl/client/src/test/config/javascript/require.config.js
impl/client/src/test/javascript/pentaho/i18n.spec.js

[DOC][CLEANUP] Adding docs to url util and unit tests for i18n amd loader plugin

---

impl/server/pom.xml

@pentaho/2-1b
Depends on pentaho/pentaho-commons-xul#143

[BACKLOG-20423] Update downstreams

---

impl/server/pom.xml

@pentaho/2-1b gav change
for pentaho/pentaho-metadata/pull/186

[BACKLOG-13306] GAV change

---

impl/client/src/main/javascript/web/dojo/pentaho/common/PageControl.js
impl/client/src/main/javascript/web/dojo/pentaho/common/RowLimitControl.js

Additional pr to https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1229
Fix for the case when user select label and input data
Goes with https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/685

[PRD-5827] - Browser freezes when marking elements on the report toolbar and trying to put data in  from keyboard.

---

impl/server/pom.xml

@pentaho/x-wing 
Depends on https://github.com/pentaho/pentaho-commons-database/pull/149

[BACKLOG-20414] pentaho-commons-database downstream update

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/_util.js

[BACKLOG-21192] VizAPI updates - FIX issue with member palettes not working

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js

[BACKLOG-22091] Disable the originIsZero of the base axis

---

assemblies/pom.xml
assemblies/webpackage/pom.xml
assemblies/webpackage/src/main/resources-filtered/common-ui/i18nMock.js
assemblies/webpackage/src/main/resources-filtered/common-ui/package.json
assemblies/webpackage/src/main/resources-filtered/common-ui/preconfig.js

[BACKLOG-21717] Common-ui webpackage assembly

---

impl/client/src/test/config/javascript/karma.ci.conf.js

[CLEANUP] JS coverage scripts path.

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/cartesianAbstract.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/categoricalContinuousAbstract.js
impl/client/src/main/javascript/web/pentaho/ccc/visual/metricPointAbstract.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/entityWithTimeIntervalKeyStrategy.js

[BACKLOG-21391] Min tick unit equals EntityWithTimeIntervalKey duration

---

impl/client/src/test/javascript/pentaho/visual/base/view.spec.js

[BACKLOG - 21825] Test view is dirty on model change

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/abstract.js
impl/client/src/main/javascript/web/pentaho/visual/models/types/multiChartOverflow.js
impl/client/src/main/javascript/web/vizapi/ccc/ccc_wrapper.js

* Added the `page` value to the `multiChartOverflow` option.
* Added pagination to the CCC Abstract view.
* Added pagination to the VizAPI 2.0 ccc wrapper.
Depends on:
* https://github.com/webdetails/ccc/pull/340

[BACKLOG-22643] Need all multi-charts from analyzer report to be exported to PDF

---

impl/client/src/main/javascript/web/pentaho/visual/base/modelAdapter.js
impl/client/src/main/javascript/web/pentaho/visual/base/view.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/allStrategies.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/entityWithTimeIntervalKeyStrategy.js

[BACKLOG-22814] - Fine-tuned requirejs resources

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.html
impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.js

- additional UI changes were introduced:
- close dialog button (X) was removed
- fixed the layout issue with Crystal theme
- little code cleanup

[PIR-1400] UI - Filter dialog box issue. Value field moves to the next row

---

impl/client/src/main/javascript/web/prompting/PromptPanel.js

@pentaho/bobafett please review

[BACKLOG-22967] Select filter keeps showing the loading screen

---

impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/entityWithTimeIntervalKeyStrategy.js
impl/client/src/test/javascript/pentaho/visual/role/adaptation/entityWithTimeIntervalKeyStrategy.spec.js

Merge with https://github.com/pentaho/pentaho-analyzer/pull/1800.

[BACKLOG-22986] Fixing case where the input field of a EntityWithTimeIntervalStrategy strategy is null.

---

docs/7.1/platform/visual/samples/bar-d3-sandbox/step2-model-creation.md

[BACKLOG-21292] Fix in VizAPI Tutorial Docs.

---

platform/whats-new-beta-3.md

[BACKLOG-21292] Fix namespace of IIsLike in VizAPI Tutorial Docs.

---

docs/platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md

[BACKLOG-21292] Fix checkout branch in VizAPI Tutorial Docs.

---

docs/platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md
docs/platform/visual/samples/bar-d3-sandbox/step2-model-creation.md
docs/platform/visual/samples/bar-d3-sandbox/step7-default-configuration.md
docs/platform/visual/whats-new-beta-3.md

gh-pages PR: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1298

[BACKLOG-21292] Fixes to the 8.1 tutorial documentation.

---

assemblies/webpackage/src/main/resources-filtered/common-ui/preconfig.js

[BACKLOG-22048] Removed i18nMock compressed paths configuration

---

assemblies/webpackage/src/main/resources-filtered/common-ui/package.json
assemblies/webpackage/src/main/resources-filtered/common-ui/preconfig.js
impl/client-config/client-config/src/main/resources-filtered/config.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/CombineStrategy.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/EntityWithNumberKeyStrategy.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/EntityWithTimeIntervalKeyStrategy.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/IdentityStrategy.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/Strategy.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/TimeIntervalDuration.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/TupleStrategy.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/allStrategies.js
impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js
impl/client/src/test/javascript/pentaho/visual/role/adaptation/CombineStrategy.spec.js
impl/client/src/test/javascript/pentaho/visual/role/adaptation/EntityWithNumberlKeyStrategy.spec.js
impl/client/src/test/javascript/pentaho/visual/role/adaptation/EntityWithTimeIntervalKeyStrategy.spec.js
impl/client/src/test/javascript/pentaho/visual/role/adaptation/Strategy.spec.js
impl/client/src/test/javascript/pentaho/visual/role/adaptationUtil.js

[BACKLOG-22100][BACKLOG-22267] [BACKLOG-22268] Visual role mapping strategies

---

assemblies/webpackage/src/main/resources-filtered/common-ui/package.json

[CLEANUP] Add cdf dependency to webpackage

---

assemblies/webpackage/src/main/resources-filtered/common-ui/package.json
impl/client/package-lock.json
impl/client/src/main/doc-js/pentaho/module/IMeta.jsdoc
impl/client/src/main/doc-js/pentaho/theme/_namespace.jsdoc
impl/client/src/main/doc-js/pentaho/theme/spec/IConfiguration.jsdoc
impl/client/src/main/doc-js/pentaho/theme/spec/_namespace.jsdoc
impl/client/src/main/javascript/web/pentaho/_core/Core.js
impl/client/src/main/javascript/web/pentaho/_core/module/Meta.js
impl/client/src/main/javascript/web/pentaho/module/util.js
impl/client/src/main/javascript/web/pentaho/theme/main.js
impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js
impl/client/src/test/javascript/pentaho/_core/module/Meta.spec.js
impl/client/src/test/javascript/pentaho/theme/main.spec.js

[BACKLOG-23472] Adds `pentaho/theme` AMD loader plugin.

---

impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/EntityWithTimeIntervalKeyStrategy.js
impl/client/src/test/javascript/pentaho/visual/role/adaptation/EntityWithTimeIntervalKeyStrategy.spec.js

[BACKLOG-25511] Default to true when isStartDateTimeProvided is omitted

---

impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js

[BACKLOG-24643] Fix regression caused in DET.

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/Abstract.js

[BACKLOG-25973] Multi-Chart Layouts (Pie & Sunburst) result in incorrect label sizes.

---

assemblies/npmpackage/src/assembly/assembly.xml
assemblies/npmpackage/src/main/javascript/viz-api/init-sandbox
assemblies/npmpackage/src/main/javascript/viz-api/sandbox/_npmignore
assemblies/npmpackage/src/main/javascript/viz-api/sandbox/sandbox.html
docs/platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md
docs/platform/visual/samples/bar-d3-sandbox/step2-model-creation.md
docs/platform/visual/samples/bar-d3-sandbox/step7-default-configuration.md

[BACKLOG-26361] Prepare for beta4 dev package release

---

docs/7.1/platform/visual/analyzer-viz-api.md
docs/8.0/platform/visual/analyzer-viz-api.md
docs/8.1/platform/visual/analyzer-viz-api.md
docs/platform/visual/analyzer-viz-api.md

[CLEANUP] Typo in Vis. Id.

---

assemblies/npmpackage/src/main/javascript/viz-api/webcontext.js
impl/client/src/main/resources-filtered/web/require-cfg.js
impl/client/src/test/config/javascript/context-begin.js
impl/client/src/test/javascript/testSamples/examples/angular-directives/index.html
impl/client/src/test/javascript/testSamples/require-config.js

- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/702
- https://github.com/pentaho/pentaho-sdk/pull/17
- https://github.com/pentaho/data-access/pull/1026
- https://github.com/pentaho/pentaho-analyzer/pull/1887
- https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/726
- https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/657
- https://github.com/pentaho/pentaho-platform-plugin-dashboards/pull/464
- https://github.com/pentaho/pentaho-platform/pull/4297
- https://github.com/pentaho/pentaho-platform-ee/pull/1286

[BACKLOG-17305] Replace pen.require/define by require/define

---

impl/client/src/main/doc-js/pentaho/data/ITable.jsdoc
impl/client/src/main/javascript/web/pentaho/data/Attribute.js
impl/client/src/main/javascript/web/pentaho/data/_AbstractTable.js
impl/client/src/main/javascript/web/pentaho/data/_Table.js
impl/client/src/main/javascript/web/pentaho/data/_TableView.js
impl/client/src/main/javascript/web/pentaho/data/_cross/Table.js
impl/client/src/main/javascript/web/pentaho/data/_plain/Table.js
impl/client/src/main/javascript/web/pentaho/visual/config/vizApi.conf.js
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/EntityWithTimeIntervalKeyStrategy.js
impl/client/src/main/javascript/web/pentaho/visual/role/util.js
impl/client/src/test/javascript/pentaho/data/Attribute.spec.js
impl/client/src/test/javascript/pentaho/data/Table.spec.js
impl/client/src/test/javascript/pentaho/data/TableView.spec.js
impl/client/src/test/javascript/pentaho/visual/role/adaptation/EntityWithTimeIntervalKeyStrategy.spec.js
impl/client/src/test/javascript/pentaho/visual/role/util.spec.js

Merge along with:
- https://github.com/pentaho/pentaho-analyzer/pull/1889
- https://github.com/pentaho/pentaho-det/pull/1281
- https://github.com/pentaho/pentaho-det-ee/pull/575

[BACKLOG-26166] DET (Model view) / PAZ: Scatter allows invalid combinations on axis drop zones

---

docs/7.1/platform/visual/index.md
docs/7.1/platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md
docs/8.0/platform/visual/index.md
docs/8.0/platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md
docs/8.1/platform/visual/index.md
docs/8.1/platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md
docs/platform/visual/index.md
docs/platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md
docs/platform/whats-new-beta-4.md

[BACKLOG-26361] Update VizAPI 3.0 tutorial to reflect 8.2 improvements

---

platform/whats-new-beta-4.md

[BACKLOG-26361] Update Viz. API tutorial for 8.2.

---

docs/platform/whats-new-beta-4.md

[BACKLOG-26361] Fix Viz API tutorial broken links to reference docs (ii).

---

impl/client/pom.xml
impl/client/src/doc/javascript/config/mt-upload-vizapi.json

[BACKLOG-26767] Removed mindtouch version property

---

assemblies/npmpackage/src/main/javascript/viz-api/loader.js

[BACKLOG-27142] Fix ES6 Viz API loader.

---

impl/client-config/folder-enabler/pom.xml

[BACKLOG-27567] Centralize org.osgi dependencies management

---

impl/client/src/main/javascript/web/prompting/PromptPanel.js
impl/client/src/test/javascript/prompting/PromptPanel.spec.js

Reverts pentaho/pentaho-platform-plugin-common-ui#1376

Revert "[SP-4841] - Backport of PIR-1418 - PIR prompt - Control type "Radio B…"

---

impl/client/src/main/javascript/web/pentaho/_core/module/Meta.js

Fixes printing in Analyzer not taking chart options, which come via configuration, into account.

[BACKLOG-27093] Fix concurrency issue.

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/Abstract.js

Merge with: https://github.com/pentaho/pentaho-det/pull/1299.

[BACKLOG-27098] Fix DET max number of cells not being respected by CCC Views.

---

assemblies/webpackage/src/main/resources-filtered/common-ui/package.json
impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js

Merge along with: https://github.com/webdetails/cgg/pull/142.

[BACKLOG-28658] Drilldown doesn't work in scatter visualization

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/Abstract.js

- When the data source has a member palette in a color role position, the wrapped scales did not set their domain function accordingly.
- When Trends and Member Palettes are used in the same chart, the second color axis' colors should not inherit that of the first/main axis colors (which includes member palette colors).
Merge with: https://github.com/webdetails/ccc/pull/362.

[BACKLOG-28632] Error in Browser console when Trend Type is updated

---

impl/client/src/doc/javascript/config/customPlugins/defineTags.js
impl/client/src/doc/javascript/config/customPlugins/eventHandlers.js
impl/client/src/main/doc-js/pentaho/_core/config/_namespace.jsdoc
impl/client/src/main/doc-js/pentaho/type/action/_namespace.jsdoc
impl/client/src/main/javascript/web/pentaho/visual/role/adaptation/Strategy.js

[BACKLOG-28933] Fix to common-ui jsdoc doclets

---

impl/client/src/main/javascript/web/prompting/builders/TextInputBuilder.js
impl/client/src/test/javascript/prompting/builders/TextInputBuilder.spec.js

…xpected.
Merge with: https://github.com/webdetails/cdf/pull/1078
@pentaho-lmartins @bantonio82
@kcruzada

 [PRD-6041] Data Format specified in the Parameter is not working as e

---

impl/client/src/main/javascript/web/prompting/parameters/ParameterDefinitionDiffer.js
impl/client/src/test/javascript/prompting/parameters/ParameterDefinitionDiffer.spec.js

Reverts pentaho/pentaho-platform-plugin-common-ui#1439
@ssamora @pentaho-lmartins

Revert "[SP-5113] Backport of PIR-1442 - Activating auto-refresh after adding…"

---

assemblies/npmpackage/pom.xml
docs/8.2/platform/visual/whats-new-beta-4.md
docs/_config.yml
docs/platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md
docs/platform/visual/whats-new-release.md

[BACKLOG-29550] Viz. API 3.0 tutorial finalization tasks

---

docs/_layouts/sub-intro.html
docs/platform/visual/samples/bar-d3-sandbox/step1-environment-preparation.md

[BACKLOG-29550] Code review by David.

---

assemblies/webpackage/src/main/resources-filtered/common-ui/package.json
assemblies/webpackage/src/main/resources-filtered/common-ui/preconfig.js
impl/client/src/main/config/javascript/build.js
impl/client/src/main/doc-js/pentaho/csrf/IService.jsdoc
impl/client/src/main/doc-js/pentaho/csrf/IToken.jsdoc
impl/client/src/main/doc-js/pentaho/csrf/_namespace.jsdoc
impl/client/src/main/javascript/web/pentaho/csrf/service.js
impl/client/src/main/javascript/web/pentaho/platformBundle.js
impl/client/src/main/javascript/web/pentaho/platformCore.js
impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js
impl/client/src/test/javascript/pentaho/csrf/service.spec.js

This PR is part of a set: https://github.com/pentaho/pentaho-platform-ee/pull/1333.

 [BACKLOG-29696] CSRF Marketo Use Case

---

impl/client/src/main/javascript/web/pentaho/visual/impl/View.js

[BACKLOG-29550] Fix JS documentation for class `pentaho.visual.impl.View`

---

docs/platform/visual/analyzer-viz-api.md

[BACKLOG-29550] Fix broken links in github.io documentation.

---

impl/client/src/main/javascript/web/pentaho/csrf/service.js

[BACKLOG-29696] Take into account when protection is disabled and token isn't returned

---

impl/client/src/main/javascript/web/jquery/jquery.i18n.properties.supported.languages.js

@pentaho/tatooine 
@pentaho-lmartins @dcleao 
Related with: https://github.com/webdetails/cdf/pull/1084

[CDE-1005] CDE dashboard can't be localized at country level

---

impl/client/src/test/javascript/prompting/components/StaticAutocompleteBoxComponent.spec.js

[CLEANUP] - Clean a forgotten focus on a karma describe function

---

impl/client/src/test/javascript/prompting/components/StaticAutocompleteBoxComponent.spec.js

Reverts pentaho/pentaho-platform-plugin-common-ui#1464
@ssamora please revert

Revert "[CLEANUP] - Clean a forgotten focus on a karma describe function"

---

impl/client/src/test/javascript/pentaho/csrf/service.spec.js
impl/client/src/test/javascript/prompting/components/StaticAutocompleteBoxComponent.spec.js

@pentaho/millenniumfalcon @RPAraujo please review

[CLEANUP] Fix to CSRF unit test and removed a 'fdescribe' in prompting api tests

---

assemblies/webpackage/src/main/resources-filtered/common-ui/package.json
impl/client/src/main/javascript/web/handlebars/handlebars-v4.0.5.js
impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js

Reverts pentaho/pentaho-platform-plugin-common-ui#1467

Revert "[PPP-4412] - Upgraded handlebars from verison 4.0.5 to 4.0.13 to addr…"

---

impl/client/src/main/javascript/web/pentaho/util/text.js
impl/client/src/test/javascript/pentaho/util/text.spec.js

[ANALYZER-3823] Adding text utiliity to support building html tooltips.

---

impl/client/src/main/doc-js/pentaho/data/ITable.jsdoc
impl/client/src/main/javascript/web/pentaho/ccc/visual/Abstract.js
impl/client/src/main/javascript/web/pentaho/data/_AbstractTable.js
impl/client/src/main/javascript/web/pentaho/util/text.js
impl/client/src/main/javascript/web/vizapi/DataTable.js
impl/client/src/test/javascript/pentaho/data/Table.spec.js
impl/client/src/test/javascript/pentaho/data/TableView.spec.js
impl/client/src/test/javascript/pentaho/util/text.spec.js

Cheery-pick of #1476 & #1478 into 8.3 branch.
**DO NOT SQUASH!**
This is part of a PR set:
- https://github.com/pentaho/pentaho-platform-plugin-geo/pull/326
- https://github.com/pentaho/pentaho-analyzer/pull/2023
- https://github.com/pentaho/pentaho-det/pull/1332
- https://github.com/pentaho/pentaho-det-ee/pull/606
@smmribeiro @gryphendowre

[SP-5290] Backport of ANALYZER-3823 - Geo Map does not plot values when a caption column is used within a level definition (8.3 Suite)

---

impl/client/src/main/javascript/web/pentaho/lang/EventSource.js
impl/client/src/main/javascript/web/pentaho/util/BitSet.js
impl/client/src/test/javascript/pentaho/lang/EventSource.spec.js

[CLEANUP] Fixes to the documentation and error messages.

---

impl/client/src/main/javascript/web/prompting/components/StaticAutocompleteBoxComponent.js

@pentaho/tatooine @RPAraujo @ssamora
* [PRD-6038] Added lines to ensure cursor is put at the end on process change
* [PRD-6038] Put the process change with a check on the source, to ensure the source gets updated each time characters are added (as designed)
* [PRD-6038] Added a 0.5 second delay, so it will wait half a second after typing has completed to get the updated source value.
* [PRD-6038] Added comments & copyright update
This PR is part of a set:
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1485
- https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/743

[PRD-6038] Auto-complete feature of Text Box is not working as expected when using a query to limit the results returned.

---

impl/client/src/test/config/javascript/karma.ci.conf.js
impl/client/src/test/javascript/util/formatting.spec.js

Reverts pentaho/pentaho-platform-plugin-common-ui#1445

Revert "[PRD-6070] Date Picker showing incorrect value when client is in diff…"

---

impl/client/src/main/javascript/web/prompting/components/StaticAutocompleteBoxComponent.js

@pentaho-lmartins 
@ssamora 
@smmribeiro 
@dcleao

[BISERVER-14512] - Text box values are only displayed for about a second in prpt reports published to PUC

---

impl/client/src/main/javascript/web/prompting/PromptPanel.js
impl/client/src/main/javascript/web/prompting/WidgetBuilder.js
impl/client/src/main/javascript/web/prompting/components/StaticAutocompleteBoxComponent.js
impl/client/src/test/javascript/prompting/PromptPanel.spec.js
impl/client/src/test/javascript/prompting/WidgetBuilder.spec.js
impl/client/src/test/javascript/prompting/components/StaticAutocompleteBoxComponent.spec.js

@pentaho-lmartins 
@ssamora 
@smmribeiro

[SP-5847] - Backport of BISERVER-14512 - Text box values are only displayed for about a second in prpt reports published to PUC (8.3 Suite)

---

impl/client/src/main/javascript/web/prompting/PromptPanel.js
impl/client/src/main/javascript/web/prompting/WidgetBuilder.js
impl/client/src/main/javascript/web/prompting/components/StaticAutocompleteBoxComponent.js
impl/client/src/test/javascript/prompting/PromptPanel.spec.js
impl/client/src/test/javascript/prompting/WidgetBuilder.spec.js
impl/client/src/test/javascript/prompting/components/StaticAutocompleteBoxComponent.spec.js

@pentaho-lmartins 
@ssamora 
@smmribeiro

[SP-5848] - Backport of BISERVER-14512 - Text box values are only displayed for about a second in prpt reports published to PUC (9.1 Suite)

---

impl/client/src/main/doc-js/pentaho/config/spec/IRuleSet.jsdoc
impl/client/src/main/doc-js/pentaho/visual/action/mixins/_namespace.jsdoc
impl/client/src/main/doc-js/pentaho/visual/color/_namespace.jsdoc
impl/client/src/main/doc-js/pentaho/visual/color/palettes/_namespace.jsoc
impl/client/src/main/doc-js/pentaho/visual/scene/impl/_namespace.jsdoc
impl/client/src/main/javascript/web/pentaho/type/action/Change.js

@pentaho/millenniumfalcon @dcleao please review
- Backport PR: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1523

[BACKLOG-32090] VizAPI Docs - Review and Fix JsDoc

---

impl/client/src/main/doc-js/pentaho/config/spec/IRuleSet.jsdoc
impl/client/src/main/doc-js/pentaho/visual/action/mixins/_namespace.jsdoc
impl/client/src/main/doc-js/pentaho/visual/color/_namespace.jsdoc
impl/client/src/main/doc-js/pentaho/visual/color/palettes/_namespace.jsoc
impl/client/src/main/doc-js/pentaho/visual/scene/impl/_namespace.jsdoc
impl/client/src/main/javascript/web/pentaho/type/action/Change.js

@pentaho/millenniumfalcon @dcleao @ssamora please review

[BACKLOG-32090] Backport - Jsdoc documentation fix

---

impl/client-config/client-config/src/main/resources-filtered/config.js

- Adding examples of how to center the cartesian axes' title
@bennychow please review.

[ANALYZER-4000] Provide more examples of VizAPI configuration

---

impl/client/src/main/javascript/web/pentaho/ccc/visual/i18n/view_en.properties
impl/client/src/main/javascript/web/pentaho/type/i18n/types_en.properties
impl/client/src/main/javascript/web/pentaho/visual/color/i18n/messages_en.properties
impl/client/src/main/javascript/web/pentaho/visual/i18n/model_en.properties
impl/client/src/main/javascript/web/pentaho/visual/models/i18n/model_en.properties
impl/client/src/main/javascript/web/pentaho/visual/role/i18n/messages_en.properties
impl/client/src/main/javascript/web/pentaho/visual/samples/calc/i18n/model_en.properties
impl/client/src/main/javascript/web/pentaho/visual/samples/calc/i18n/view_en.properties
impl/client/src/main/javascript/web/prompting/messages/messages_en.properties

@smmribeiro please review
/cc @bennychow

[ANALYZER-4020] Chart Type list not translated in Analyzer if locale is French and PUC Language is set to English

---

impl/client/src/main/javascript/web/pentaho/csrf/service.js
impl/client/src/main/javascript/web/util/pentaho-csrf.js
impl/client/src/test/javascript/pentaho/csrf/service.spec.js

Please, review:
@graimundo
/cc @bennychow if you want to review, be my guest!
/cc @jcarneirohv
Related with pentaho/security-web#4.

[BACKLOG-35000] CSRF refactor

---

impl/client/src/main/javascript/web/pentaho/visual/config.js

[ANALYZER-3942] Fix month precision date tick formatting in stock visualizations for IE 11

---

impl/client/src/main/javascript/web/pentaho/environment/impl/Environment.js

@bennychow please review, merge. Thanks!

[ANALYZER-3942] Fix Environment failing to validate locale on IE11

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.html

[ANALYZER-4028] - Clicking on Date Range Picker with multiple tabs open hides tabs on PUC

---

impl/client/src/main/javascript/web/pentaho/visual/config.js

Please merge without squashing, to preserve equivalence with the original commits.
Merge along with: https://github.com/webdetails/ccc/pull/380.

[SP-6052] Backport of ANALYZER-2977

---

impl/client/src/main/javascript/web/dojo/pentaho/common/ComboColorPicker.js
impl/client/src/main/javascript/web/dojo/pentaho/common/CustomColorPicker.js
impl/client/src/main/javascript/web/dojo/pentaho/common/CustomColorPicker/CustomColorPicker.html

@smmribeiro 
@andreramos89 
@renato-s

[PIR-1061] Color Picker works incorrectly

---

impl/client-config/client-config/src/main/resources-filtered/config.js

@bennychow please review and merge.

[CLEANUP] Update help links in global config file to point to 9.3

---

impl/client/src/main/javascript/web/vizapi/VizController.js
impl/client/src/main/javascript/web/vizapi/ccc/ccc_analyzer_plugin.js

@dcleao 
@bcostahitachivantara @andreramos89 @renato-s

[BACKLOG-35699] CGG samples with viz2 are not working

---

impl/client/src/main/doc-js/pentaho/environment/spec/IEnvironment.jsdoc
impl/client/src/main/javascript/web/pentaho/data/_WithCellTupleBase.js
impl/client/src/main/javascript/web/pentaho/environment/impl/Environment.js
impl/client/src/main/javascript/web/pentaho/i18n/serverService.js
impl/client/src/main/javascript/web/pentaho/visual/config.js
impl/client/src/main/javascript/web/vizapi/VizController.js
impl/client/src/main/javascript/web/vizapi/ccc/ccc_analyzer_plugin.js
impl/client/src/test/javascript/pentaho/environment/impl/Environment.spec.js
impl/client/src/test/javascript/pentaho/environment/main.spec.js

@pentaho/sp-branch-write please review and merge.

[SP-6088] Backport of ANALYZER-3942 - Localized date tick formatting for CCC based stock visualizations

---

impl/client/src/main/doc-js/pentaho/environment/spec/IEnvironment.jsdoc
impl/client/src/main/javascript/web/pentaho/data/_WithCellTupleBase.js
impl/client/src/main/javascript/web/pentaho/environment/impl/Environment.js
impl/client/src/main/javascript/web/pentaho/i18n/serverService.js
impl/client/src/main/javascript/web/pentaho/visual/config.js
impl/client/src/main/javascript/web/vizapi/VizController.js
impl/client/src/main/javascript/web/vizapi/ccc/ccc_analyzer_plugin.js
impl/client/src/test/javascript/pentaho/environment/impl/Environment.spec.js
impl/client/src/test/javascript/pentaho/environment/main.spec.js

@pentaho/sp-branch-write please review and merge.

[SP-6088] Backport of ANALYZER-3942 - Localized date tick formatting for CCC based stock visualizations 

---

impl/client/src/main/doc-js/pentaho/environment/spec/IEnvironment.jsdoc
impl/client/src/main/javascript/web/pentaho/data/_WithCellTupleBase.js
impl/client/src/main/javascript/web/pentaho/environment/impl/Environment.js
impl/client/src/main/javascript/web/pentaho/i18n/serverService.js
impl/client/src/main/javascript/web/pentaho/visual/config.js
impl/client/src/main/javascript/web/vizapi/VizController.js
impl/client/src/main/javascript/web/vizapi/ccc/ccc_analyzer_plugin.js
impl/client/src/test/javascript/pentaho/environment/impl/Environment.spec.js
impl/client/src/test/javascript/pentaho/environment/main.spec.js

@pentaho/sp-branch-write please review and merge.

[SP-6087] Backport of ANALYZER-3942 - Localized date tick formatting for CCC based stock visualizations

---

impl/client/src/main/javascript/web/dataapi/Xmla.js

[BACKLOG-35904] CSRF - Protect the Request Parameters authentication mechanism

---

impl/server/pom.xml

This commit has been cherry-picked from 6dd67285

[SP-6179] [PPP-4654] Get commons-io version from parent pom

---

impl/client/src/main/doc-js/pentaho/config/IService.jsdoc
impl/client/src/main/javascript/web/pentaho/_core/config/Service.js
impl/client/src/test/javascript/pentaho/_core/config/Service.spec.js

@himanshu6201, @varuntangirala, @NJtwentyone, @rmansoor please review.

[BACKLOG-36318] Ability to inherit configuration rules directly in the configuration service

---

impl/client-config/client-config/src/main/resources-filtered/config.js

@himanshu6201, @varuntangirala, @NJtwentyone, @rmansoor please review.

[BACKLOG-36396] Update Pentaho help links to 9.4 on the system config.js file

---

impl/client/src/main/doc-js/pentaho/config/IService.jsdoc
impl/client/src/main/doc-js/pentaho/config/impl/_namespace.jsdoc
impl/client/src/main/javascript/web/pentaho/_core/config/Service.js
impl/client/src/main/javascript/web/pentaho/config/impl/Service.js
impl/client/src/main/javascript/web/pentaho/platformCore.js
impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js
impl/client/src/test/javascript/pentaho/_core/config/Service.spec.js
impl/client/src/test/javascript/pentaho/config/impl/Service.spec.js

**PR set**: https://github.com/pentaho/pentaho-analyzer/pull/2288
Please, do **not** squash.
@himanshu6201, @varuntangirala, @NJtwentyone, @rmansoor please review.
---
For reference, **original PRs** for the `analyzer-viz-view-config` branch where main code reviews were made:
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1577
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1578

[BACKLOG-36156][BACKLOG-36318] PAZ visualization view configuration for 9.4

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FieldList.js

[PIR-1499]Category name not appearing in Available Fields using Find after adding column within it to canvas or filter

---

impl/client/src/main/javascript/web/prompting/components/StaticAutocompleteBoxComponent.js

@smmribeiro 
@bcostahitachivantara 
@renato-s

[BISERVER-14871] Mandatory Parameter Validation breaks if using First Value when Formula is NA

---

assemblies/webpackage/src/main/resources-filtered/common-ui/package.json
impl/client/src/main/javascript/web/handlebars/handlebars-v4.7.7.js
impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js

@smmribeiro 
@andreramos89 
@renato-s

[PPP-4754] - Use of outdated JavaScript libraries

---

impl/client/src/main/javascript/web/dojo/dijit/form/templates/Button.html
impl/client/src/main/javascript/web/dojo/pentaho/common/FormatCombo.js

@pentaho/wcag ,
Please review the changes as suggested in  https://github.com/pentaho/pentaho-analyzer/pull/2327

[BACKLOG-36886] Added Focus Visibility to Layouts and Dialogs

---

impl/client/src/main/javascript/web/prompting/components/StaticAutocompleteBoxComponent.js

@smmribeiro 
@bcostahitachivantara 
@renato-s

[SP-6225] - Backport of BISERVER-14871 - Mandatory Parameter Validation breaks if using First Value when Formula is NA (9.3 Suite)

---

impl/client/src/main/javascript/web/prompting/components/StaticAutocompleteBoxComponent.js

@smmribeiro 
@bcostahitachivantara 
@renato-s

[SP-6226] - Backport of BISERVER-14871 - Mandatory Parameter Validation breaks if using First Value when Formula is NA (9.4 Suite)

---

impl/client/src/main/javascript/web/dojo/dijit/form/templates/DropDownBox.html

@pentaho/wcag Please review ,
Applied Changes suggested in https://github.com/pentaho/pentaho-analyzer/pull/2330

[BACKLOG-36886] Added Focus Visibility to Date Fields

---

impl/server/src/main/java/org/pentaho/common/ui/metadata/service/MetadataServiceUtil.java
impl/server/src/main/java/org/pentaho/common/ui/metadata/service/MetadataServiceUtil2.java

@andreramos89
@bcostahitachivantara
@smmribeiro

[PPP-4801] - GeoJson service is vulnerable to deserialization attacks

---

impl/client/src/main/javascript/web/util/_a11y.js

[BACKLOG-36843]-Accessibility-Buttons and Keycodes

---

impl/server/src/main/java/org/pentaho/common/ui/metadata/service/MetadataServiceUtil.java
impl/server/src/main/java/org/pentaho/common/ui/metadata/service/MetadataServiceUtil2.java

@andreramos89 
@bcostahitachivantara 
@smmribeiro 
Original PR:
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1616

[SP-6303] - Backlog of PPP-4801 - GeoJson service is vulnerable to deserialization attacks (9.3 Suite)

---

impl/client/src/main/javascript/web/util/_dialog.js

Fix recent regression registered as: https://hv-eng.atlassian.net/browse/BACKLOG-37136.
@pentaho/wcag, please review.
Merge with: https://github.com/pentaho/pentaho-commons-gwt-modules/pull/854.

[BACKLOG-37136][BACKLOG-36879][BACKLOG-37033][BACKLOG-37034] Fix multiple jQuery race condition

---

impl/client/src/main/javascript/web/dojo/pentaho/common/overrides/dijit/_PaletteMixin.js

[BACKLOG-37162] Fixing Keyboard Navigation (A) for color palette

---

impl/client/src/main/javascript/web/dojo/pentaho/common/overrides/dijit/Dialog.js
impl/client/src/main/javascript/web/dojo/pentaho/common/propertiesPanel/Panel.js
impl/client/src/main/javascript/web/util/_a11y.js
impl/client/src/main/javascript/web/util/_focus.js

[BACKLOG-36893] Focus order

---

impl/client/src/main/javascript/web/util/BusyIndicator.js

[BACKLOG-37006] - PUC Notifications - Name and Role

---

impl/client/src/main/javascript/web/util/_a11y.js

[BACKLOG-37343] Listbox changes using JS. Removed the changes made with select and option.

---

impl/client/src/main/javascript/web/util/_a11y.js

[BACKLOG-37343] Listbox Shift + Space change

---

impl/client/src/main/javascript/web/dojo/pentaho/common/overrides/dijit/Dialog.js

https://github.com/orgs/pentaho/teams/wcag ,Please review.

[BACKLOG-37444] - FileChooser dialog from hyperlink on analyzer does not receive the focus and Keyboard interaction.

---

assemblies/client-config/pom.xml
assemblies/npmpackage/pom.xml
assemblies/platform-plugin/pom.xml
assemblies/pom.xml
assemblies/webpackage/pom.xml
impl/client-config/client-config/pom.xml
impl/client-config/folder-enabler/pom.xml
impl/client-config/pom.xml
impl/client/pom.xml
impl/pom.xml
impl/server/pom.xml
impl/server/src/it/resources/pentaho-solutions/system/simple-jndi/jdbc.properties
pom.xml

Rebasing wcag with master

---

impl/client/src/main/javascript/web/dojo/pentaho/common/ComboColorPicker.js
impl/client/src/main/javascript/web/dojo/pentaho/common/TabSet.js

@pentaho/wcag , please review.

[BACKLOG-37783] Added keyboard Navigation and focus visibility for top part of Sidebar and in Formatting panel-> tabs for color palette

---

impl/client/src/main/javascript/web/dojo/pentaho/common/TabSet.js

@pentaho/wcag , Please review.
Latest build is unstable. Hence fixing that.

[BACKLOG-37783] Fixed syntax error due to arrow function

---

impl/client/src/main/javascript/web/dojo/pentaho/common/SmallImageButton.js
impl/client/src/main/javascript/web/dojo/pentaho/common/TemplatePicker.js

@pentaho/wcag , please review.

[BACKLOG-37785] Added Keyboard-navigation for select template dialog

---

impl/client/src/main/javascript/web/dojo/pentaho/common/Dialog.js
impl/client/src/main/javascript/web/dojo/pentaho/common/datasourceselect.html
impl/client/src/main/javascript/web/dojo/pentaho/common/datasourceselect.js
impl/client/src/test/javascript/testSamples/datasourcedialogtest.html
impl/client/src/test/javascript/testSamples/filterdialogtest.html

[BACKLOG-37922] Made Select Data Source Keyboard Accessible

---

impl/client/src/main/javascript/web/dojo/dijit/form/templates/ValidationTextBox.html

[BACKLOG-37784] Made page control buttons keyboard navigable and gave focus outlines to input fields in toolbar

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FieldList.js

@pentaho/wcag Please Review.
The tree here is multi-select tree and most of implementation is inspired from that of PAZ.

[BACKLOG-38046] Made Tree Keyboard Accessible

---

impl/client/src/main/javascript/web/dojo/pentaho/common/Dialog.js

@pentaho/wcag Please review
https://hv-eng.atlassian.net/browse/BACKLOG-38132

[BACKLOG-38132] When an operation is done after opening popup, ensure focus restored to query button

---

assemblies/webpackage/src/main/resources-filtered/common-ui/package.json
assemblies/webpackage/src/main/resources-filtered/common-ui/preconfig.js
impl/client/src/main/javascript/web/dojo/pentaho/common/overrides/dojo/store/JsonRest.js
impl/client/src/main/javascript/web/util/_alertDialog/i18n/messages.properties
impl/client/src/main/javascript/web/util/_alertDialog/i18n/messages_en.properties
impl/client/src/main/javascript/web/util/_alertDialog/main.js
impl/client/src/main/javascript/web/util/_alertDialog/themes/styles.css
impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js

@pentaho/hoth, please review.
Part of PR group: https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/16.

[BACKLOG-37995] Patch dojo/store/JsonRest and add _alertDialog utility

---

impl/client/src/main/javascript/web/dojo/pentaho/common/overrides/dijit/Menu.js

Please review @pentaho/wcag 
Merge with https://github.com/pentaho/pentaho-commons-gwt-modules/pull/947, https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/911

[BACKLOG-37807] - Fixed incorrect behavior for keyboard navigation in toolbar

---

assemblies/client-config/pom.xml
assemblies/npmpackage/pom.xml
assemblies/platform-plugin/pom.xml
assemblies/pom.xml
assemblies/webpackage/pom.xml
impl/client-config/client-config/pom.xml
impl/client-config/folder-enabler/pom.xml
impl/client-config/pom.xml
impl/client/pom.xml
impl/pom.xml
impl/server/pom.xml
pom.xml

[CLEANUP] updated versions via release version merger

Merging master into wcag

---

impl/client/src/main/javascript/web/dataapi/controller.js
impl/client/src/main/javascript/web/dojo/pentaho/common/FieldList.js

[BACKLOG-38259] Basic UI changes wherever necessary to accommodate the new calculated fields creation
[BACKLOG-38259]: https://hv-eng.atlassian.net/browse/BACKLOG-38259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-38259] Basic UI changes wherever necessary to accommodate the new calculated fields creation

---

assemblies/platform-plugin/src/main/resources/plugin.xml
impl/client/src/main/javascript/web/util/_a11y.js
impl/client/src/main/javascript/web/util/_focus.js

@pentaho/wcag  , Please review for https://hv-eng.atlassian.net/browse/BACKLOG-37966
Used in https://github.com/pentaho/pentaho-analyzer/pull/2471

[BACKLOG-37966] Toolbar improvements in Analyzer

---

assemblies/client-config/pom.xml
assemblies/npmpackage/pom.xml
assemblies/platform-plugin/pom.xml
assemblies/pom.xml
assemblies/webpackage/pom.xml
impl/client-config/client-config/pom.xml
impl/client-config/folder-enabler/pom.xml
impl/client-config/pom.xml
impl/client/pom.xml
impl/pom.xml
impl/server/pom.xml
pom.xml

Sync feature branch with master/10.1

[BACKLOG-38494] - Upgrade Scheduler Feature Pipeline to Version 10.1

---

impl/client/src/main/javascript/web/prompting/parameters/ParameterDefinition.js
impl/client/src/test/javascript/prompting/parameters/ParameterDefinition.spec.js

'hidden' attribute to dynamically hide and show parameters in the scheduler and elsewhere.

[BACKLOG-38398] Update parameter UI to respond to changes in the

---

impl/client/src/main/javascript/web/prompting/PromptPanel.js

[BACKLOG-37967] - Fixed Prompt panel to restore proper focus

---

impl/client/src/main/javascript/web/dojo/pentaho/common/datasourceselect.js

@pentaho/wcag Please review,
Firefox doesn't support property ariaDisabled

[BACKLOG-37966] Toolbar improvements for PIR

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FieldList.js

[BACKLOG-38046] fixing search function to make its first result tab-able when needed

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FieldList.js

[BACKLOG-38258] Make all UI changes compliant with WCAG

---

impl/client/src/main/javascript/web/prompting/PromptPanel.js
impl/client/src/main/javascript/web/prompting/parameters/ParameterDefinitionDiffer.js

[BACKLOG-38910] Ensure that parameters remain in the same order when

---

impl/client/src/main/javascript/web/dataapi/controller.js
impl/client/src/main/javascript/web/dojo/pentaho/common/FieldList.js
impl/client/src/main/javascript/web/prompting/PromptPanel.js
impl/client/src/main/javascript/web/prompting/parameters/ParameterDefinition.js
impl/client/src/main/javascript/web/prompting/parameters/ParameterDefinitionDiffer.js
impl/client/src/test/javascript/prompting/parameters/ParameterDefinition.spec.js

@pentaho/hoth, please review and merge

[MAINTENANCE] Merging master changes

---

impl/client/src/main/javascript/web/dojo/dijit/themes/pentaho/Dialog.css
impl/client/src/main/javascript/web/dojo/pentaho/common/Dialog.js

- add logic to make dialogs responsive

[BACKLOG-38048] WCAG - PIR -Page Zoom: General -> Template Page Setup

---

impl/client/src/main/javascript/web/dojo/dijit/themes/pentaho/PageControl.css
impl/client/src/main/javascript/web/dojo/pentaho/common/PageControl.js

@pentaho/wcag . Please review
Addressing some comments from https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1679

[BACKLOG-38666] Added Keyboard navigation for previous-next page buttons - Pentaho report viewer

---

impl/client/src/main/javascript/web/pentaho/visual/models/Treemap.js
impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js

Adding Treemap to common-ui requireJS file.
The remaining code for adding this chart was already merged as part of #1712

[BACKLOG-38691] - Create and Add Tree Map Visualization to the available list of Chart options in Analyzer

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.css
impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.html
impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.js

Please review @pentaho/wcag 
To be merged alongside https://github.com/pentaho/pentaho-commons-gwt-modules/pull/994

[BACKLOG-38706] WCAG - PIR - Page Zoom: Filter Dialog

---

License.txt
impl/client/src/main/javascript/web/dojo/pentaho/common/ComboColorPicker.html
impl/client/src/main/javascript/web/dojo/pentaho/common/CustomColorPicker/CustomColorPicker.html
impl/client/src/main/javascript/web/dojo/pentaho/common/ExpressionTree/ExpressionTree.html
impl/client/src/main/javascript/web/dojo/pentaho/common/FieldList.js
impl/client/src/main/javascript/web/dojo/pentaho/common/MessageBox.js
impl/client/src/main/javascript/web/dojo/pentaho/common/SplashScreen.js
impl/client/src/main/javascript/web/dojo/pentaho/common/datasourceselect.js
impl/client/src/main/javascript/web/prompting/builders/ParameterGroupPanelBuilder.js

@pentaho/wcag  and @pentaho/millenniumfalcon  please review
Main PR: https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/1015

Addresses BACKLOG-37996: WCAG main page zoom

---

impl/client/src/main/javascript/web/dojo/pentaho/common/ComboColorPicker.js

[BACKLOG-39219] Make 'In use' section of formatting panel keyboard navigable

---

impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.css
impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.html
impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.js

cherry-pick to master https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1723

[BACKLOG-38706] cherry-pick to master #1723

---

impl/client/src/main/javascript/web/dojo/pentaho/common/responsive/Dialog/i18n/messages.properties
impl/client/src/main/javascript/web/dojo/pentaho/common/responsive/Dialog/i18n/messages_en.properties
impl/client/src/main/javascript/web/dojo/pentaho/common/responsive/Dialog/main.js
impl/client/src/main/javascript/web/dojo/pentaho/common/responsive/Dialog/template.html
impl/client/src/main/javascript/web/dojo/pentaho/common/responsive/Dialog/themes/styles.css
impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js

- `pentaho/common/responsive/Dialog`
https://hv-eng.atlassian.net/browse/BACKLOG-39652
Part of PR set: https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/123
/cc @pentaho/hoth, @pentaho/r2d2

[BACKLOG-39652] Added responsive Dojo dialog base class

---

impl/client/src/main/javascript/web/dojo/pentaho/common/Dialog.js

[BACKLOG-39403] Restore focus after clicking on cross-button in Field Sorting

---

impl/client/src/main/javascript/web/dojo/pentaho/common/datasourceselect.js

trying to select the first data source in the list.

[BACKLOG-39911] Previous change removed a check for an empty list before

---

assemblies/webpackage/src/main/resources-filtered/common-ui/package.json
assemblies/webpackage/src/main/resources-filtered/common-ui/preconfig.js
impl/client/src/main/javascript/web/pentaho/visual/models/Gauge.js
impl/client/src/main/javascript/web/pentaho/visual/models/all.js
impl/client/src/main/javascript/web/pentaho/visual/models/i18n/model.properties
impl/client/src/main/javascript/web/pentaho/visual/models/i18n/model_en.properties
impl/client/src/main/javascript/web/pentaho/visual/views/all.js
impl/client/src/main/javascript/web/pentaho/visual/views/echarts/Abstract.js
impl/client/src/main/javascript/web/pentaho/visual/views/echarts/Funnel.js
impl/client/src/main/javascript/web/pentaho/visual/views/echarts/Gauge.js
impl/client/src/main/resources-filtered/web/common-ui-require-js-cfg.js

Moved common methods to Abstract.js

[BACKLOG-39066] - Create and Add Gauge Charts to the available list of Chart options in Analyzer

---

impl/client/src/main/javascript/web/pentaho/data/_AbstractTable.js
impl/client/src/main/javascript/web/pentaho/visual/models/Radar.js
impl/client/src/main/javascript/web/pentaho/visual/views/echarts/Abstract.js
impl/client/src/main/javascript/web/pentaho/visual/views/echarts/Funnel.js
impl/client/src/main/javascript/web/pentaho/visual/views/echarts/Gauge.js
impl/client/src/main/javascript/web/pentaho/visual/views/echarts/Radar.js

This PR  :
- addresses review comments of #1753 
- allows user to adjust following chart properties via chart options for echarts
- background color, 
- label's font, size, style, & color, 
- position of legend, background color of legend, each legends label's font, size, style, color

[BACKLOG-40336] Link some echart properties with Chart Options

---

impl/client/src/main/javascript/web/pentaho/visual/views/echarts/Abstract.js
impl/client/src/main/javascript/web/pentaho/visual/views/echarts/Funnel.js
impl/client/src/main/javascript/web/pentaho/visual/views/echarts/Gauge.js
impl/client/src/main/javascript/web/pentaho/visual/views/echarts/Radar.js

Merge with: https://github.com/pentaho/pentaho-analyzer/pull/2606
This PR:
- updates color of unselected items when a part of chart is selected
- sets "toggle" as default selection action
- makes sure event handlers are only attached when chart is initialized
- resolves most of the review comments in https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1763#pullrequestreview-2042878339 & https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1766

[BACKLOG-40383] Implement chart Interactions

---

impl/client/src/main/javascript/web/dojo/pentaho/common/MessageBox.js

Addresses PPP-5061: Sanitize messages and title in message box

---

impl/client/pom.xml
impl/client/src/main/assembly/dependencies-js-assembly.xml
impl/client/src/main/javascript/web/bootstrap/bootstrap.js
impl/client/src/main/javascript/web/dojo/dijit/templates/TitlePane.html
impl/client/src/main/javascript/web/dojo/pentaho/common/CheckedMenuItem.html
impl/client/src/main/javascript/web/dojo/pentaho/common/ComboColorPicker.html
impl/client/src/main/javascript/web/dojo/pentaho/common/ListItem.html
impl/client/src/main/javascript/web/dojo/pentaho/common/MenuItem.html
impl/client/src/main/javascript/web/dojo/pentaho/common/MessageBox.html
impl/client/src/main/javascript/web/dojo/pentaho/common/SectionHeader.html
impl/client/src/main/javascript/web/dojo/pentaho/common/SplashScreen.html
impl/client/src/main/javascript/web/dojo/pentaho/common/datasourceselect.html
impl/client/src/main/javascript/web/dojo/pentaho/common/datasourceselect/datasourceselect.html
impl/client/src/test/javascript/testSamples/style-samples.html
impl/client/src/test/javascript/testSamples/tabsettest.html

Reverts pentaho/pentaho-platform-plugin-common-ui#1778

Revert "[PPP-4305] Upgrade boostsrap.js to 3.4.1"

---

impl/client/pom.xml
package-lock.json
package.json

solves issue with build being stuck in 'npm install'

chore: bump puppeter to latest version

---

impl/server/src/main/java/org/pentaho/common/ui/metadata/model/impl/Query.java
impl/server/src/main/java/org/pentaho/common/ui/metadata/service/MetadataServiceUtil.java
impl/server/src/main/java/org/pentaho/common/ui/metadata/service/MetadataServiceUtil2.java
impl/server/src/test/java/org/pentaho/common/ui/metadata/service/MetadataServiceUtil2Test.java
impl/server/src/test/java/org/pentaho/common/ui/metadata/service/MetadataServiceUtilTest.java

[SP-6565]-Backport of PPP-5078 - Insecure deserialization in Pentaho Interactive Reporting (9.3 Suite)
[SP-6565]: https://hv-eng.atlassian.net/browse/SP-6565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6565]-Backport of PPP-5078 - Insecure deserialization in Pentaho Interactive Reporting (9.3 Suite)

---

assemblies/platform-plugin/src/main/resources/plugin.xml
impl/client/src/main/javascript/web/dojo/pentaho/common/Dialog.js
impl/client/src/main/javascript/web/dojo/pentaho/common/FieldsetPane.js
impl/client/src/main/javascript/web/dojo/pentaho/common/SectionHeader.js
impl/client/src/main/javascript/web/dojo/pentaho/common/SplashScreen.js
impl/client/src/main/javascript/web/dojo/pentaho/common/TabSet.js
impl/client/src/main/javascript/web/dojo/pentaho/common/TemplatePickerEmbed.js
impl/client/src/main/javascript/web/dojo/pentaho/common/propertiesPanel/Panel.js
impl/client/src/main/javascript/web/util/xss.js
impl/client/src/test/javascript/util/xss.spec.js

[PPP-5350]-XSS Findings For Pentaho-platform-plugin-common-ui
[PPP-5350]: https://hv-eng.atlassian.net/browse/PPP-5350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-5350]-XSS Findings For Pentaho-platform-plugin-common-ui

---

impl/server/pom.xml
impl/server/src/main/java/org/pentaho/common/ui/models/PermissionsModel.java
impl/server/src/main/java/org/pentaho/common/ui/models/TreeBrowserModel.java
impl/server/src/test/java/org/pentaho/common/ui/models/TreeBrowserMapperTest.java
impl/server/src/test/java/org/pentaho/common/ui/models/TreeBrowserModelUtilsTest.java

[BACKLOG-42753]-Upgrading pentaho-platform-plugin-common-ui from Java EE to Jakarta EE
[BACKLOG-42753]: https://hv-eng.atlassian.net/browse/BACKLOG-42753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-42753]-Upgrading pentaho-platform-plugin-common-ui from Java EE to Jakarta EE

---

impl/client/src/main/javascript/web/util/xss.js
impl/client/src/test/javascript/util/xss.spec.js

Add SanitizeURL Common Utility

[BACKLOG-41215][Add][SanitizeURL]

---

impl/client/src/main/javascript/web/dojo/pentaho/common/Dialog.js
impl/client/src/main/javascript/web/dojo/pentaho/common/FieldsetPane.js
impl/client/src/main/javascript/web/dojo/pentaho/common/FilterDialog.js
impl/client/src/main/javascript/web/dojo/pentaho/common/SectionHeader.js
impl/client/src/main/javascript/web/dojo/pentaho/common/SplashScreen.js
impl/client/src/main/javascript/web/dojo/pentaho/common/TabSet.js
impl/client/src/main/javascript/web/dojo/pentaho/common/TemplatePickerEmbed.js
impl/client/src/main/javascript/web/dojo/pentaho/common/propertiesPanel/Panel.js
impl/client/src/main/javascript/web/vizapi/ccc/sample/sampleVisualization.js

[SP-6639] Backport of PPP-4790 sanitize html to address XSS Vulnerabilities

---

impl/client/src/main/javascript/web/util/xss.js
impl/client/src/test/javascript/util/xss.spec.js

[PPP-5459][Create common-ui Utilities]

---

impl/client/src/main/javascript/web/util/xss.js
impl/client/src/test/javascript/util/xss.spec.js

Add Encode JS common-ui Utility

[PPP-5459][Add Encode common-ui Utility]

---

impl/client/src/main/javascript/web/util/xss.js
impl/client/src/test/javascript/util/xss.spec.js

\cc @Rangashivani
Unit tests started failing after https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1829

test: fix xss util unit tests failures [PPP-5350]

---

README.md
impl/client/pom.xml
package-lock.json
package.json
pom.xml

fix: vulnerable component requirejs [PPP-5516]

---

README.md
impl/client/pom.xml
package-lock.json
package.json
pom.xml

[SP-6819] Backport of PPP-5516 - Vulnerable Component: requirejs 2.3.6 (10.2 Suite)

---

assemblies/client-config/pom.xml
impl/client-config/client-config/pom.xml

[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
